force-app/main/default/objects/Additional_Info_NL_Letter_Of_Liability__c/Additional_Info_NL_Letter_Of_Liability__c.object-meta.xml
<CustomObject>
    <description>A CreditsafeCompanyAdditionalInformationNLLetterOfLiabilityInformation403V2</description>
    <label>Additional Info NL Letter Of Liability</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Additional Info NL Letter Of Liability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Info NL Letter Of Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Info_NL_Letter_Of_Liability__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report Full</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Additional Info NL Letter Of Liabilities</relationshipLabel>
    <relationshipName>Additional_Info_NL_Letter_Of_Liabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/modules/creditSafe/objects/Additional_Information_Historical_Event__c/Additional_Information_Historical_Event__c.object-meta.xml
<CustomObject>
    <description>A CreditsafeCompanyAdditionalInformationHistoricalEventV2</description>
    <label>Additional Information Historical  Event</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Creditsafe Company Additional Info Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Information Historical  Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Information_Historical_Event__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Additional Information Historical  Event</relationshipLabel>
    <relationshipName>Additional_Information_Historical_Event</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Additional_Information_NL_Financial_Item__c/Additional_Information_NL_Financial_Item__c.object-meta.xml
<CustomObject>
    <description>A CreditsafeCompanyAdditionalInformationNLFinancialItemV2</description>
    <label>Additional Information NL Financial Item</label>
    <nameField>
        <displayFormat>FI-{000000}</displayFormat>
        <label>Additional Information NL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Information NL Financial Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Information_NL_Financial_Item__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report Full</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Additional Information NL Financial Item</relationshipLabel>
    <relationshipName>Additional_Information_NL_Financial_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Information_NL_Kvk_Filing__c/Additional_Information_NL_Kvk_Filing__c.object-meta.xml
<CustomObject>
    <description>A CreditsafeCompanyAdditionalInformationNLKvkFilingV2</description>
    <label>Additional Information NL Kvk Filing</label>
    <nameField>
        <displayFormat>Kvk-{000000}</displayFormat>
        <label>Additional Information NL Kvk Filing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Information NL Kvk Filings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/creditSafe/objects/Additional_Information_NL_Kvk_Filing__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Additional Information NL Kvk Filings</relationshipLabel>
    <relationshipName>Additional_Information_NL_Kvk_Filings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Creditsafe_Address__c/Creditsafe_Address__c.object-meta.xml
<CustomObject>
    <description>A creditsafe address of the business</description>
    <label>Creditsafe Address</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Creditsafe Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Creditsafe Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Creditsafe_Address__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report Full</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Creditsafe Addresses</relationshipLabel>
    <relationshipName>Creditsafe_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/modules/creditSafe/objects/Creditsafe_Company_Key_Value__c/Creditsafe_Company_Key_Value__c.object-meta.xml
<CustomObject>
    <description>A CreditsafeCompanyKeyValueV2</description>
    <label>Creditsafe Company Key Value</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Creditsafe Company Key Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Creditsafe Company Key Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/creditSafe/objects/Creditsafe_Company_Key_Value__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Generic Payment Data</relationshipLabel>
    <relationshipName>Creditsafe_Company_Key_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/modules/creditSafe/objects/Creditsafe_Company_Report_Full__c/Creditsafe_Company_Report_Full__c.object-meta.xml
<CustomObject>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Creditsafe Company Report Full Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Creditsafe Company Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/services/CreditSafe/GetCreditsafeFullReportInvocableTest.cls
/**
 * Created by tejaswinidandi on 10/03/2020.
 */

@IsTest
private class GetCreditsafeFullReportInvocableTest {

    @IsTest
    static void testGetCreditSafeReportFullHappyFlow() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsCreditsafe wsCreditsafeService = (IWsCreditsafe)mocks.mock(IWsCreditsafe.class);

        CreditsafeWsdl.CreditsafeCompanyReportFullV2 reportFullV2 = CreditSafeServiceImplTest.createCompanyReportFullV2Mock();

        mocks.startStubbing();
        mocks.when(wsCreditsafeService.creditsafeGetReportFullV2(fflib_Match.anyString(), fflib_Match.anyString(),fflib_Match.anyString())).thenReturn(reportFullV2);
        mocks.stopStubbing();

        Application.Service.setMock(IWsCreditsafe.class, wsCreditsafeService);
        Creditsafe_Company_Report_Full__c reportFull;
        List<Creditsafe_Company_Report_Full__c> reportFulls;
                Test.startTest();
        {
            List<GetCreditsafeFullReportInvocable.CreditsafeReportParameters> parameters = new List<GetCreditsafeFullReportInvocable.CreditsafeReportParameters>();
            parameters.add(new GetCreditsafeFullReportInvocable.CreditsafeReportParameters('BE-X-831382050', 'EN', ''));
            reportFulls = GetCreditsafeFullReportInvocable.getCreditsafeCompanyReportFull(parameters);
        }
        Test.stopTest();
        System.assert(reportFulls.size() > 0);
        reportFull = reportFulls[0];
        System.assert(reportFull != null);

        List<Additional_Info_NL_Letter_Of_Liability__c> additionalInfoNLLetterOfLiabilities = [
                SELECT Id
                FROM Additional_Info_NL_Letter_Of_Liability__c WHERE Creditsafe_Company_Report_Full__c = :reportFull.Id];

        System.assert(additionalInfoNLLetterOfLiabilities.size() == 2);

        List<Additional_Information_NL_Kvk_Filing__c> kvkFilings = [
                SELECT Id
                FROM Additional_Information_NL_Kvk_Filing__c WHERE Creditsafe_Company_Report_Full__c = :reportFull.Id];
        System.assert(kvkFilings.size() == 2);

        List<Additional_Information_NL_Financial_Item__c> financialItems = [
                SELECT Id
                FROM Additional_Information_NL_Financial_Item__c WHERE Creditsafe_Company_Report_Full__c = :reportFull.Id];

        System.assert(financialItems.size() == 2);

        List<Additional_Information_Historical_Event__c> historicalEvents = [
                SELECT Id
                FROM Additional_Information_Historical_Event__c WHERE Creditsafe_Company_Report_Full__c = :reportFull.Id];
        System.assert(historicalEvents.size() == 4);

        List<Creditsafe_Address__c> addresses = [
                SELECT Id
                FROM Creditsafe_Address__c WHERE Creditsafe_Company_Report_Full__c = :reportFull.Id];
        System.assert(addresses.size() == 2);

        List<Creditsafe_Company_Key_Value__c> keyValue = [
                SELECT Id
                FROM Creditsafe_Company_Key_Value__c WHERE Creditsafe_Company_Report_Full__c = :reportFull.Id];
        System.assert(keyValue.size() == 6);

    }

}