force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Logs errors fired throughout the application. Purely to ease the maintenance. No access needed for users of the app or admins.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <description>The cause of the error</description>
    <inlineHelpText>The cause of the error</inlineHelpText>
    <label>Cause</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number the error occurred on.</description>
    <inlineHelpText>The line number the error occurred on.</inlineHelpText>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message logged. Message of the exception if an exception has been logged.</description>
    <inlineHelpText>The message logged</inlineHelpText>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set in the handleAfterEventInsert method to true if an email needs to be send to the support email address configured in the Setting error email. If checked the after insert trigger on Error Log itself will send an email to the support email address. See https://salesforce.stackexchange.com/questions/221708/does-messaging-sendemail-not-work-in-a-platform-event-trigger-context</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>The stacktrace&#39; exception to log</description>
    <inlineHelpText>The stacktrace&#39; exception to log</inlineHelpText>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The exception type</description>
    <inlineHelpText>The exception type</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/ErrorLogUtilTest.cls
/**
 * Created by jaapbranderhorst on 2019-06-19.
 */

@IsTest
private class ErrorLogUtilTest {

    private without sharing class TestException extends Exception {

    }

    @IsTest
    static void testLogException() {
        Test.startTest();
        ErrorLogUtil.logException(new TestException('message'));
        Test.stopTest();
        List<Error_Log__c> logs = [
                SELECT
                        Cause__c,
                        Line_Number__c,
                        Message__c,
                        Stacktrace__c,
                        Type__c
                FROM Error_Log__c];
        System.assertEquals(1, logs.size());
        System.assertEquals('message', logs[0].Message__c);
    }

    @IsTest
    static void testLogExceptionInCatch() {
        Test.startTest();
        try {
            Exception ex = new TestException('test');
            throw ex;
        } catch(Exception ex) {
            ErrorLogUtil.logException(ex);
        }
        Test.stopTest();
        List<Error_Log__c> logs = [
                SELECT
                        Cause__c,
                        Line_Number__c,
                        Message__c,
                        Stacktrace__c,
                        Type__c
                FROM Error_Log__c];
        System.assertEquals(1, logs.size());
        System.assertEquals('test', logs[0].Message__c);
    }

    @IsTest
    static void testLogExceptionWithSystemEmail() {
        Test.startTest();
        ErrorLogUtil.logException(new TestException('test'), true);
        Test.stopTest();
        // System.assertEquals(1, invocations); // doesn't work since sending the email is done in a different thread
        List<Error_Log__c> logs = [
                SELECT
                        Cause__c,
                        Line_Number__c,
                        Message__c,
                        Stacktrace__c,
                        Type__c
                FROM Error_Log__c];
        System.assertEquals(1, logs.size());
        System.assertEquals('test', logs[0].Message__c);
    }

    @IsTest
    static void testLogExceptionReThrown() {
        Boolean exceptionThrown = false;
        try {
            Test.startTest();
            try {
                throw new TestException();
            } catch (Exception ex) {
                ErrorLogUtil.logException(ex);
                throw ex;
            }
        } catch (Exception ex) {
            Test.stopTest();
            exceptionThrown = true;
        }
        System.assertEquals(true, ErrorLogUtil.hasErrorsLogged());
        System.assert(exceptionThrown);
    }

    @IsTest
    static void testSendSupportEmails() {
        List<Error_Log__c> logs = new List<Error_Log__c>();
        for (Integer i = 0; i < 5; i++) {
            logs.add(new Error_Log__c(Message__c = 'test', Send_Email__c = true));
        }
        Test.startTest();
        insert logs;
        System.debug('logs: ' + JSON.serializePretty(logs));
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(1, invocations);
    }

    @IsTest
    static void testHasErrorsLogged() {
        Test.startTest();
        ErrorLogUtil.logException(new TestException());
        Test.stopTest();
        Integer numbersOfErrorsLogged = ErrorLogUtil.getNumberOfErrorsLogged();
        Boolean errorsLogged = ErrorLogUtil.hasErrorsLogged();
        System.assertEquals(true, errorsLogged);
        System.assertEquals(1, numbersOfErrorsLogged);
    }

    @IsTest
    static void testHasNoErrorsLogged() {
        Test.startTest();
        Boolean errorsLogged = ErrorLogUtil.hasErrorsLogged();
        Integer numbersOfErrorsLogged = ErrorLogUtil.getNumberOfErrorsLogged();
        Test.stopTest();
        System.assertEquals(false, errorsLogged);
        System.assertEquals(0, numbersOfErrorsLogged);
    }



}