force-app/main/modules/objects/Protected_Subscriber_Setting__mdt/Protected_Subscriber_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Contains Subscriber settings which 
-Should not be overwritten when a new package version is installed
-Should not be changed through the custom metadata types interface</description>
    <label>Protected Subscriber Setting</label>
    <pluralLabel>Protected Subscriber Settings</pluralLabel>
</CustomObject>

force-app/main/modules/setup/objects/Protected_Subscriber_Setting__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A field to store a description of this setting.</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/modules/setup/objects/Protected_Subscriber_Setting__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <description>A field to store a true or false value for this setting.</description>
    <defaultValue>false</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/modules/setup/objects/Protected_Subscriber_Setting__mdt/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>This field stores an identifier value of another system.</description>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/services/Setup/SetupServiceImplTest.cls
/**
 * Created by Hugo on 04/06/2020.
 */

@IsTest
public with sharing class SetupServiceImplTest {
    @IsTest
    public static void getUpdateSettingsHappyFlowTest(){
        System.runAs(TestUtils.getAdminUser()){
            Test.startTest();
            List<Protected_Subscriber_Setting__mdt> updateTypes = SetupService.getUpdateTypes();
            Test.stopTest();


            //Check response
            System.assertNotEquals(null,updateTypes);
            //Check response size = 21
            System.assertEquals(21,updateTypes.size());

            //Check fields
            System.assertNotEquals(null, updateTypes[0].Description__c);
            System.assertNotEquals(null, updateTypes[0].Enabled__c);
            System.assertNotEquals(null, updateTypes[0].External_Id__c);
        }
    }

    @IsTest
    public static void setUpdateSettingsTest(){

        Map<String,Object> record1 = new Map<String,Object>{
                'developerName' => 'Activity',
                'checked' => false,
                'label' => 'Activity'
        };
        List<Map<String,Object>> l1 = new List<Map<String,Object>>();
        l1.add(record1);

        System.runAs(TestUtils.getAdminUser()){
            //Deploying custom metadata cannot be tested/mocked. It will always throw an error.
            Test.startTest();
            try{
                SetupService.setUpdateTypes(l1);
            }catch (Exception e){
                //Should always return an exception due to the fact that this function cannot be run in test methods.
                System.assertEquals(Label.Error_updating_update_type_settings, e.getMessage());
            }
            Test.stopTest();
        }
    }
}