force-app/main/standard/objects/Error_Events__e/Error_Events__e.object-meta.xml
<CustomObject>
    <description>An event that is fired whenever a Company.info element triggers an error.</description>
    <label>Error Event</label>
    <pluralLabel>Error Events</pluralLabel>
</CustomObject>

force-app/main/standard/objects/Error_Events__e/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <description>The cause of the error</description>
    <label>Cause</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Events__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number the error occurred on.</description>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Events__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message of the event</description>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/standard/objects/Error_Events__e/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if an email needs to be send out to the configured email address.</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/standard/objects/Error_Events__e/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>The stacktrace of an exception to log</description>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/standard/objects/Error_Events__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the error</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Logs errors fired throughout the application. Purely to ease the maintenance. No access needed for users of the app or admins.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <description>The cause of the error</description>
    <inlineHelpText>The cause of the error</inlineHelpText>
    <label>Cause</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number the error occurred on.</description>
    <inlineHelpText>The line number the error occurred on.</inlineHelpText>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message logged. Message of the exception if an exception has been logged.</description>
    <inlineHelpText>The message logged</inlineHelpText>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set in the handleAfterEventInsert method to true if an email needs to be send to the support email address configured in the Setting error email. If checked the after insert trigger on Error Log itself will send an email to the support email address. See https://salesforce.stackexchange.com/questions/221708/does-messaging-sendemail-not-work-in-a-platform-event-trigger-context</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>The stacktrace&#39; exception to log</description>
    <inlineHelpText>The stacktrace&#39; exception to log</inlineHelpText>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The exception type</description>
    <inlineHelpText>The exception type</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Setting__mdt/Error_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <description>To send an email with errors</description>
    <label>Error Log Setting</label>
    <pluralLabel>Error Log Settings</pluralLabel>
</CustomObject>

force-app/main/appsolutelyBaseComponents/errorLogUtil/ErrorLogUtil.cls
/****************************************************************************************
Author          : Jaap Branderhorst
Description     : Error log util class to log error messages to the ErrorLog SObject so even in batches you can review.

CAREFULL: doesn't work when you rollback the transaction.
******************************************************************************************/

public inherited sharing class ErrorLogUtil {

    private class AsyncLogger implements Queueable {
        private Exception ex;
        private Boolean sendEmail;

        public AsyncLogger(Exception ex, Boolean sendEmail) {
            this.ex = ex;
            this.sendEmail = sendEmail;
        }

        public void execute(QueueableContext param1) {
            ErrorLogUtil.logException(ex, sendEmail);
        }
    }

    @TestVisible
    private final static String ERROR_LOG_SETTING_EMAIL = 'Error_Email_Address';

    private static String supportEmailAddress {
        get {
            if (String.isEmpty(supportEmailAddress)) {
                supportEmailAddress = SettingUtils.getSetting(ERROR_LOG_SETTING_EMAIL);
            }
            return supportEmailAddress;
        }
        set;
    }

    /**
     * Logs an exception. This is the main method to be called whenever an exception happens
     *
     * @param e
     */
    public static void logException(Exception e) {
       logException(e, false);
    }

    /**
    *
    *
    * @param e the exception to log
    * @param sendEmail true if an email needs to be send to the in Error_Log_Setting__mdt configured email address
    */
    public static void logException(Exception e, Boolean sendEmail) {
        Error_Events__e error = new Error_Events__e();
        error.Type__c = e.getTypeName();
        error.Cause__c = String.valueOf(e.getCause());
        error.Message__c = e.getMessage();
        error.Line_Number__c = '' + e.getLineNumber();
        error.Stacktrace__c = e.getStackTraceString();
        error.Send_Email__c = sendEmail;
        EventBus.publish(error);
    }

    /**
     * Logs an exception without writing any DML. To be used in AuraEnabled(Cachaeable=true) methods.
     * THE TRANSACTION CANNOT END WITH AN EXCEPTION. NO LOGGING WILL TAKE PLACE. WRAP ANY EXCEPTIONS AND HANDLE THEM IN THE TRANSCATION
     *
     * @param e the exception to log
     * @param sendEmail true if an email needs to be send to the in Error_Log_Setting__mdt configured email address
     */
    public static void logExceptionNoDML(Exception e, Boolean sendEmail) {
        AsyncLogger asyncLogger = new AsyncLogger(e, sendEmail);
        System.enqueueJob(asyncLogger);
    }

    /**
    * Handles the after insert trigger event of the Error_Event__e platform event. Inserts the logged exception into the Error_Log__c custom object.
    *
    * @param events the events to log
    */
    public static void handleAfterEventInsert(List<Error_Events__e> events){
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();
        List<Error_Events__e> emailEvents = new List<Error_Events__e>();
        for(Error_Events__e event : events){
            errorLogs.add(new Error_Log__c(Send_Email__c = event.Send_Email__c, Cause__c = event.Cause__c, Message__c = event.Message__c, Line_Number__c = event.Line_Number__c, Stacktrace__c = event.Stacktrace__c, Type__c = event.Type__c));
        }
        // in system context since this needs to happen always
        insert errorLogs;
    }

    /**
    * Utility method to check if there are errors logged. Handy in test methods.
    *
    * @return true if there are any errors logged. Otherwise false.
    */
    public static Boolean hasErrorsLogged() {
        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c LIMIT 1];
        return (errorLogs.size() == 1);
    }

    /**
    * Utility method that returns the number of errors logged. Handy in test methods.
    *
    * @return the number of errors logged in the database
    */
    public static Integer getNumberOfErrorsLogged() {
        return ([SELECT Id FROM Error_Log__c]).size();
    }

    /**
    * Sends an exception email to the Appsolutely support
    *
    * @param emailEvents the platform events for which to send emails
    */
    @InvocableMethod
    global static void sendSupportEmails(List<Error_Log__c> logs) {
        List<String> messages = new List<String>();
        for (Error_Log__c log : logs) {
            String message = '\n' + 'Type: ' + log.Type__c + '\n' + 'Cause: ' + log.Cause__c + '\n' + 'Message: '
                    + log.Message__c + '\n' + 'Line #: ' + log.Line_Number__c + '\n' + log.Stacktrace__c + '\n';
            messages.add(message);
        }
        //send email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {supportEmailAddress});
        mail.setSubject('Exception(s) from Company.info for Salesforce. Org Id ' + UserInfo.getOrganizationId() + ' and Org Name ' + UserInfo.getOrganizationName());
        mail.setPlainTextBody(messages.toString());

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }


}