force-app/main/standard/objects/Error_Events__e/Error_Events__e.object-meta.xml
<CustomObject>
    <description>An event that is fired whenever a Company.info element triggers an error.</description>
    <label>Error Event</label>
    <pluralLabel>Error Events</pluralLabel>
</CustomObject>

force-app/main/standard/objects/Error_Events__e/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <description>The cause of the error</description>
    <label>Cause</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Events__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number the error occurred on.</description>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Events__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message of the event</description>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/standard/objects/Error_Events__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the error</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/standard/classes/ErrorEventTriggerHandler.cls
/**
 * Created by hugovankrimpen on 12/03/2020.
 */

public with sharing class ErrorEventTriggerHandler {

    public static void AfterInsert(List<Error_Events__e> events){
        for(Error_Events__e event : events){


            String message = '\n' + 'Type: ' + event.Type__c + '\n' + 'Cause: ' + event.Cause__c + '\n' + 'Message: '
                    + event.Message__c + '\n' + 'Line #: ' + event.Line_Number__c;
            ErrorLogUtil.logMessage(message);
        }
    }
}