force-app/main/default/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Annual_Financial_Statement_Summary__c.field-meta.xml
<CustomField>
    <fullName>Annual_Financial_Statement_Summary__c</fullName>
    <description>Financial summary from the last known annual financial statement DutchBusinessAnnualFinancialStatementSummary.</description>
    <label>Annual_Financial Statement Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Assets__c.field-meta.xml
<CustomField>
    <fullName>Assets__c</fullName>
    <description>The amount of assets for the financial year DutchBusinessMoneyV2</description>
    <label>Assets</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Authorized_Share_Capital__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Share_Capital__c</fullName>
    <description>Number indicating the amount of authorized share capital.  The amount of money for which the company is allowed to give out shares.  Dutch: `maatschappelijk kapitaal`.</description>
    <label>Authorized Share Capital</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Authorized_Share_Capital_Currency__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Share_Capital_Currency__c</fullName>
    <label>Currency For Authorized Share Capital</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Chamber_Code__c.field-meta.xml
<CustomField>
    <fullName>Chamber_Code__c</fullName>
    <label>Chamber of Commerce office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>chamber_number</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Chamber_Number__c.field-meta.xml
<CustomField>
    <fullName>Chamber_Number__c</fullName>
    <description>The chamber number is the number of the Chamber of Commerce office which manages this dossier.


01	Noord Nederland
08	Oost Nederland
09	Centraal Gelderland
14	Limburg
17	Brabant
20	Zuid West Nederland
24	Rotterdam
27	Den Haag
30	Midden Nederland
32	Gooi-, Eem- en Flevoland
34	Amsterdam
37	Noordwest-Holland</description>
    <label>Chamber Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Class_Personnel__c.field-meta.xml
<CustomField>
    <fullName>Class_Personnel__c</fullName>
    <description>A classification of the total number of employees (full-time and part-time).  Possible values:
1	no employees
2	1 employee
3	2 to 4 employees
4	5 to 9 employees
5	10 to 19 employees
6	20 to 49 employees
7	50 to 99 employees
8	100 to 199 employees
9	199 to 499 employees
10	500 to 749 employees
11	750 to 999 employees
12	1000 or more employees</description>
    <label>Classification Of Number Of Employees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class_Personnel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Class_Personnel_CI__c.field-meta.xml
<CustomField>
    <fullName>Class_Personnel_CI__c</fullName>
    <label>Number of Employees (Company.info)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class_Personnel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Class_Personnel_Fulltime__c.field-meta.xml
<CustomField>
    <fullName>Class_Personnel_Fulltime__c</fullName>
    <label>Classification Of Fulltime Employees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class_Personnel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Contact_Gender__c.field-meta.xml
<CustomField>
    <fullName>Contact_Gender__c</fullName>
    <label>Contact Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>m</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>f</fullName>
                <label>Female</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Contact_Initials__c.field-meta.xml
<CustomField>
    <fullName>Contact_Initials__c</fullName>
    <description>Initials of the contact</description>
    <label>Contact Initials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Contact_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Contact_Prefix__c</fullName>
    <description>Name prefix of the contact.</description>
    <label>Contact Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Contact_Surname__c.field-meta.xml
<CustomField>
    <fullName>Contact_Surname__c</fullName>
    <description>Surname of the contact.</description>
    <label>Contact Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Contact_Title1__c.field-meta.xml
<CustomField>
    <fullName>Contact_Title1__c</fullName>
    <description>Title of the contact person of this business.</description>
    <label>Contact First Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Contact_Title2__c.field-meta.xml
<CustomField>
    <fullName>Contact_Title2__c</fullName>
    <description>Second title of the contact person of this business.</description>
    <label>Contact Second Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Continuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Continuation_Date__c</fullName>
    <description>The continuation date of the company, if applicable. This is usually the date that the company changed legal form.</description>
    <label>Continuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Creditsafe_Id__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Id__c</fullName>
    <description>The unique credit safe Id. Only filled for records retrieved through Credit Safe.</description>
    <externalId>true</externalId>
    <label>Creditsafe Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Date_of_Last_Account__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Account__c</fullName>
    <label>Date of Last Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Date_of_Last_Change__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Last_Change__c</fullName>
    <label>Date of Last Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/fields/Discontinuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Discontinuation_Date__c</fullName>
    <description>The date when the business was discontinued (Dutch: datum wanneer de activiteiten gestaakt zijn)</description>
    <label>Discontinuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <description>The internet domain name registered by the business</description>
    <label>Domain Name</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Date__c.field-meta.xml
<CustomField>
    <fullName>Establishment_Date__c</fullName>
    <description>The date the establishment started its activities.  This date does not change when the establishment moves to another location.</description>
    <label>Establishment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Founding_Date__c.field-meta.xml
<CustomField>
    <fullName>Founding_Date__c</fullName>
    <label>Founding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Indication_Bankruptcy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if the business is currently registered as bankrupt (Dutch: ‘Faillissement’).</description>
    <label>Indication Bankruptcy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Dip__c.field-meta.xml
<CustomField>
    <fullName>Indication_Dip__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if the business is currently registered as Debtor-in-Possession (Dutch: ‘in Surseance’).</description>
    <label>Debtor in possession</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Economically_Active__c.field-meta.xml
<CustomField>
    <fullName>Indication_Economically_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if the business is economically active. This indication is determined by a formula developed by the ‘Vereninging Kamers van Koophandel’. This should not be interpreted as an indication of whether the business is currently still registered at the Chamber of Commerce: only currently registered businesses are available through our services.</description>
    <label>Economically Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Export__c.field-meta.xml
<CustomField>
    <fullName>Indication_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indication of whether the company does export.  Optional.</description>
    <label>Exports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Import__c.field-meta.xml
<CustomField>
    <fullName>Indication_Import__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indication of whether the company does import.  Optional.</description>
    <label>Imports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Main_Establishment__c.field-meta.xml
<CustomField>
    <fullName>Indication_Main_Establishment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if this is the main establishment of the business.</description>
    <label>Main Establishment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Non_Mailing__c.field-meta.xml
<CustomField>
    <fullName>Indication_Non_Mailing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if the business has specified that the ‘Vereniging Kamers van Koophandel’ and the ‘de kamers van koophandel’ may not supply the business’ information to third parties for direct marketing purposes.</description>
    <label>Non Mailing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Organisation_Code__c.field-meta.xml
<CustomField>
    <fullName>Indication_Organisation_Code__c</fullName>
    <description>Possible values:
O	Business (Dutch: ‘Onderneming)
V	Association (Dutch: ‘Vereniging’)
S	Non-profit organisation (Dutch: ‘Stichting’)
K	Church community (Dutch: ‘Kerkgenootschap’)
&lt;empty&gt;	Unknown</description>
    <label>Organisation Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Association</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Non-profit organisation</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Church community</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Insolvencies__c.field-meta.xml
<CustomField>
    <fullName>Insolvencies__c</fullName>
    <description>Array of DutchBusinessInsolvency entries containing data about the insolvencies.  [optional]</description>
    <label>Insolvencies</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Number Of Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Personnel_CI__c.field-meta.xml
<CustomField>
    <fullName>Personnel_CI__c</fullName>
    <description>The total number of employees as recorded by the company.info software</description>
    <label>Number Of Employees wrt Company Info</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Personnel_Fulltime__c.field-meta.xml
<CustomField>
    <fullName>Personnel_Fulltime__c</fullName>
    <label>Number of Fulltime Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/dutchBusiness/globalValueSets/chamber_number.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <label>Onbekend</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>Noord Nederland</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Oost Nederland</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Centraal Gelderland</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Limburg</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>Brabant</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Zuid West Nederland</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>Rotterdam</label>
    </customValue>
    <customValue>
        <fullName>27</fullName>
        <label>Den Haag</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Midden Nederland</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Gooi-, Eem- en Flevoland</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Amsterdam</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Noordwest-Holland</label>
    </customValue>
    <description>value set for chamber_number__c field on dossier object</description>
    <masterLabel>Chamber Number</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Class_Personnel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <masterLabel>Class Personnel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProcessRemovedDutchDossiersBatchTest.cls
/**
 * Created by jaapbranderhorst on 04/02/2020.
 */

@IsTest
private class ProcessRemovedDutchDossiersBatchTest {

    @IsTest
    static void testNoResults() {
        // given
        // a list of updated  dossiers from the CI backend
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness wsDutchBusinessMock = (IWsDutchBusiness) mocks.mock(IWsDutchBusiness.class);
        mocks.startStubbing();

        mocks.when(wsDutchBusinessMock.dutchBusinessUpdateGetChangedDossiers(fflib_Match.anyDate(), (DutchBusinessWsdl.stringArray) fflib_Match.anyObject(), fflib_Match.integerBetween(1, true, 1, true))).thenReturn(UpdateDossiersBatchTest.getDutchBusinessUpdateReferencePagedResultMock(10, 1, 1, 0, 1));
        mocks.stopStubbing();
        Application.Service.setMock(IWsDutchBusiness.class, wsDutchBusinessMock);
        // with no match with the dossiers currently in SF
        List<Business_Dossier__c> dossiers = UpdateDossiersBatchTest.getBusinessDossiersMock(10, 30, 1, 1);
        insert dossiers;
        dossiers = [
                SELECT
                        Annual_Financial_Statement_Summary__c,
                        Assets__c,
                        Authorized_Share_Capital__c,
                        Authorized_Share_Capital_Currency__c,
                        Chamber_Code__c,
                        Chamber_Number__c,
                        Class_Personnel__c,
                        Class_Personnel_CI__c,
                        Class_Personnel_Fulltime__c,
                        Contact_Gender__c,
                        Contact_Initials__c,
                        Contact_Prefix__c,
                        Contact_Surname__c,
                        Contact_Title1__c,
                        Contact_Title2__c,
                        Continuation_Date__c,
                        Creditsafe_Id__c,
                        Date_of_Last_Account__c,
                        Date_of_Last_Change__c,
                        Discontinuation_Date__c,
                        Domain_Name__c,
                        Dossier_Number__c,
                        Establishment_Date__c,
                        Establishment_Number__c,
                        Founding_Date__c,
                        Indication_Bankruptcy__c,
                        Indication_Dip__c,
                        Indication_Economically_Active__c,
                        Indication_Export__c,
                        Indication_Import__c,
                        Indication_Main_Establishment__c,
                        Indication_Non_Mailing__c,
                        Indication_Organisation_Code__c,
                        Insolvencies__c,
                        Is_Removed__c,
                        Issued_Share_Capital__c,
                        Issued_Share_Capital_Currency__c,
                        Legal_Form_Code__c,
                        Legal_Form_Text__c,
                        Main_Establishment_Number__c,
                        Mobile_Number__c,
                        Number_Of_Subsidiaries__c,
                        Office_Type__c,
                        Paid_Up_Share_Capital__c,
                        Paid_Up_Share_Capital_Currency__c,
                        Parent_Chamber_Of_Commerce_Number__c,
                        Personnel__c,
                        Personnel_CI__c,
                        Personnel_CI_Reference_Date__c,
                        Personnel_Fulltime__c,
                        Personnel_Reference_Date__c,
                        Primary_Sbi_Code__c,
                        Primary_Sbi_Code_Text__c,
                        Profit__c,
                        Registration_Country__c,
                        Rsin_Number__c,
                        Sbi_Collection__c,
                        Secondary_Sbi_Code_1__c,
                        Secondary_Sbi_Code_1_Text__c,
                        Secondary_Sbi_Code_2__c,
                        Secondary_Sbi_Code_2_Text__c,
                        Status__c,
                        Structure__c,
                        Telephone_Number__c,
                        Trade_Name_45__c,
                        Trade_Name_Full__c,
                        Trade_Names__c,
                        Turnover__c,
                        Type__c,
                        Ultimate_Parent_Chamber_Of_Commerce_Nr__c,
                        VAT_Number__c,
                        Year__c,
                        CreatedById,
                        CreatedDate,
                        Id,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Name,
                        OwnerId,
                        RecordTypeId,
                        SystemModstamp
                FROM Business_Dossier__c];

        // when
        // we run the batch
        Test.startTest();
        Database.Batchable<Business_Dossier__c> batch = new ProcessRemovedDutchDossiersBatch();
        Database.executeBatch(batch, 100);
        Test.stopTest();

        // then
        // no dossiers in the DB should be changed
        List<Business_Dossier__c> dossiersToBeAsserted = [
                SELECT
                        Annual_Financial_Statement_Summary__c,
                        Assets__c,
                        Authorized_Share_Capital__c,
                        Authorized_Share_Capital_Currency__c,
                        Chamber_Code__c,
                        Chamber_Number__c,
                        Class_Personnel__c,
                        Class_Personnel_CI__c,
                        Class_Personnel_Fulltime__c,
                        Contact_Gender__c,
                        Contact_Initials__c,
                        Contact_Prefix__c,
                        Contact_Surname__c,
                        Contact_Title1__c,
                        Contact_Title2__c,
                        Continuation_Date__c,
                        Creditsafe_Id__c,
                        Date_of_Last_Account__c,
                        Date_of_Last_Change__c,
                        Discontinuation_Date__c,
                        Domain_Name__c,
                        Dossier_Number__c,
                        Establishment_Date__c,
                        Establishment_Number__c,
                        Founding_Date__c,
                        Indication_Bankruptcy__c,
                        Indication_Dip__c,
                        Indication_Economically_Active__c,
                        Indication_Export__c,
                        Indication_Import__c,
                        Indication_Main_Establishment__c,
                        Indication_Non_Mailing__c,
                        Indication_Organisation_Code__c,
                        Insolvencies__c,
                        Is_Removed__c,
                        Issued_Share_Capital__c,
                        Issued_Share_Capital_Currency__c,
                        Legal_Form_Code__c,
                        Legal_Form_Text__c,
                        Main_Establishment_Number__c,
                        Mobile_Number__c,
                        Number_Of_Subsidiaries__c,
                        Office_Type__c,
                        Paid_Up_Share_Capital__c,
                        Paid_Up_Share_Capital_Currency__c,
                        Parent_Chamber_Of_Commerce_Number__c,
                        Personnel__c,
                        Personnel_CI__c,
                        Personnel_CI_Reference_Date__c,
                        Personnel_Fulltime__c,
                        Personnel_Reference_Date__c,
                        Primary_Sbi_Code__c,
                        Primary_Sbi_Code_Text__c,
                        Profit__c,
                        Registration_Country__c,
                        Rsin_Number__c,
                        Sbi_Collection__c,
                        Secondary_Sbi_Code_1__c,
                        Secondary_Sbi_Code_1_Text__c,
                        Secondary_Sbi_Code_2__c,
                        Secondary_Sbi_Code_2_Text__c,
                        Status__c,
                        Structure__c,
                        Telephone_Number__c,
                        Trade_Name_45__c,
                        Trade_Name_Full__c,
                        Trade_Names__c,
                        Turnover__c,
                        Type__c,
                        Ultimate_Parent_Chamber_Of_Commerce_Nr__c,
                        VAT_Number__c,
                        Year__c,
                        CreatedById,
                        CreatedDate,
                        Id,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Name,
                        OwnerId,
                        RecordTypeId,
                        SystemModstamp
                FROM Business_Dossier__c
        ];
        System.assert(dossiers.size() == dossiersToBeAsserted.size());
        Map<String, Business_Dossier__c> dossiersToBeAssertedByUniqueId = new Map<String, Business_Dossier__c>();
        for (Business_Dossier__c businessDossier : dossiersToBeAsserted) {
            dossiersToBeAssertedByUniqueId.put(businessDossier.Dossier_Number__c + businessDossier.Establishment_Number__c, businessDossier);
        }
        for (Business_Dossier__c businessDossier : dossiers) {
            Business_Dossier__c dossierToBeAsserted = dossiersToBeAssertedByUniqueId.get(businessDossier.Dossier_Number__c + businessDossier.Establishment_Number__c);
            System.assert(dossierToBeAsserted != null);
            System.assert(businessDossier == dossierToBeAsserted);
        }
    }

    @IsTest
    private static void testOnePage() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness wsDutchBusinessMock = (IWsDutchBusiness) mocks.mock(IWsDutchBusiness.class);
        mocks.startStubbing();

        DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult dutchBusinessUpdateReferencePagedResultMock = UpdateDossiersBatchTest.getDutchBusinessUpdateReferencePagedResultMock(10, 1, 1, 1, 1);
        mocks.when(wsDutchBusinessMock.dutchBusinessUpdateGetChangedDossiers(fflib_Match.anyDate(), (DutchBusinessWsdl.stringArray) fflib_Match.anyObject(), fflib_Match.integerBetween(1, true, 1, true))).thenReturn(dutchBusinessUpdateReferencePagedResultMock);
        mocks.stopStubbing();
        Application.Service.setMock(IWsDutchBusiness.class, wsDutchBusinessMock);
        // with a match with the dossiers currently in SF
        List<Business_Dossier__c> dossiers = UpdateDossiersBatchTest.getBusinessDossiersMock(10, 1, 1, 1);
        insert dossiers;
        dossiers = [
                SELECT
                        Annual_Financial_Statement_Summary__c,
                        Assets__c,
                        Authorized_Share_Capital__c,
                        Authorized_Share_Capital_Currency__c,
                        Chamber_Code__c,
                        Chamber_Number__c,
                        Class_Personnel__c,
                        Class_Personnel_CI__c,
                        Class_Personnel_Fulltime__c,
                        Contact_Gender__c,
                        Contact_Initials__c,
                        Contact_Prefix__c,
                        Contact_Surname__c,
                        Contact_Title1__c,
                        Contact_Title2__c,
                        Continuation_Date__c,
                        Creditsafe_Id__c,
                        Date_of_Last_Account__c,
                        Date_of_Last_Change__c,
                        Discontinuation_Date__c,
                        Domain_Name__c,
                        Dossier_Number__c,
                        Establishment_Date__c,
                        Establishment_Number__c,
                        Founding_Date__c,
                        Indication_Bankruptcy__c,
                        Indication_Dip__c,
                        Indication_Economically_Active__c,
                        Indication_Export__c,
                        Indication_Import__c,
                        Indication_Main_Establishment__c,
                        Indication_Non_Mailing__c,
                        Indication_Organisation_Code__c,
                        Insolvencies__c,
                        Is_Removed__c,
                        Issued_Share_Capital__c,
                        Issued_Share_Capital_Currency__c,
                        Legal_Form_Code__c,
                        Legal_Form_Text__c,
                        Main_Establishment_Number__c,
                        Mobile_Number__c,
                        Number_Of_Subsidiaries__c,
                        Office_Type__c,
                        Paid_Up_Share_Capital__c,
                        Paid_Up_Share_Capital_Currency__c,
                        Parent_Chamber_Of_Commerce_Number__c,
                        Personnel__c,
                        Personnel_CI__c,
                        Personnel_CI_Reference_Date__c,
                        Personnel_Fulltime__c,
                        Personnel_Reference_Date__c,
                        Primary_Sbi_Code__c,
                        Primary_Sbi_Code_Text__c,
                        Profit__c,
                        Registration_Country__c,
                        Rsin_Number__c,
                        Sbi_Collection__c,
                        Secondary_Sbi_Code_1__c,
                        Secondary_Sbi_Code_1_Text__c,
                        Secondary_Sbi_Code_2__c,
                        Secondary_Sbi_Code_2_Text__c,
                        Status__c,
                        Structure__c,
                        Telephone_Number__c,
                        Trade_Name_45__c,
                        Trade_Name_Full__c,
                        Trade_Names__c,
                        Turnover__c,
                        Type__c,
                        Ultimate_Parent_Chamber_Of_Commerce_Nr__c,
                        VAT_Number__c,
                        Year__c,
                        CreatedById,
                        CreatedDate,
                        Id,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Name,
                        OwnerId,
                        RecordTypeId,
                        SystemModstamp
                FROM Business_Dossier__c];

        // when
        // we run the batch
        Test.startTest();
        Database.Batchable<Business_Dossier__c> batch = new ProcessRemovedDutchDossiersBatch();
        Database.executeBatch(batch, 100);
        Test.stopTest();

        // then
        // the matching dossiers in the DB should be changed
        List<Business_Dossier__c> dossiersToBeAsserted = [
                SELECT
                        Annual_Financial_Statement_Summary__c,
                        Assets__c,
                        Authorized_Share_Capital__c,
                        Authorized_Share_Capital_Currency__c,
                        Chamber_Code__c,
                        Chamber_Number__c,
                        Class_Personnel__c,
                        Class_Personnel_CI__c,
                        Class_Personnel_Fulltime__c,
                        Contact_Gender__c,
                        Contact_Initials__c,
                        Contact_Prefix__c,
                        Contact_Surname__c,
                        Contact_Title1__c,
                        Contact_Title2__c,
                        Continuation_Date__c,
                        Creditsafe_Id__c,
                        Date_of_Last_Account__c,
                        Date_of_Last_Change__c,
                        Discontinuation_Date__c,
                        Domain_Name__c,
                        Dossier_Number__c,
                        Establishment_Date__c,
                        Establishment_Number__c,
                        Founding_Date__c,
                        Indication_Bankruptcy__c,
                        Indication_Dip__c,
                        Indication_Economically_Active__c,
                        Indication_Export__c,
                        Indication_Import__c,
                        Indication_Main_Establishment__c,
                        Indication_Non_Mailing__c,
                        Indication_Organisation_Code__c,
                        Insolvencies__c,
                        Is_Removed__c,
                        Issued_Share_Capital__c,
                        Issued_Share_Capital_Currency__c,
                        Legal_Form_Code__c,
                        Legal_Form_Text__c,
                        Main_Establishment_Number__c,
                        Mobile_Number__c,
                        Number_Of_Subsidiaries__c,
                        Office_Type__c,
                        Paid_Up_Share_Capital__c,
                        Paid_Up_Share_Capital_Currency__c,
                        Parent_Chamber_Of_Commerce_Number__c,
                        Personnel__c,
                        Personnel_CI__c,
                        Personnel_CI_Reference_Date__c,
                        Personnel_Fulltime__c,
                        Personnel_Reference_Date__c,
                        Primary_Sbi_Code__c,
                        Primary_Sbi_Code_Text__c,
                        Profit__c,
                        Registration_Country__c,
                        Rsin_Number__c,
                        Sbi_Collection__c,
                        Secondary_Sbi_Code_1__c,
                        Secondary_Sbi_Code_1_Text__c,
                        Secondary_Sbi_Code_2__c,
                        Secondary_Sbi_Code_2_Text__c,
                        Status__c,
                        Structure__c,
                        Telephone_Number__c,
                        Trade_Name_45__c,
                        Trade_Name_Full__c,
                        Trade_Names__c,
                        Turnover__c,
                        Type__c,
                        Ultimate_Parent_Chamber_Of_Commerce_Nr__c,
                        VAT_Number__c,
                        Year__c,
                        CreatedById,
                        CreatedDate,
                        Id,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Name,
                        OwnerId,
                        RecordTypeId,
                        SystemModstamp
                FROM Business_Dossier__c WHERE Is_Removed__c = true];
        System.assert(dossiers.size() == dossiersToBeAsserted.size());

    }
}