force-app/main/appsolutelyBaseComponents/settingsUtil/objects/Setting__mdt/Setting__mdt.object-meta.xml
<CustomObject>
    <description>Contains settings in the form of key (developerName) value pairs. The Custom Metadata Type is protected so only within the namespace these settings can be used.</description>
    <label>Setting</label>
    <pluralLabel>Settings</pluralLabel>
</CustomObject>

force-app/main/standard/objects/Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The setting&#39;s value</description>
    <inlineHelpText>The setting&#39;s value</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/standard/objects/Subscriber_Setting__mdt/Subscriber_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings belonging to Appsolutely packages that are visible to the subscriber&#39;s admin and which can be changed by him.</description>
    <label>Subscriber Setting</label>
    <pluralLabel>Subscriber Settings</pluralLabel>
</CustomObject>

force-app/main/standard/objects/Subscriber_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value of the subscriber setting.</description>
    <inlineHelpText>The value of the subscriber setting.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/standard/classes/SettingUtils.cls
/**
 * Created by jaapbranderhorst on 28/03/2020.
 */

public inherited sharing class SettingUtils {

    /**
    * Retrieves a setting with the given name. Throws and logs an exception if the setting cannot be found
    *
    * @param settingName name of the setting
    *
    * @return the value of the setting
    */
    public static String getSetting(String settingName) {
        try {
            String value = ([SELECT Value__c FROM Setting__mdt WHERE DeveloperName = :settingName LIMIT 1]).Value__c;
            return value;
        } catch (Exception ex) {
            ErrorLogUtil.logException(ex);
            throw ex;
        }
    }

    /**
    * Retrieves a subscriber setting with the given name. Throws and logs an exception if the setting cannot be found
    *
    * @param settingName name of the subscriber setting
    *
    * @return the value of the setting
    */
    public static String getSubscriberSetting(String settingName) {
        try {
            String value = ([SELECT Value__c FROM Subscriber_Setting__mdt WHERE DeveloperName = :settingName LIMIT 1]).Value__c;
            return value;
        } catch (Exception ex) {
            ErrorLogUtil.logException(ex);
            throw ex;
        }
    }

}