force-app/main/default/objects/Credentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/Dutch_Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Dutch Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dutch Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dutch Business Dossiers</relationshipLabel>
    <relationshipName>Dutch_Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Chamber_Number__c.field-meta.xml
<CustomField>
    <fullName>Chamber_Number__c</fullName>
    <description>The chamber number is the number of the Chamber of Commerce office which manages this dossier.


01	Noord Nederland
08	Oost Nederland
09	Centraal Gelderland
14	Limburg
17	Brabant
20	Zuid West Nederland
24	Rotterdam
27	Den Haag
30	Midden Nederland
32	Gooi-, Eem- en Flevoland
34	Amsterdam
37	Noordwest-Holland</description>
    <label>Chamber Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01	Noord Nederland</fullName>
            </value>
            <value>
                <fullName>08	Oost Nederland</fullName>
            </value>
            <value>
                <fullName>09	Centraal Gelderland</fullName>
            </value>
            <value>
                <fullName>14	Limburg</fullName>
            </value>
            <value>
                <fullName>17	Brabant</fullName>
            </value>
            <value>
                <fullName>20	Zuid West Nederland</fullName>
            </value>
            <value>
                <fullName>24	Rotterdam</fullName>
            </value>
            <value>
                <fullName>27	Den Haag</fullName>
            </value>
            <value>
                <fullName>30	Midden Nederland</fullName>
            </value>
            <value>
                <fullName>32	Gooi-, Eem- en Flevoland</fullName>
            </value>
            <value>
                <fullName>34	Amsterdam</fullName>
            </value>
            <value>
                <fullName>37	Noordwest-Holland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Indication_Main_Establishment__c.field-meta.xml
<CustomField>
    <fullName>Indication_Main_Establishment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if this is the main establishment of the business.</description>
    <label>Indication Main Establishment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Indication_Organisation_Code__c.field-meta.xml
<CustomField>
    <fullName>Indication_Organisation_Code__c</fullName>
    <description>Possible values:
O	Business (Dutch: ‘Onderneming)
V	Association (Dutch: ‘Vereniging’)
S	Non-profit organisation (Dutch: ‘Stichting’)
K	Church community (Dutch: ‘Kerkgenootschap’)
&lt;empty&gt;	Unknown</description>
    <label>Indication Organisation Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Association</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Non-profit organisation</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Church community</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Legal_Form_Text__c.field-meta.xml
<CustomField>
    <fullName>Legal_Form_Text__c</fullName>
    <description>Description of the legal form (in Dutch).</description>
    <label>Legal Form Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Main_Establishment_Number__c.field-meta.xml
<CustomField>
    <fullName>Main_Establishment_Number__c</fullName>
    <description>The establishment number for the main establishment of the business.  Optional.</description>
    <label>Main Establishment Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Rsin_Number__c.field-meta.xml
<CustomField>
    <fullName>Rsin_Number__c</fullName>
    <description>The 9 number RSIN (`Rechtspersonen Samenwerkingsverbanden Informatie Nummer`) identifying the business’ legal entity.  Optional, businesses with a sole proprietor (`eenmanszaken`) do not have an rsin_number.</description>
    <label>Rsin Number</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Trade_Name_45__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_45__c</fullName>
    <description>Primary name under which the business engages in commercial activity.  Shortened to a maximum of 45 characters.</description>
    <label>Trade Name 45</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CompanyDetailsControllerHelper.cls
/**
* Created by Asifsayyed on 02/12/18.
* @Description:Helper to CompanyDetailsController
* TBD make generic class to take request based on new form params
* TBD Mapping of parameters
* TBD Error Handling
*/
public with sharing class CompanyDetailsControllerHelper {

    private static wwwWebservicesNlSoap.Webservices_nlPort stub;
    private static list<wwwWebservicesNlSoap.DutchBusinessReferenceV2> searchResults;
    private static wwwWebservicesNlSoap.DutchBusinessReferenceV2PagedResult returnedResults;
    private static wwwWebservicesNlSoap.HeaderLoginType header;
    private static string param,postCode,telephoneNumber,domainName;
    public  static Credentials__c cs;

    /**
    * @description :Sets username and password in header
    */
    public static wwwWebservicesNlSoap.HeaderLoginType getAuthentication(){
        CS = Credentials__c.getOrgDefaults();
        header= new wwwWebservicesNlSoap.HeaderLoginType();
        header.userName=cs.Username__c;//'appsolutelytest_bfc9bbb2';
        header.passWord=cs.Password__c;//'5Z9wwVa-hYzy*mFY)VW.-U$!5Vu}Ymc{';//
        System.debug('get auth');
        System.debug(header);
        return header;
    }

    /**
    * @description :Sets header
    * @param String searchText
    */
    public static wwwWebservicesNlSoap.DutchBusinessReferenceV2[] search(CompanyDetailsControllerHelper.CompanySearchDto searchParams){
        // Handle valid postcodes that the web service does not like
        searchParams.postcode = searchParams.postcode.replaceAll('(\\s+)', '').toUpperCase();

        stub=new wwwWebservicesNlSoap.Webservices_nlPort();
        stub.HeaderLogin= getAuthentication();
        try{
            returnedResults=stub.dutchBusinessSearchParametersV2(searchParams.name,searchParams.city,searchParams.street,searchParams.postcode,null,null,searchParams.phone,searchParams.domain,Constants.Strict_Search,Constants.paramInt);
        }
        catch (System.CalloutException ex){
            System.debug('ERROR:' + ex.getMessage());
            throw new AuraHandledException(ex.getMessage());
        }

        if(returnedResults.results.item.size()>0){
            searchResults=returnedResults.results.item;
        }
        else{
            System.debug('no items');
            // searchResults=returnedResults;
        }
        //return parsed result
        return searchResults;
    }

    public static wwwWebservicesNlSoap.DutchBusinessDossierV3 getInfo(String dossierNumber) {
        System.debug('getInfo');
        System.debug(dossierNumber);
        stub=new wwwWebservicesNlSoap.Webservices_nlPort(); 
        stub.HeaderLogin= getAuthentication();
        try{
            wwwWebservicesNlSoap.DutchBusinessDossierV3 response = stub.dutchBusinessGetDossierV3(dossierNumber, '000036043249');
            System.debug('RETURNED');
            System.debug(response);
            return response;
        }
        catch (System.CalloutException ex){
            System.debug('ERROR:' + ex.getMessage());
            throw new AuraHandledException(ex.getMessage());
        }
    }

    public static Id saveDutchBusinessDossier(wwwWebservicesNlSoap.DutchBusinessDossierV3 dossier, Id accountId) {
        // Condense all trade names into single field, seperated by new lines.
        String trade_names = '';
        for (Integer i = 0; i < dossier.trade_names.item.size(); i++) {
            trade_names += dossier.trade_names.item[i] + '/n';
        }

        // @todo add addresses and everything from 'Contact person' on.
        Dutch_Business_Dossier__c d = new Dutch_Business_Dossier__c(
            Account__c = accountId,
            Name = dossier.legal_name,
            Dossier_Number__c = Integer.valueOf(dossier.dossier_number),
            Establishment_Number__c = Integer.valueOf(dossier.establishment_number),
            Main_Establishment_Number__c = Integer.valueOf(dossier.main_establishment_number),
            Indication_Main_Establishment__c = Boolean.valueOf(dossier.indication_main_establishment),
            Rsin_Number__c = Integer.valueOf(dossier.rsin_number),
            Chamber_Number__c = Integer.valueOf(dossier.chamber_number),
            Legal_Form_Code__c = Integer.valueOf(dossier.legal_form_code),
            Legal_Form_Text__c = String.valueOf(dossier.legal_form_text),
            Indication_Organisation_Code__c = String.valueOf(dossier.indication_organisation_code),
            Trade_Name_45__c = dossier.trade_name_45,
            Trade_Name_Full__c = dossier.trade_name_full,
            Trade_Names__c = trade_names,
            Telephone_Number__c = dossier.telephone_number,
            Mobile_Number__c = dossier.mobile_number,
            Domain_Name__c = dossier.domain_name
        );

        // @todo add security checking
        insert d;

        return d.Id;
    }

    public class CompanySearchDto {
        public string name;
        public string domain;
        public string phone;
        public string street;
        public string city;
        public string postcode;
        public string province;
        public string country;
    }


}