force-app/main/default/objects/Credentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/modules/setup/CompanyInfoLoginController.cls
/**
 * Created by jaapbranderhorst on 09/04/2020.
 */

public inherited sharing class CompanyInfoLoginController {

    public class Credentials {
        @AuraEnabled
        public String username;

        @AuraEnabled
        public String password;

        public Credentials(Credentials__c credentials) {
            this.username = credentials.Username__c;
            this.password = credentials.Password__c;
        }
    }

    @AuraEnabled
    public static void saveUsernamePassword(String username, String password) {
        try {
            BusinessAccountingService.saveDataUserCredentials(username, password);
        } catch(Exception ex) { // do not log the error otherwise we can see the username/password entered maybe
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static AuraResponseWrapper getCredentials(){
        try {
            return new AuraResponseWrapper(new Credentials(BusinessAccountingService.getCredentials()));
        } catch(Exception ex) {
            return new AuraResponseWrapper(ex, true, true);
        }
    }

}