force-app/main/default/objects/Credentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/webServices/impl/classes/WebservicesNlSOAPImplTest.cls
@isTest
public with sharing class WebservicesNlSOAPImplTest {
    @isTest
    public static void userContextOrgActive(){
        
        Credentials__c CS = Credentials__c.getOrgDefaults();
        cs.Username__c = 'mock';
        cs.Password__c = 'mock';
        insert cs;
        Test.startTest();
        boolean error = false;
            try{IWebservicesNlSOAP service = WebservicesNlSOAP.newInstance();}catch(BdsException e){error = true;}
        Test.stopTest();
        system.assert(!error);  
    }

   /* @isTest
    public static void userContextOrgNotActive(){
        
        Test.startTest();
        boolean error = false;
            try{IWebservicesNlSOAP service = WebservicesNlSOAP.newInstance();}catch(BdsException e){error = true;}
        Test.stopTest();
        system.assert(error);  
    }*/
    

}