force-app/main/default/objects/Credentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/services/impl/classes/BusinessAccountingServiceImplTest.cls
@isTest
public with sharing class BusinessAccountingServiceImplTest {


    @isTest
    public static void onboardCustomer(){




    }


    @isTest
    public static void testCreateCIUser(){


    }

    @isTest
    public static void testGetUserOnboardedFail(){
        system.assert(!BusinessAccountingServiceImpl.GetUserOnboarded());

    }

    @isTest
    public static void testGetUserOnboardedSuccess(){
        Credentials__c CS = Credentials__c.getOrgDefaults();
        cs.Username__c = 'mock';
        cs.Password__c = 'mock';
        insert cs;
        system.assert(BusinessAccountingServiceImpl.GetUserOnboarded());

    }

    @isTest
    public static void testAddBudget(){


    }
    @isTest
    public static void testGetBalance(){

    }



}