force-app/main/default/objects/International_Address__c/International_Address__c.object-meta.xml
<CustomObject>
    <label>International Address</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>International Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>International Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/modules/address/objects/International_Address__c/fields/CeBuco_Code__c.field-meta.xml
<CustomField>
    <fullName>CeBuco_Code__c</fullName>
    <description>Code given by CeBuCo (Centraal Bureau voor Courantenpubliciteit).  Range: ‘0’-’999’</description>
    <label>CeBuco Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/City_Extract__c.field-meta.xml
<CustomField>
    <fullName>City_Extract__c</fullName>
    <description>Four letter abbreviation of the city name as used by TPG Post; In capitals without punctuation marks.</description>
    <label>City Extract</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/City_Id__c.field-meta.xml
<CustomField>
    <fullName>City_Id__c</fullName>
    <description>Webservices.nl identifier for the city.</description>
    <label>City Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/City_Ptt__c.field-meta.xml
<CustomField>
    <fullName>City_Ptt__c</fullName>
    <description>City name in accordance with the PTT standard; In capitals.  Maximum length of 18 characters.</description>
    <label>City Ptt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/House_Number_Addition__c.field-meta.xml
<CustomField>
    <fullName>House_Number_Addition__c</fullName>
    <description>House number of a perceel.  In case of a Postbus match the house number will always be 0.  Range: 0-99999</description>
    <label>House Number Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/House_Number_From__c.field-meta.xml
<CustomField>
    <fullName>House_Number_From__c</fullName>
    <description>Lowest house number of a postcode range.  Range: 0-99999</description>
    <label>House Number From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/House_Number_To__c.field-meta.xml
<CustomField>
    <fullName>House_Number_To__c</fullName>
    <description>Highest house number of a postcode range.  Range: 0-99999</description>
    <label>House Number To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Letter_Combination__c.field-meta.xml
<CustomField>
    <fullName>Letter_Combination__c</fullName>
    <description>Two character lettercombination (second part of a postcode).  Range: ‘AA’-’ZZ’</description>
    <label>Letter Combination</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <description>Municipality name in capital letters.  The municipality name does not contain apostrophes, but may contain dashes.  Examples: “BAARLE-NASSAU”, “S GRAVENHAGE”.</description>
    <label>Municipality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Municipality_Code__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Code__c</fullName>
    <description>Code given by the CBS (Centraal Bureau Statistiek).  Range: ‘0’-’9999’</description>
    <label>Municipality Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Municipality_Id__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Id__c</fullName>
    <description>Webservices.nl identifier for the municipality.</description>
    <label>Municipality Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Perceel_Id__c.field-meta.xml
<CustomField>
    <fullName>Perceel_Id__c</fullName>
    <description>Webservices.nl identifier for this parcel.</description>
    <label>Perceel Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Perceel_Number__c.field-meta.xml
<CustomField>
    <fullName>Perceel_Number__c</fullName>
    <description>Unique number for a perceel / delivery point, assigned by TPG.  In case of a Postbus address match perceelnummer will always be 0.</description>
    <label>Perceel Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province or state.</description>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Province_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Code__c</fullName>
    <description>Code of the province, a single letter</description>
    <label>Province Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Reeks_Id__c.field-meta.xml
<CustomField>
    <fullName>Reeks_Id__c</fullName>
    <description>Webservices.nl identifier for this house number range.</description>
    <label>Reeks Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Reeks_Indication__c.field-meta.xml
<CustomField>
    <fullName>Reeks_Indication__c</fullName>
    <description>Postcode range type.  Range: {‘0’,’1’,’ ‘};
’0’	range of odd house numbers,
’1’	range of even house numbers,
’ ‘	vacant</description>
    <label>Reeks Indication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street name of the address</description>
    <inlineHelpText>Street name of the address</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Id__c.field-meta.xml
<CustomField>
    <fullName>Street_Id__c</fullName>
    <description>Webservices.nl identifier for the street.</description>
    <label>Street Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Name_Extract__c.field-meta.xml
<CustomField>
    <fullName>Street_Name_Extract__c</fullName>
    <description>5 letter abbreviation of the street name as used by TPG Post; In capitals without punctuation marks.</description>
    <label>Street Name Extract</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Name_Nen__c.field-meta.xml
<CustomField>
    <fullName>Street_Name_Nen__c</fullName>
    <description>Street name in accordance with NEN 5825 conventions; In capital and lowercase letters, including punctuation marks.  This field is at most 24 characters in length.  Longer street names are shortened using the NEN 5825 rules.  Filled with ‘Postbus’ in case it is a range of PO boxes.</description>
    <label>Street Name Nen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Name_Ptt__c.field-meta.xml
<CustomField>
    <fullName>Street_Name_Ptt__c</fullName>
    <description>Street name in accordance with TPG Post conventions; In capitals without punctuation marks.  Filled with ‘POSTBUS’ in case it is a range of PO boxes.  Maximum length of 17 characters.</description>
    <label>Street Name Ptt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/services/Address/AddressServiceImplTest.cls
/**
 * Created by tejaswinidandi on 12/06/2020.
 */

@IsTest
private class AddressServiceImplTest {

    @IsTest
    static void dutchAddressSearchTest() {

        // given a webservice returning two Address objects
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IWsAddress wsAddress = (IWsAddress)mocks.mock(IWsAddress.class);

        mocks.startStubbing();
        AddressWsdl.ResultInfo resultInfo = new AddressWsdl.ResultInfo();
        AddressWsdl.PerceelArray perceelArray = new AddressWsdl.PerceelArray();
        perceelArray.item = new List<AddressWsdl.Perceel>();
        AddressWsdl.PerceelSearchPartsPagedResult returnedResults = new AddressWsdl.PerceelSearchPartsPagedResult();
        resultInfo.curpage = 1;
        resultInfo.maxresults = 500;
        resultInfo.numpages = 1;
        resultInfo.numresults = 2;
        resultInfo.perpage = 10;

        for (Integer i = 0; i < 2; i++) {
            AddressWsdl.Perceel perceelAddress = new AddressWsdl.Perceel();
            perceelAddress.provinciecode = '' + i;
            perceelAddress.cebucocode = i;
            perceelAddress.plaatsnaam_extract = 'plaatsnaam_extract' + i;
            perceelAddress.plaatsnaam = 'plaatsnaam' + i;
            perceelAddress.plaatsnaam_ptt = 'plaatsnaam_ptt' + i;
            perceelAddress.plaatsid = i;
            perceelAddress.straatnaam_extract = 'straatnaam_extract' + i;
            perceelAddress.straatnaam = 'straatnaam' + i;
            perceelAddress.straatnaam_ptt = 'straatnaam_ptt' + i;
            perceelAddress.straatnaam_nen = 'straatnaam_nen' + i;
            perceelAddress.straatid = i;
            perceelAddress.reeksindicatie = 'reeksindicatie' + i;
            perceelAddress.wijkcode = 'wijkcode' + i;
            perceelAddress.reeksid = i;
            perceelAddress.perceelnummer = i;
            perceelAddress.huisnr_toevoeging = 'a' + i;
            perceelAddress.provincienaam = 'provincienaam' + i;
            perceelAddress.gemeenteid = i;
            perceelAddress.gemeentecode = i;
            perceelAddress.gemeentenaam = 'gemeentenaam' + i;
            perceelAddress.lettercombinatie = 'lettercombinatie' + i;
            perceelAddress.huisnr_tm = i;
            perceelAddress.huisnr_van = i * 10;
            perceelAddress.perceelid = i;
            perceelArray.item.add(perceelAddress);
        }
        returnedResults.paging = resultInfo;
        returnedResults.results = perceelArray;
        mocks.when(wsAddress.addressPerceelFullParameterSearchV2( 'province', 'district', 'city', 'street', 1,
                'houseNoAddition', 'nbcode', 'lettercombination', 'addresstype', 1)).thenReturn(returnedResults);
        mocks.stopStubbing();

        Application.Service.setMock(IWsAddress.class, wsAddress);

        // when
        Test.startTest();
        List<International_Address__c> internationalAddresses = AddressService.dutchAddressSearch('org', 'province', 'district', 'city', 'street', 1, 'houseNoAddition', 'nbcode', 'lettercombination', 'addresstype');
        Test.stopTest();

        // then
        System.assertEquals(2, internationalAddresses.size());
        for (Integer i = internationalAddresses.size(); i == 1; i--) {
            International_Address__c addressToTest = internationalAddresses.get(i-1);
            System.assertEquals( '' + i, addressToTest.Province_Code__c);
            System.assertEquals( i, addressToTest.CeBuco_Code__c);
            System.assertEquals('plaatsnaam_extract' + i, addressToTest.City_Extract__c);
            System.assertEquals('plaatsnaam' + i, addressToTest.Locality__c);
            System.assertEquals('plaatsnaam_ptt' + i, addressToTest.City_Ptt__c);
            System.assertEquals( i, addressToTest.City_Id__c);
            System.assertEquals('straatnaam_extract' + i, addressToTest.Street_Name_Extract__c);
            System.assertEquals('straatnaam' + i, addressToTest.Street__c);
            System.assertEquals('straatnaam_ptt' + i, addressToTest.Street_Name_Ptt__c);
            System.assertEquals('straatnaam_nen' + i, addressToTest.Street_Name_Nen__c);
            System.assertEquals( i, addressToTest.Street_Id__c);
            System.assertEquals('reeksindicatie' + i, addressToTest.Reeks_Indication__c);
            System.assertEquals( i, addressToTest.Reeks_Id__c);
            System.assertEquals('wijkcode' + i, addressToTest.Postcode__c);
            System.assertEquals( i, addressToTest.Perceel_Number__c);
            System.assertEquals( 'a' + i, addressToTest.House_Number_Addition__c);
            System.assertEquals( 'provincienaam' + i, addressToTest.Province__c);
            System.assertEquals( i, addressToTest.House_Number_From__c);
            System.assertEquals( i * 10, addressToTest.House_Number_To__c);
            System.assertEquals( i , addressToTest.Perceel_Id__c);
            System.assertEquals( i, addressToTest.Municipality_Id__c);
            System.assertEquals( i, addressToTest.Municipality_Code__c);
            System.assertEquals( 'gemeentenaam' + i, addressToTest.Municipality__c);
            System.assertEquals( 'lettercombinatie' + i, addressToTest.Letter_Combination__c);
        }

    }
}