force-app/main/default/objects/International_Address__c/International_Address__c.object-meta.xml
<CustomObject>
    <label>International Address</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>International Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>International Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/modules/address/objects/International_Address__c/fields/CeBuco_Code__c.field-meta.xml
<CustomField>
    <fullName>CeBuco_Code__c</fullName>
    <description>Code given by CeBuCo (Centraal Bureau voor Courantenpubliciteit).  Range: ‘0’-’999’</description>
    <label>CeBuco Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/City_Extract__c.field-meta.xml
<CustomField>
    <fullName>City_Extract__c</fullName>
    <description>Four letter abbreviation of the city name as used by TPG Post; In capitals without punctuation marks.</description>
    <label>City Extract</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/City_Id__c.field-meta.xml
<CustomField>
    <fullName>City_Id__c</fullName>
    <description>Webservices.nl identifier for the city.</description>
    <label>City Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/City_Ptt__c.field-meta.xml
<CustomField>
    <fullName>City_Ptt__c</fullName>
    <description>City name in accordance with the PTT standard; In capitals.  Maximum length of 18 characters.</description>
    <label>City Ptt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <description>Complete formatted address</description>
    <inlineHelpText>Complete formatted address</inlineHelpText>
    <label>Formatted Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number of the address, if available.</description>
    <inlineHelpText>House number of the address, if available.</inlineHelpText>
    <label>House Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/House_Number_Addition__c.field-meta.xml
<CustomField>
    <fullName>House_Number_Addition__c</fullName>
    <description>House number of a perceel.  In case of a Postbus match the house number will always be 0.  Range: 0-99999</description>
    <label>House Number Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/House_Number_From__c.field-meta.xml
<CustomField>
    <fullName>House_Number_From__c</fullName>
    <description>Lowest house number of a postcode range.  Range: 0-99999</description>
    <label>House Number From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/House_Number_To__c.field-meta.xml
<CustomField>
    <fullName>House_Number_To__c</fullName>
    <description>Highest house number of a postcode range.  Range: 0-99999</description>
    <label>House Number To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Letter_Combination__c.field-meta.xml
<CustomField>
    <fullName>Letter_Combination__c</fullName>
    <description>Two character lettercombination (second part of a postcode).  Range: ‘AA’-’ZZ’</description>
    <label>Letter Combination</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <description>Municipality name in capital letters.  The municipality name does not contain apostrophes, but may contain dashes.  Examples: “BAARLE-NASSAU”, “S GRAVENHAGE”.</description>
    <label>Municipality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Municipality_Code__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Code__c</fullName>
    <description>Code given by the CBS (Centraal Bureau Statistiek).  Range: ‘0’-’9999’</description>
    <label>Municipality Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Municipality_Id__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Id__c</fullName>
    <description>Webservices.nl identifier for the municipality.</description>
    <label>Municipality Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Perceel_Id__c.field-meta.xml
<CustomField>
    <fullName>Perceel_Id__c</fullName>
    <description>Webservices.nl identifier for this parcel.</description>
    <label>Perceel Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Perceel_Number__c.field-meta.xml
<CustomField>
    <fullName>Perceel_Number__c</fullName>
    <description>Unique number for a perceel / delivery point, assigned by TPG.  In case of a Postbus address match perceelnummer will always be 0.</description>
    <label>Perceel Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province or state.</description>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Province_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_Code__c</fullName>
    <description>Code of the province, a single letter</description>
    <label>Province Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Reeks_Id__c.field-meta.xml
<CustomField>
    <fullName>Reeks_Id__c</fullName>
    <description>Webservices.nl identifier for this house number range.</description>
    <label>Reeks Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Reeks_Indication__c.field-meta.xml
<CustomField>
    <fullName>Reeks_Indication__c</fullName>
    <description>Postcode range type.  Range: {‘0’,’1’,’ ‘};
’0’	range of odd house numbers,
’1’	range of even house numbers,
’ ‘	vacant</description>
    <label>Reeks Indication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street name of the address</description>
    <inlineHelpText>Street name of the address</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Id__c.field-meta.xml
<CustomField>
    <fullName>Street_Id__c</fullName>
    <description>Webservices.nl identifier for the street.</description>
    <label>Street Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Name_Extract__c.field-meta.xml
<CustomField>
    <fullName>Street_Name_Extract__c</fullName>
    <description>5 letter abbreviation of the street name as used by TPG Post; In capitals without punctuation marks.</description>
    <label>Street Name Extract</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Name_Nen__c.field-meta.xml
<CustomField>
    <fullName>Street_Name_Nen__c</fullName>
    <description>Street name in accordance with NEN 5825 conventions; In capital and lowercase letters, including punctuation marks.  This field is at most 24 characters in length.  Longer street names are shortened using the NEN 5825 rules.  Filled with ‘Postbus’ in case it is a range of PO boxes.</description>
    <label>Street Name Nen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Name_Ptt__c.field-meta.xml
<CustomField>
    <fullName>Street_Name_Ptt__c</fullName>
    <description>Street name in accordance with TPG Post conventions; In capitals without punctuation marks.  Filled with ‘POSTBUS’ in case it is a range of PO boxes.  Maximum length of 17 characters.</description>
    <label>Street Name Ptt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/recordTypes/Dutch_Address.recordType-meta.xml
<RecordType>
    <fullName>Dutch_Address</fullName>
    <active>true</active>
    <label>Dutch Address</label>
</RecordType>

force-app/main/services/Address/AddressServiceImpl.cls
/**
 * Created by tejaswinidandi on 15/05/2020.
 */

public with sharing class AddressServiceImpl implements IAddressService {

    public static final Integer MAX_SEARCH_RESULTS = 1000;

    public List<International_Address__c> dutchAddressSearch(String province,String district,String city,String street,Integer houseNo,String houseNoAddition,String nbcode,String lettercombination,String addresstype){

        List<International_Address__c> dutchAddresses = new List<International_Address__c>();
        List<AddressWsdl.Perceel> addresses = searchForDutchAddressInCompanyInfo(province, district, city, street, houseNo, houseNoAddition, nbcode, lettercombination, addresstype);
        
        for (AddressWsdl.Perceel addressPerceel : addresses) {
            dutchAddresses.add(mapAddressPerceelToInternationalAddress(addressPerceel));
        }
        
        return dutchAddresses;
    }

    private List<AddressWsdl.Perceel> searchForDutchAddressInCompanyInfo(String province,String district,String city,String street,Integer houseNo,String houseNoAddition,String nbcode,String lettercombination,String addresstype){
        List<AddressWsdl.Perceel> searchResults = new List<AddressWsdl.Perceel>();
        AddressWsdl.PerceelSearchPartsPagedResult returnedResults = WsAddress.addressPerceelFullParameterSearchV2(province, district, city, street, houseNo, houseNoAddition, nbcode, lettercombination, addresstype, 1);
        if (returnedResults != null && returnedResults.results != null && returnedResults.results.item != null) {
            searchResults.addAll(returnedResults.results.item);
            Integer numPages = returnedResults.paging.numpages;
            for (Integer i = 2; i <= numPages && searchResults.size() < MAX_SEARCH_RESULTS; i++) {
                returnedResults = WsAddress.addressPerceelFullParameterSearchV2(province, district, city, street, houseNo, houseNoAddition, nbcode, lettercombination, addresstype, i);
                searchResults.addAll(returnedResults.results.item);
            }
        }
        return searchResults;
    }
    
    private International_Address__c mapAddressPerceelToInternationalAddress(AddressWsdl.Perceel addressPerceel) {
        International_Address__c dutchAddres = new International_Address__c();
        dutchAddres.Perceel_Id__c = addressPerceel.perceelid;
        dutchAddres.House_Number__c = String.valueOf(addressPerceel.huisnr);
        dutchAddres.House_Number_Addition__c = addressPerceel.huisnr_toevoeging;
        dutchAddres.Perceel_Number__c = addressPerceel.perceelnummer;
        dutchAddres.Reeks_Id__c = addressPerceel.reeksid;
        dutchAddres.House_Number_From__c = addressPerceel.huisnr_van;
        dutchAddres.House_Number_To__c = addressPerceel.huisnr_tm;
        dutchAddres.Postcode__c = addressPerceel.wijkcode;
        dutchAddres.Reeks_Indication__c = addressPerceel.reeksindicatie;
        dutchAddres.Letter_Combination__c = addressPerceel.lettercombinatie;
        dutchAddres.Street_Id__c = addressPerceel.straatid;
        dutchAddres.Street__c = addressPerceel.straatnaam;
        dutchAddres.Street_Name_Nen__c = addressPerceel.straatnaam_nen;
        dutchAddres.Street_Name_Ptt__c = addressPerceel.straatnaam_ptt;
        dutchAddres.Street_Name_Extract__c = addressPerceel.straatnaam_extract;
        dutchAddres.City_Id__c = addressPerceel.plaatsid;
        dutchAddres.City_Ptt__c = addressPerceel.plaatsnaam_ptt;
        dutchAddres.City_Extract__c = addressPerceel.plaatsnaam_extract;
        dutchAddres.Locality__c = addressPerceel.plaatsnaam;
        dutchAddres.Municipality__c = addressPerceel.gemeentenaam;
        dutchAddres.Municipality_Code__c = addressPerceel.gemeentecode;
        dutchAddres.Municipality_Id__c = addressPerceel.gemeenteid;
        dutchAddres.Province__c = addressPerceel.provincienaam;
        dutchAddres.Province_Code__c = addressPerceel.provinciecode;
        dutchAddres.CeBuco_Code__c = addressPerceel.cebucocode;
        dutchAddres.Formatted_Address__c = addressPerceel.straatnaam + String.valueOf(addressPerceel.huisnr) ;
        dutchAddres.RecordTypeId = Schema.SObjectType.International_Address__c.getRecordTypeInfosByDeveloperName().get('Dutch_Address').recordTypeId;

        return dutchAddres;
    }

}