force-app/main/default/objects/International_Address__c/International_Address__c.object-meta.xml
<CustomObject>
    <label>International Address</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>International Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>International Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/International_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country of the address.</description>
    <inlineHelpText>Country of the address.</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/selectors/InternationalAddressSelector/InternationalAddressSelectorTest.cls
/**
 * Created by tejaswinidandi on 23/04/2020.
 */

@IsTest
private class InternationalAddressSelectorTest {

    @TestSetup
    static void setup() {
        List<International_Address__c> internationalAddresses = new List<International_Address__c>();
        for (Integer i = 0; i < 10; i++) {
            internationalAddresses.add(new International_Address__c(Country__c = 'NL' + i, Postcode__c = 'P' + i));
        }
        insert internationalAddresses;
    }

    @IsTest
    static void testSelectById() {
        Map<Id, International_Address__c> internationalAddressesByIds = new Map<Id, International_Address__c>([SELECT Id FROM International_Address__c]);
        Test.startTest();
        List<International_Address__c> internationalAddresses = InternationalAddressSelector.newInstance().selectById(internationalAddressesByIds.keySet());
        System.assert(internationalAddresses.size() == 10);
    }
}