force-app/main/default/objects/International_Address__c/International_Address__c.object-meta.xml
<CustomObject>
    <label>International Address</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>International Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>International Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/modules/address/objects/International_Address__c/fields/Alpha_2_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Country_Code__c</fullName>
    <description>The ISO 3166 Alpha 2 country code. Set based on the country code whilst retrieving the international address.</description>
    <inlineHelpText>The ISO 3166 Alpha 2 country code</inlineHelpText>
    <label>Alpha 2 Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Building_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Building_Match_Status__c</fullName>
    <description>Describes how the building element matches the available reference data.</description>
    <inlineHelpText>Describes how the building element matches the available reference data.</inlineHelpText>
    <label>Building Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Building_Number_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Building_Number_Match_Status__c</fullName>
    <description>Describes how the building number element matches the available reference data.</description>
    <inlineHelpText>Describes how the building number element matches the available reference data.</inlineHelpText>
    <label>Building Number Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Building_Number_Result_Status__c.field-meta.xml
<CustomField>
    <fullName>Building_Number_Result_Status__c</fullName>
    <description>Describes how the building number element has been modified</description>
    <inlineHelpText>Describes how the building number element has been modified</inlineHelpText>
    <label>Building Number Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Result_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Name or contact information of person.</description>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country of the address.</description>
    <inlineHelpText>Country of the address.</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Country_Specific_Locality__c.field-meta.xml
<CustomField>
    <fullName>Country_Specific_Locality__c</fullName>
    <description>Country specific alternative notation for locality</description>
    <inlineHelpText>Country specific alternative notation for locality</inlineHelpText>
    <label>Country Specific Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <description>Local delivery address</description>
    <inlineHelpText>Local delivery address</inlineHelpText>
    <label>Delivery Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Name or description of the department, if available.</description>
    <inlineHelpText>Name or description of the department, if available.</inlineHelpText>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <description>Complete formatted address</description>
    <inlineHelpText>Complete formatted address</inlineHelpText>
    <label>Formatted Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number of the address, if available.</description>
    <inlineHelpText>House number of the address, if available.</inlineHelpText>
    <label>House Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>This field will hold language</description>
    <label>Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Locality_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Locality_Match_Status__c</fullName>
    <inlineHelpText>Describes how the locality element matches the available reference data.</inlineHelpText>
    <label>Locality Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Locality_Result_Status__c.field-meta.xml
<CustomField>
    <fullName>Locality_Result_Status__c</fullName>
    <description>Describes how the locality element has been modified</description>
    <inlineHelpText>Describes how the locality element has been modified</inlineHelpText>
    <label>Locality Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Result_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Matchrate__c.field-meta.xml
<CustomField>
    <fullName>Matchrate__c</fullName>
    <description>A matchrate in percentages, denoting how well the result matches the search parameters.</description>
    <inlineHelpText>A matchrate in percentages, denoting how well the result matches the search parameters.</inlineHelpText>
    <label>Matchrate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>Name of a company or organization, if available.</description>
    <inlineHelpText>Name of a company or organization, if available.</inlineHelpText>
    <label>Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Organization_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Match_Status__c</fullName>
    <description>Describes how the organization element matches the available reference data.</description>
    <inlineHelpText>Describes how the organization element matches the available reference data.</inlineHelpText>
    <label>Organization Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/PO_Box_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Box_Match_Status__c</fullName>
    <description>Describes how the PO Box element matches the available reference data.</description>
    <inlineHelpText>Describes how the PO Box element matches the available reference data.</inlineHelpText>
    <label>PO Box Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/PO_Box_Result_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Box_Result_Status__c</fullName>
    <description>Describes how the PO Box element has been modified</description>
    <inlineHelpText>Describes how the PO Box element has been modified</inlineHelpText>
    <label>PO Box Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Result_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/POBox__c.field-meta.xml
<CustomField>
    <fullName>POBox__c</fullName>
    <description>This field will hold pobox address of business</description>
    <label>POBox</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Match_Status__c</fullName>
    <inlineHelpText>Describes how the postcode element matches the available reference data.</inlineHelpText>
    <label>Postcode Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Postcode_Result_Status__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Result_Status__c</fullName>
    <description>Describes how the postcode element has been modified</description>
    <inlineHelpText>Describes how the postcode element has been modified</inlineHelpText>
    <label>Postcode Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Result_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province or state.</description>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Province_Match_Status__c</fullName>
    <inlineHelpText>Describes how the province element matches the available reference data.</inlineHelpText>
    <label>Province Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province_Result_Status__c.field-meta.xml
<CustomField>
    <fullName>Province_Result_Status__c</fullName>
    <description>Describes how the province element has been modified</description>
    <inlineHelpText>Describes how the province element has been modified</inlineHelpText>
    <label>Province Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Result_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street name of the address</description>
    <inlineHelpText>Street name of the address</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Street_Match_Status__c</fullName>
    <description>Describes how the street element matches the available reference data.</description>
    <inlineHelpText>Describes how the street element matches the available reference data.</inlineHelpText>
    <label>Street Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Match_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/modules/internationalAddress/objects/International_Address__c/fields/Street_Result_Status__c.field-meta.xml
<CustomField>
    <fullName>Street_Result_Status__c</fullName>
    <description>Describes how the street element has been modified</description>
    <inlineHelpText>Describes how the street element has been modified</inlineHelpText>
    <label>Street Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>International_Address_Result_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/ISO_3166_Entry__mdt.object-meta.xml
<CustomObject>
    <description>3 letter and 3 digit country codes according to ISO 3166</description>
    <label>ISO 3166 Entry</label>
    <pluralLabel>ISO 3166 Entries</pluralLabel>
</CustomObject>

force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <description>The 2 letter country code according to ISO 3166</description>
    <inlineHelpText>The 2 letter country code according to ISO 3166</inlineHelpText>
    <label>Alpha 2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/modules/internationalAddress/globalValueSets/International_Address_Match_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Empty</fullName>
    </customValue>
    <customValue>
        <fullName>Not found</fullName>
    </customValue>
    <customValue>
        <fullName>Not checked (no reference data or no chance of success)</fullName>
    </customValue>
    <customValue>
        <fullName>Matched with errors</fullName>
    </customValue>
    <customValue>
        <fullName>Matched without errors</fullName>
    </customValue>
    <description>Describes how individual address element match against the available reference data</description>
    <masterLabel>International Address Match  Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/International_Address_Result_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Empty</fullName>
    </customValue>
    <customValue>
        <fullName>Not checked</fullName>
    </customValue>
    <customValue>
        <fullName>Not checked but standardized</fullName>
    </customValue>
    <customValue>
        <fullName>Checked and corrected (changed or inserted)</fullName>
    </customValue>
    <customValue>
        <fullName>Validated, but changed (synonyms, old names)</fullName>
    </customValue>
    <customValue>
        <fullName>Validated, but standardized</fullName>
    </customValue>
    <customValue>
        <fullName>Validated and unchanged</fullName>
    </customValue>
    <customValue>
        <fullName>No value returned, due to multiple possible matches</fullName>
    </customValue>
    <description>Describes how each address element has been modified</description>
    <masterLabel>International Address Result Status</masterLabel>
</GlobalValueSet>

force-app/main/services/InternationalAddress/InternationalAddressImpl.cls
/**
 * Created by appsolutely on 14/02/2020.
 */

public inherited sharing class InternationalAddressImpl implements IInternationalAddressService{

    private inherited sharing class InternationalAddressComparableWrapper implements Comparable {

        public International_Address__c address { get; set; }

        private String organization { get; set; }

        private Integer organizationLevenshteinDistance { get; set; }

        private InternationalAddressComparableWrapper(International_Address__c address, String organization) {
            this.address = address;
            if (organization != null) {
                this.organization = organization;
                this.organizationLevenshteinDistance = address.Organization__c != null ? address.Organization__c.getLevenshteinDistance(organization) : null; // optimization so we don't need to do this for every compareTo call
            }
        }

        public Integer compareTo(Object param1) {
            International_Address__c addressToCompare = ((InternationalAddressComparableWrapper)param1).address;
            Integer returnValue = 0;
            if (this.organization != null && this.organizationLevenshteinDistance != null && addressToCompare.Organization__c != null) {
                Integer addressToCompareOrganizationLevenshteinDistance = addressToCompare.Organization__c.getLevenshteinDistance(this.organization);
                if (this.organizationLevenshteinDistance < addressToCompareOrganizationLevenshteinDistance) {
                    returnValue = -1;
                } else {
                    if (this.organizationLevenshteinDistance > addressToCompareOrganizationLevenshteinDistance) {
                        returnValue = 1;
                    }
                }
            }
            if (returnValue == 0 && address.Matchrate__c != null && addressToCompare.Matchrate__c != null) {
                if (address.Matchrate__c < addressToCompare.Matchrate__c) {
                    returnValue = -1;
                } else {
                    if (address.Matchrate__c > addressToCompare.Matchrate__c) {
                        returnValue = 1;
                    }
                }
            }
            return returnValue;
        }

    }

    public List<International_Address__c> internationalAddressSearchV2(String organization,String building,String street,String housenr,String pobox,String locality,String postcode,String province,String country,String language,String country_format) {

        // check and complete the input
        if (String.isEmpty(country)) {
            throw new CCInputException(Label.Error_Input_Incorrect);
        }
        if (String.isEmpty(language)) {
            language = 'database';
        }
        if (String.isEmpty(country_format)) {
            country_format = 'en';
        }

        InternationalAddressWSDL.InternationalAddressSearchV2Result userSearchResult = WsInternationalAddress.internationalAddressSearchV2(organization, building, street, housenr, pobox, locality, postcode, province, country, language, country_format);

        List<International_Address__c> resultArray = new List<International_Address__c>();
        if (userSearchResult != null && userSearchResult.result != null && userSearchResult.result.item != null) {
            for (InternationalAddressWSDL.InternationalV2 resultItem : userSearchResult.result.item) {
                resultArray.add(mapInternationalV2ToInternationalAddress(resultItem, country));
            }
        }

        // sort the results on how well the organization matches and then on the matchrate. If there is no organization, just sorts on matchrate
        List<InternationalAddressComparableWrapper> wrappedInternationalAddresses = new List<InternationalAddressImpl.InternationalAddressComparableWrapper>();
        for (International_Address__c internationalAddress : resultArray) {
            wrappedInternationalAddresses.add(new InternationalAddressComparableWrapper(internationalAddress, organization));
        }
        wrappedInternationalAddresses.sort();
        // and back to the resultArray
        resultArray = new List<International_Address__c>();
        for (InternationalAddressComparableWrapper internationalAddressComparableWrapper : wrappedInternationalAddresses) {
            resultArray.add(internationalAddressComparableWrapper.address);
        }

        return resultArray;
    }

    private International_Address__c mapInternationalV2ToInternationalAddress(InternationalAddressWsdl.InternationalV2 wsAddress, String searchCountryAlpha3Code) {
        International_Address__c address = new International_Address__c();
        // map the address fields
        if (wsAddress.address != null) {
            address.Matchrate__c = wsAddress.address.matchrate;
            address.Street__c = wsAddress.address.street;
            address.Country__c = wsAddress.address.country;
            if (!String.isEmpty(address.Country__c)) {
                address.Alpha_2_Country_Code__c = ([SELECT Alpha_2_Code__c FROM ISO_3166_Entry__mdt WHERE Label =: searchCountryAlpha3Code LIMIT 1]).Alpha_2_Code__c;
            }
            address.Building__c = wsAddress.address.building;
            address.Contact__c = wsAddress.address.contact;
            address.Country_Specific_Locality__c = wsAddress.address.countryspecific_locality;
            address.Delivery_Address__c = wsAddress.address.delivery_address;
            address.Formatted_Address__c = wsAddress.address.formatted_address;
            address.House_Number__c = wsAddress.address.housenr;
            //address.Language__c = wsAddress.address.
            address.Locality__c = wsAddress.address.locality;
            address.Organization__c = wsAddress.address.organization;
            address.POBox__c = wsAddress.address.pobox;
            address.Postcode__c = wsAddress.address.postcode;
            address.Department__c = wsAddress.address.department;
            address.Province__c = wsAddress.address.province;
        }
        // map the match status
        String elementMatchStatus = wsAddress.element_match_status;
        Map<String, String> matchStatusByFieldName = new Map<String, String>{
                'Postcode_Match_Status__c' => elementMatchStatus.substring(0,1),
                'Locality_Match_Status__c' => elementMatchStatus.substring(1,2),
                'Province_Match_Status__c' => elementMatchStatus.substring(2,3),
                'Street_Match_Status__c' => elementMatchStatus.substring(3,4),
                'Building_Number_Match_Status__c' => elementMatchStatus.substring(4,5),
                'PO_Box_Match_Status__c' => elementMatchStatus.substring(5,6),
                'Building_Match_Status__c' => elementMatchStatus.substring(6,7),
                'Organization_Match_Status__c' => elementMatchStatus.substring(7,8)
        };
        for (String fieldName : matchStatusByFieldName.keySet()) {
            String value = null;
            switch on matchStatusByFieldName.get(fieldName) {
                when '0' {
                    value = 'Empty';
                }
                when '1' {
                    value = 'Not found';
                }
                when '2' {
                    value = 'Not checked (no reference data or no chance of success)';
                }
                when '3' {
                    value = 'Matched with errors';
                }
                when '4' {
                    value = 'Matched without errors';
                }
                when else {
                    ErrorLogUtil.logException(new CCException('Unexpected value ' + matchStatusByFieldName.get(fieldName) + ' while match status for field ' + fieldName));
                }
            }
            address.put(fieldName, value);
        }
        // map the result status
        String elementResultStatus = wsAddress.element_result_status;
        Map<String, String> resultStatusByFieldName = new Map<String, String>{
                'Postcode_Result_Status__c' => elementResultStatus.substring(0,1),
                'Locality_Result_Status__c' => elementResultStatus.substring(1,2),
                'Province_Result_Status__c' => elementResultStatus.substring(2,3),
                'Street_Result_Status__c' => elementResultStatus.substring(3,4),
                'Building_Number_Result_Status__c' => elementResultStatus.substring(4,5),
                'PO_Box_Result_Status__c' => elementResultStatus.substring(5,6),
                'Building_Result_Status__c' => elementResultStatus.substring(6,7),
                'Organization_Result_Status__c' => elementResultStatus.substring(7,8)
        };
        System.debug(JSON.serializePretty(resultStatusByFieldName));
        for (String fieldName : resultStatusByFieldName.keySet()) {
            String value = null;
            switch on resultStatusByFieldName.get(fieldName) {
                when '0' {
                    value = 'Empty';
                }
                when '1' {
                    value = 'Not checked';
                }
                when '2' {
                    value = 'Not checked but standardized';
                }
                when '3' {
                    value = 'Checked and corrected (changed or inserted)';
                }
                when '4' {
                    value = 'Validated, but changed (synonyms, old names)';
                }
                when '5' {
                    value = 'Validated, but standardized';
                }
                when '6' {
                    value = 'Validated and unchanged';
                }
                when '7' {
                    value = 'No value returned, due to multiple possible matches';
                }
                when else {
                    ErrorLogUtil.logException(new CCException('Unexpected value ' + resultStatusByFieldName.get(fieldName) + ' while filling result status for field ' + fieldName));
                }
            }
            address.put(fieldName, value);
        }
        return address;
    }

    /**
     * Deletes the international address with the given id with all related objects
     *
     * @param internationalAddressId
     * @param checkPermissions true if permissions need to be checked
     */
    public void deleteInternationalAddress(Id internationalAddressId, Boolean checkPermissions) {
        if (String.isNotEmpty(internationalAddressId)) {
            List<International_Address__c> internationalAddresses = InternationalAddressSelector.newInstance().selectById(new Set<Id>{internationalAddressId});

            if (internationalAddresses.size() == 1) {
                fflib_ISObjectUnitOfWork unitOfWork = null;
                if (checkPermissions) {
                    unitOfWork = Application.UnitOfWork.newInstance(new DMLWithCRUD());
                } else {
                    unitOfWork = Application.UnitOfWork.newInstance();
                }
                unitOfWork.registerDeleted(internationalAddresses[0]);
                unitOfWork.commitWork();
            }
        }
        else {
            throw new CCInputException(Label.Error_Input_Incorrect);
        }
    }
}