force-app/main/default/objects/International_Address__c/International_Address__c.object-meta.xml
<CustomObject>
    <label>International Address</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>International Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>International Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/International_Address__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Name or contact information of person.</description>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country of the address.</description>
    <inlineHelpText>Country of the address.</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Country_Specific_Locality__c.field-meta.xml
<CustomField>
    <fullName>Country_Specific_Locality__c</fullName>
    <description>Country specific alternative notation for locality</description>
    <inlineHelpText>Country specific alternative notation for locality</inlineHelpText>
    <label>Country Specific Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <description>Local delivery address</description>
    <inlineHelpText>Local delivery address</inlineHelpText>
    <label>Delivery Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Name or description of the department, if available.</description>
    <inlineHelpText>Name or description of the department, if available.</inlineHelpText>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <description>Complete formatted address</description>
    <inlineHelpText>Complete formatted address</inlineHelpText>
    <label>Formatted Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number of the address, if available.</description>
    <inlineHelpText>House number of the address, if available.</inlineHelpText>
    <label>House Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>Name of a company or organization, if available.</description>
    <inlineHelpText>Name of a company or organization, if available.</inlineHelpText>
    <label>Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/POBox__c.field-meta.xml
<CustomField>
    <fullName>POBox__c</fullName>
    <description>This field will hold pobox address of business</description>
    <label>POBox</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province or state.</description>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/RecordRefNo__c.field-meta.xml
<CustomField>
    <fullName>RecordRefNo__c</fullName>
    <description>This field will be used only for unique data reference while displaying the search results on screen.</description>
    <label>RecordRefNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street name of the address</description>
    <inlineHelpText>Street name of the address</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/services/invocable/classes/SearchForInternationalAddressInvocable.cls
/**
 * Created by appsolutely on 18/02/2020.
 */

global inherited sharing class SearchForInternationalAddressInvocable {

    global inherited sharing class SearchInternationalAddressArgument {
        @InvocableVariable(label='Organization' description='Name of the company or organisation at the address')
        global String organization;
        @InvocableVariable(label='Building' description='Building or sub-building name')
        global String building;
        @InvocableVariable(label='POBox' description='PO box search phrase')
        global String pobox;
        @InvocableVariable(label='Province' description='Province search phrase')
        global String province;
        @InvocableVariable(label='Street' description='Street search phrase')
        global String street;
        @InvocableVariable(label='Postal Code' description='Postalcode search phrase')
        global String postal_code;
        @InvocableVariable(label='House Number' description='House number search phrase')
        global String housenr;
        @InvocableVariable(label='Locality' description='District or municipality search phrase')
        global String locality;
        @InvocableVariable(label='Language' description='Language in which the results are returned')
        global String language;
        @InvocableVariable(label='Country' description='Country of the address')
        global String country;

    }

    @InvocableMethod
    global static List<List<International_Address__c>>  searchInternationalAddress(List<SearchInternationalAddressArgument> arguments) {
        try{
            List<List<International_Address__c>> listInternationalAddressesFinal = new List<List<International_Address__c>>();
            List<International_Address__c> listInternationalAddresses = new List<International_Address__c>();
            Integer recordRefNumberCount = 1;
            List<InternationalAddressResultsDto> searchInternationalAddressResultsDtos = new List<InternationalAddressResultsDto>();
            for (SearchInternationalAddressArgument searchInternationalAddressArgument : arguments) {
                searchInternationalAddressResultsDtos.addAll(
                        InternationalAddressService.internationalAddressSearchV2(
                                searchInternationalAddressArgument.organization,
                                searchInternationalAddressArgument.building,
                                searchInternationalAddressArgument.street,
                                searchInternationalAddressArgument.housenr,
                                searchInternationalAddressArgument.pobox,
                                searchInternationalAddressArgument.locality,
                                searchInternationalAddressArgument.postal_code,
                                searchInternationalAddressArgument.province,
                                searchInternationalAddressArgument.country,
                                searchInternationalAddressArgument.language,
                                InternationalAddressController.countries.get(searchInternationalAddressArgument.country)
                        )
                );
            }

            for (InternationalAddressResultsDto searchInternationalAddressResultDto : searchInternationalAddressResultsDtos) {
                listInternationalAddresses.add(assignInternationalAddress(searchInternationalAddressResultDto, 'IA00'+recordRefNumberCount));
                recordRefNumberCount = recordRefNumberCount + 1;
            }

            listInternationalAddressesFinal.add(listInternationalAddresses);
            return listInternationalAddressesFinal;
        } catch (Exception e) {
            ErrorLogUtil.logException(e);
        }
        return null;
    }

    private static International_Address__c assignInternationalAddress(InternationalAddressResultsDto searchInternationalAddressResultsDto, String recordRefNumber) {
        International_Address__c interAddress = new International_Address__c();
        interAddress.Organization__c = searchInternationalAddressResultsDto.organization;
        interAddress.Building__c = searchInternationalAddressResultsDto.building;
        interAddress.Street__c = searchInternationalAddressResultsDto.street;
        interAddress.House_Number__c = searchInternationalAddressResultsDto.housenr;
        interAddress.Locality__c = searchInternationalAddressResultsDto.locality;
        interAddress.POBox__c = searchInternationalAddressResultsDto.pobox;
        interAddress.Postcode__c =  searchInternationalAddressResultsDto.postcode;
        interAddress.Country__c = searchInternationalAddressResultsDto.country;
        interAddress.Province__c = searchInternationalAddressResultsDto.province;
        interAddress.Contact__c = searchInternationalAddressResultsDto.contact;
        interAddress.Country_Specific_Locality__c = searchInternationalAddressResultsDto.countryspecific_locality;
        interAddress.Delivery_Address__c = searchInternationalAddressResultsDto.delivery_address;
        interAddress.Department__c = searchInternationalAddressResultsDto.department;
        interAddress.Formatted_Address__c = searchInternationalAddressResultsDto.formatted_address;
        // interAddress.RecordRefNo__c = recordRefNumber;
        return interAddress;
    }

}