force-app/main/default/objects/International_Address__c/International_Address__c.object-meta.xml
<CustomObject>
    <label>International Address</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>International Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>International Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/International_Address__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Name or contact information of person.</description>
    <label>Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country of the address.</description>
    <inlineHelpText>Country of the address.</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Country_Specific_Locality__c.field-meta.xml
<CustomField>
    <fullName>Country_Specific_Locality__c</fullName>
    <description>Country specific alternative notation for locality</description>
    <inlineHelpText>Country specific alternative notation for locality</inlineHelpText>
    <label>Country Specific Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <description>Local delivery address</description>
    <inlineHelpText>Local delivery address</inlineHelpText>
    <label>Delivery Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Name or description of the department, if available.</description>
    <inlineHelpText>Name or description of the department, if available.</inlineHelpText>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <description>Complete formatted address</description>
    <inlineHelpText>Complete formatted address</inlineHelpText>
    <label>Formatted Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>House number of the address, if available.</description>
    <inlineHelpText>House number of the address, if available.</inlineHelpText>
    <label>House Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <label>Locality</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Matchrate__c.field-meta.xml
<CustomField>
    <fullName>Matchrate__c</fullName>
    <description>A matchrate in percentages, denoting how well the result matches the search parameters.</description>
    <inlineHelpText>A matchrate in percentages, denoting how well the result matches the search parameters.</inlineHelpText>
    <label>Matchrate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>Name of a company or organization, if available.</description>
    <inlineHelpText>Name of a company or organization, if available.</inlineHelpText>
    <label>Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/POBox__c.field-meta.xml
<CustomField>
    <fullName>POBox__c</fullName>
    <description>This field will hold pobox address of business</description>
    <label>POBox</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/International_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province or state.</description>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/address/objects/International_Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street name of the address</description>
    <inlineHelpText>Street name of the address</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/services/InternationalAddress/InternationalAddressImplTest.cls
/**
 * Created by jaapbranderhorst on 14/03/2020.
 */

@IsTest
private class InternationalAddressImplTest {
    @IsTest
    static void testHappyFlow() {
        // given a webservice returning two InternationalV2 objects
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IWsInternationalAddress wsInternationalAddress = (IWsInternationalAddress)mocks.mock(IWsInternationalAddress.class);

        mocks.startStubbing();
        InternationalAddressWsdl.InternationalAddressSearchV2Result searchV2Result = new InternationalAddressWsdl.InternationalAddressSearchV2Result();

        InternationalAddressWsdl.InternationalV2 internationalV2_1 = createInternationalV2(1);
        InternationalAddressWsdl.InternationalV2 internationalV2_2 = createInternationalV2(2);

        searchV2Result.result = new InternationalAddressWsdl.InternationalV2Array();
        searchV2Result.result.item = new List<InternationalAddressWsdl.InternationalV2>{internationalV2_1, internationalV2_2};
        mocks.when(wsInternationalAddress.internationalAddressSearchV2('org2',
                'building',
                'street',
                'housenr',
                'pobox',
                'locality',
                'postal_code',
                'province',
                'NLD',
                'database',
                'en')).thenReturn(searchV2Result);
        mocks.stopStubbing();

        Application.Service.setMock(IWsInternationalAddress.class, wsInternationalAddress);

        // when
        Test.startTest();
        List<International_Address__c> internationalAddresses = InternationalAddressService.internationalAddressSearchV2('org2',
                'building',
                'street',
                'housenr',
                'pobox',
                'locality',
                'postal_code',
                'province',
                'NLD',
                null,
                null);
        Test.stopTest();

        // then
        System.assertEquals(2, internationalAddresses.size());
        for (Integer i = internationalAddresses.size(); i == 1; i--) {
            International_Address__c addressToTest = internationalAddresses.get(i-1);
            System.assertEquals('province' + i, addressToTest.Province__c);
            System.assertEquals('street' + i, addressToTest.Street__c);
            System.assertEquals('housenr' + i, addressToTest.House_Number__c);
            System.assertEquals('pobox' + i, addressToTest.POBox__c);
            System.assertEquals('postcode' + i, addressToTest.Postcode__c);
            System.assertEquals('locality' + i, addressToTest.Locality__c);
            System.assertEquals('country' + i, addressToTest.Country__c);
            System.assertEquals('countryspecific_locality' + i, addressToTest.Country_Specific_Locality__c);
            System.assertEquals('org' + i, addressToTest.Organization__c);
            System.assertEquals('department' + i, addressToTest.Department__c);
            System.assertEquals('formatted_address' + i, addressToTest.Formatted_Address__c);
            System.assertEquals('delivery_address' + i, addressToTest.Delivery_Address__c);
            System.assertEquals('building' + i, addressToTest.Building__c);
            System.assertEquals('contact' + i, addressToTest.Contact__c);
            System.assertEquals(100.0, addressToTest.Matchrate__c);
        }


    }

    @IsTest
    public static void testDeleteInternationalAddressHappyFlow() {
        International_Address__c internationalAddress = new International_Address__c(Country__c = 'test');
        insert internationalAddress;

        Test.startTest();
        InternationalAddressService.deleteInternationalAddress(internationalAddress.Id, false);
        Test.stopTest();

        System.assert([SELECT Id FROM International_Address__c].size() == 0);

    }

    @IsTest
    public static void testDeleteInternationalAddressErrorFlow() {
        Exception ex;
        Test.startTest();
        try {
            InternationalAddressService.deleteInternationalAddress(null, false);
        }catch (Exception e) {
            ex = e;
        }
        Test.stopTest();

        System.assert([SELECT Id FROM International_Address__c].size() == 0);
        System.assert(ex != null);
        System.assert(ex.getMessage() == 'Incorrect input. Please correct your input and try again.');

    }

    @IsTest
    public static void testDuplicateAddressFlow() {

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IWsInternationalAddress wsInternationalAddress = (IWsInternationalAddress)mocks.mock(IWsInternationalAddress.class);

        mocks.startStubbing();
        InternationalAddressWsdl.InternationalAddressSearchV2Result searchV2Result = new InternationalAddressWsdl.InternationalAddressSearchV2Result();

        InternationalAddressWsdl.InternationalV2 internationalV2_1 = createInternationalV2(1);
        InternationalAddressWsdl.InternationalV2 internationalV2_2 = createInternationalV2(1);

        searchV2Result.result = new InternationalAddressWsdl.InternationalV2Array();
        searchV2Result.result.item = new List<InternationalAddressWsdl.InternationalV2>{internationalV2_1, internationalV2_2};
        mocks.when(wsInternationalAddress.internationalAddressSearchV2('org2',
                'building',
                'street',
                'housenr',
                'pobox',
                'locality',
                'postal_code',
                'province',
                'NLD',
                'database',
                'en')).thenReturn(searchV2Result);
        mocks.stopStubbing();

        //Make sure the mocked response is size = 2
        System.assertEquals(2, searchV2Result.result.item.size());


        Application.Service.setMock(IWsInternationalAddress.class, wsInternationalAddress);

        // when
        Test.startTest();
        List<International_Address__c> internationalAddresses = InternationalAddressService.internationalAddressSearchV2('org2',
                'building',
                'street',
                'housenr',
                'pobox',
                'locality',
                'postal_code',
                'province',
                'NLD',
                null,
                null);
        Test.stopTest();

        // then
        // Mocked response size = 2, but filtered to only show 1
        System.assertEquals(1, internationalAddresses.size());
    }
    private static InternationalAddressWsdl.InternationalV2 createInternationalV2(Integer i){
        InternationalAddressWsdl.InternationalV2 internationalV2_2 = new InternationalAddressWsdl.InternationalV2();
        InternationalAddressWsdl.InternationalFormattedAddress address2 = createInternationalAddress(i);
        internationalV2_2.address = address2;
        internationalV2_2.element_match_status = '01230123';
        internationalV2_2.element_result_status = '01234567';
        return internationalV2_2;
    }
    private static InternationalAddressWsdl.InternationalFormattedAddress createInternationalAddress(Integer i){
        InternationalAddressWsdl.InternationalFormattedAddress address1 = new InternationalAddressWsdl.InternationalFormattedAddress();
        address1.matchrate = 100.0;
        address1.province = 'province' + String.valueOf(i);
        address1.department = 'department' + String.valueOf(i);
        address1.postcode = 'postcode1' + String.valueOf(i);
        address1.pobox = 'pobox' + String.valueOf(i);
        address1.street = 'street' + String.valueOf(i);
        address1.organization = 'org' + String.valueOf(i);
        address1.locality = 'locality' + String.valueOf(i);
        address1.housenr = 'housenr' + String.valueOf(i);
        address1.formatted_address = 'formatted_address' + String.valueOf(i);
        address1.delivery_address = 'delivery_address' + String.valueOf(i);
        address1.countryspecific_locality = 'countryspecific_locality' + String.valueOf(i);
        address1.contact = 'contact' + String.valueOf(i);
        address1.building = 'building' + String.valueOf(i);
        address1.country = 'country' + String.valueOf(i);
        return address1;
    }
}