force-app/main/licensetypes/objects/License_Type_Definition__mdt/License_Type_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Contains all information with regards to License Types. Integrates the different parts of the solution.</description>
    <label>License Type Definition</label>
    <pluralLabel>License Type Definitions</pluralLabel>
</CustomObject>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Licence_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Licence_Type_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The name of the license type as returned by LicenseType.name()</description>
    <inlineHelpText>The name of the license type as returned by LicenseType.name()</inlineHelpText>
    <label>Licence Type Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Nr_Of_Seats_Feature_Param_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Nr_Of_Seats_Feature_Param_API_Name__c</fullName>
    <description>The API Name of the Feature parameter containing the nr of seats provisioned for the License Type</description>
    <inlineHelpText>The API Name of the Feature parameter containing the nr of seats provisioned for the License Type</inlineHelpText>
    <label>Nr Of Seats Feature Param API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which the license types should be shown in the Company.info setup. -1 means don&#39;t show.</description>
    <inlineHelpText>The order in which the license types should be shown in the Company.info setup. -1 means don&#39;t show.</inlineHelpText>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Permission_Set_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_API_Name__c</fullName>
    <description>The API Name of the permission set that contains the permissions for the given license type.</description>
    <inlineHelpText>The API Name of the permission set that contains the permissions for the given license type.</inlineHelpText>
    <label>Permission Set API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the license type as shown on the License Management Card for the License Type.</description>
    <inlineHelpText>The title of the license type as shown on the License Management Card for the License Type.</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/modules/setup/LicenseManagementTabController.cls
/**
 * Created by jaapbranderhorst on 17/05/2020.
 */

public inherited sharing class LicenseManagementTabController {

    @AuraEnabled(Cacheable=true)
    public static String[] getLicenseTypes() {
        List<License_Type_Definition__mdt> licenseTypeDefinitions = new List<License_Type_Definition__mdt>();
        licenseTypeDefinitions = [
                SELECT
                        Licence_Type_Name__c,
                        Nr_Of_Seats_Feature_Param_API_Name__c,
                        Permission_Set_API_Name__c,
                        Title__c,
                        DeveloperName,
                        Id,
                        Label,
                        Language,
                        MasterLabel,
                        NamespacePrefix,
                        QualifiedApiName,
                        Order__c
                FROM License_Type_Definition__mdt WHERE Order__c > 0 ORDER BY Order__c ASC];
        List<String> returnValues = new List<String>();
        System.debug('license type definitions: ' + licenseTypeDefinitions);
        for (License_Type_Definition__mdt licenseTypeDefinition : licenseTypeDefinitions) {
            returnValues.add(licenseTypeDefinition.Licence_Type_Name__c);
        }
        return returnValues;
    }

}