force-app/main/licensetypes/objects/License_Type_Definition__mdt/License_Type_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Contains all information with regards to License Types. Integrates the different parts of the solution.</description>
    <label>License Type Definition</label>
    <pluralLabel>License Type Definitions</pluralLabel>
</CustomObject>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Licence_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Licence_Type_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The name of the license type as returned by LicenseType.name()</description>
    <inlineHelpText>The name of the license type as returned by LicenseType.name()</inlineHelpText>
    <label>Licence Type Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/licensetypes/objects/License_Type_Definition__mdt/fields/Permission_Set_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_API_Name__c</fullName>
    <description>The API Name of the permission set that contains the permissions for the given license type.</description>
    <inlineHelpText>The API Name of the permission set that contains the permissions for the given license type.</inlineHelpText>
    <label>Permission Set API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/selectors/PermissionSetSelector/PermissionSetSelector.cls
/**
 * Created by jaapbranderhorst on 26/05/2020.
 */

public with sharing class PermissionSetSelector extends fflib_SObjectSelector implements IPermissionSetSelector{

    @TestVisible
    private static Map<LicenseType, PermissionSet> permissionSetByLicenseTypes {
        get {
            if (permissionSetByLicenseTypes == null) {
                permissionSetByLicenseTypes = new Map<LicenseType, PermissionSet>();
                Map<String, LicenseType> licenseTypesByName = new Map<String, LicenseType>();
                for (LicenseType licenseType : LicenseType.values()) {
                    licenseTypesByName.put(licenseType.name(), licenseType);
                }
                System.debug('license type names: ' + JSON.serializePretty(licenseTypesByName));
                License_Type_Definition__mdt[] licenseTypeDefinitions = [SELECT Permission_Set_API_Name__c, DeveloperName, Licence_Type_Name__c FROM License_Type_Definition__mdt];
                Set<String> permissionSetApiNames = new Set<String>();
                Map<String, LicenseType> licenseTypesByPermissionSetApiName = new Map<String, LicenseType>();
                for (License_Type_Definition__mdt licenseTypeDefinition : licenseTypeDefinitions) {
                    permissionSetApiNames.add(licenseTypeDefinition.Permission_Set_API_Name__c);
                    licenseTypesByPermissionSetApiName.put(licenseTypeDefinition.Permission_Set_API_Name__c, licenseTypesByName.get(licenseTypeDefinition.Licence_Type_Name__c));
                }
                System.debug('permission set names: ' + JSON.serializePretty(permissionSetApiNames));
                PermissionSet[] permissionSets = [SELECT Name, Id, Label, NamespacePrefix FROM PermissionSet WHERE Name IN : permissionSetApiNames];
                System.debug('permission sets: ' + JSON.serializePretty(permissionSets));

                for (PermissionSet permissionSet : permissionSets) {
                    LicenseType licenseType = licenseTypesByName.get(permissionSet.Name.toUpperCase());
                    permissionSetByLicenseTypes.put(licenseType, permissionSet);
                }
            }
            return permissionSetByLicenseTypes;
        }
        set;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                PermissionSet.Id,
                PermissionSet.Name,
                PermissionSet.Label,
                PermissionSet.NamespacePrefix
        };
    }

    public SObjectType getSObjectType() {
        return PermissionSet.SObjectType;
    }

    public static IPermissionSetSelector newInstance() {
        SObjectType op = PermissionSet.SObjectType;
        return (IPermissionSetSelector)Application.Selector.newInstance(PermissionSet.SObjectType);
    }

    public PermissionSet selectByLicenseType(LicenseType licenseType) {
        return permissionSetByLicenseTypes.get(licenseType);
    }

    public PermissionSet[] selectLicenseTypePermissionSetsExcludingLicenseType(LicenseType licenseTp) {
        Set<LicenseType> otherLicenseTypes = new Set<LicenseType>(LicenseType.values());
        otherLicenseTypes.remove(licenseTp);
        PermissionSet[] returnValue = new List<PermissionSet>();
        for (LicenseType licenseType2 : otherLicenseTypes) {
            if (permissionSetByLicenseTypes.get(licenseType2) != null) // test license type values don't have permission sets related to them and will return null therefore
                returnValue.add(permissionSetByLicenseTypes.get(licenseType2));
        }
        System.debug('permission sets with exclusion: ' + JSON.serializePretty(returnValue));
        return returnValue;
    }


}