force-app/main/default/objects/Account/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business data fetched from Company.info</description>
    <inlineHelpText>The business data fetched from Company.info</inlineHelpText>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Dutch Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Dossiers</relationshipLabel>
    <relationshipName>Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/selectors/main/classes/BusinessDossierSelectorTest.cls
/****************************************************************************************
Author          : ValerijsProkudins
******************************************************************************************/
@isTest
public with sharing class BusinessDossierSelectorTest {

    
    @isTest
    static void testGetInstance() {
        Object o = BusinessDossierSelector.newInstance();
        System.assert(o instanceof BusinessDossierSelector);
    }
    @isTest
    static void testGetSObjectFields() {
        BusinessDossierSelector selector = (BusinessDossierSelector) BusinessDossierSelector.newInstance();
        Test.startTest();
        System.runAs(TestUtils.getCompanyConnectUser()) { //didnt work. need to check with jaap how testutils work
            List<Schema.SObjectField> fields = selector.getSObjectFieldList();
            Set<Schema.SObjectField> fieldsAsSet = new Set<Schema.SObjectField>(fields);
            System.assert(fieldsAsSet.containsAll(new List<Schema.SObjectField>{
                Business_Dossier__c.Id,
                Business_Dossier__c.Name,
                Business_Dossier__c.Account__c,
                Business_Dossier__c.Account__r.Id,
                Business_Dossier__c.Account__r.name
            }));
        }
        Test.stopTest();
        

    }

    @isTest
    static void testGetSObjectType() {
        BusinessDossierSelector selector = (BusinessDossierSelector) BusinessDossierSelector.newInstance();
        Test.startTest();
        System.runAs(TestUtils.getCompanyConnectUser()) {//didnt work. need to check with jaap how testutils work
            Schema.SObjectType tpe = selector.getSObjectType();
            System.assertEquals(Business_Dossier__c.sObjectType, tpe);
        }
        Test.stopTest();

    }
   

    @isTest
    static void testSelectByDossierNumber() {
        List<Business_Dossier__c> dossiers = new List<Business_Dossier__c>();
        Set<String> dossierNumSet = new set<String>();
        for (Integer i2 = 0; i2 < 10 ; i2++) {
            dossiers.add(new Business_Dossier__c(Name = 'test'+i2, Dossier_Number__c=string.valueOf(i2)));
            dossierNumSet.add(string.valueOf(i2));
        }
        insert dossiers;
        

        

        Test.startTest();
        System.runAs(TestUtils.getCompanyConnectUser()) {//didnt work. need to check with jaap how testutils work
            IBusinessDossierSelector selector = BusinessDossierSelector.newInstance();
            List<Business_Dossier__c> dossiersReturned = selector.selectByDossierNumber(dossierNumSet);
            System.assertEquals(10, dossiersReturned.size());
        }
        Test.stopTest();


    }






}