force-app/main/default/objects/Account/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business data fetched from Company.info</description>
    <inlineHelpText>The business data fetched from Company.info</inlineHelpText>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/Business_Data_SBI__c.object-meta.xml
<CustomObject>
    <description>A DutchBusiness Company SBI Collection.</description>
    <label>SBI Code</label>
    <nameField>
        <displayFormat>SBI-{000000}</displayFormat>
        <label>SBI Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SBI Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <label>Business Dossier</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipName>SBIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/services/DutchBusiness/UpsertBusinessDossierInvocableTest.cls
/**
 * Created by hugovankrimpen on 08/07/2020.
 */

@IsTest
public with sharing class UpsertBusinessDossierInvocableTest {

    @IsTest
    static void testCreateDutchDossierInvocableHappyFlow() {


        //Instantiate sObject
        string dossierNumber = '1234';
        string establishmentNumber = '5678';
        InstantiateBusinessDossierInvocableTest.initiateMockResponse(dossierNumber, establishmentNumber);

        InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument argument = new InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument();
        argument.dossierNumber = dossierNumber;
        argument.establishmentNumber = establishmentNumber;

        //This function is tested in "InstantiateBusinessDossierInvocableTest
        Business_Dossier__c businessDossier =
                InstantiateBusinessDossierInvocable.instantiateBusinessDossier(
                        new List<InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument>{argument}
                )[0];

        //Instantiate Account
        Account a = new Account();
        a.Name = 'abc';

        //Build the argument for the invocable.
        UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument upsertArgument = new UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument();
        upsertArgument.businessDossier = businessDossier;
        upsertArgument.relatedAccount = a;
        List<UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument> arguments = new List<UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument>{upsertArgument};



        Test.startTest();
        List<Business_Dossier__c> dossiers = UpsertBusinessDossierInvocable.upsertAccountWithBusinessDossier(arguments);
        Test.stopTest();


        List<Business_Dossier__c> insertedDossiers = [SELECT id, (SELECT Id FROM SBIs__r) FROM Business_Dossier__c];
        System.assertNotEquals(null,insertedDossiers);
        System.assertEquals(1, insertedDossiers.size());
        System.assertEquals(10, insertedDossiers[0].SBIs__r.size());
    }
    @IsTest
    static void testCreateDutchDossierInvocableErrorFlow() {
        //Build the argument for the invocable.
        UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument upsertArgument = new UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument();
        upsertArgument.businessDossier = null;
        upsertArgument.relatedAccount = null;
        List<UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument> arguments = new List<UpsertBusinessDossierInvocable.UpsertBusinessDossierArgument>{upsertArgument};

        Test.startTest();
        try {
            List<Business_Dossier__c> dossiers = UpsertBusinessDossierInvocable.upsertAccountWithBusinessDossier(arguments);
            System.assert(false);
        }catch (Exception e){
            System.assert(true);
        }
        Test.stopTest();
    }
}