force-app/main/default/objects/Account/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business data fetched from Company.info</description>
    <inlineHelpText>The business data fetched from Company.info</inlineHelpText>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Dutch Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Dossiers</relationshipLabel>
    <relationshipName>Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Indication_Main_Establishment__c.field-meta.xml
<CustomField>
    <fullName>Indication_Main_Establishment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if this is the main establishment of the business.</description>
    <label>Main Establishment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Is_Removed__c.field-meta.xml
<CustomField>
    <fullName>Is_Removed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True, if removed from Company.info server</description>
    <label>Is Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/CompanyConnectUserId__c.field-meta.xml
<CustomField>
    <fullName>CompanyConnectUserId__c</fullName>
    <label>CompanyConnectUserId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/CompanyInfo_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>CompanyInfo_Account_Id__c</fullName>
    <description>The account id of the account of the company info DATA user. For resell customers that is the appsolutely account id.</description>
    <label>CompanyInfo Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Last_Executed_Batch__c.field-meta.xml
<CustomField>
    <fullName>Last_Executed_Batch__c</fullName>
    <description>The time when &quot;UpdateDossiersBatch&quot; is executed</description>
    <label>Last Executed Batch</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateDossiersBatchTest.cls
/**
 * Created by tejaswinidandi on 2019-08-01.
 */

@IsTest
public class UpdateDossiersBatchTest {

    @TestSetup
    private static void setupData() {
        Credentials__c c = new Credentials__c();
        c.Username__c = 'test';
        c.Password__c = 'pas';
        c.CompanyInfo_Account_Id__c = '1';
        c.CompanyConnectUserId__c = 11;
        c.Last_Executed_Batch__c = Datetime.newInstance(2019, 7, 28);

        Business_Dossier__c d = new Business_Dossier__c();
        d.Dossier_Number__c = '1';
        d.Establishment_Number__c = '2';
        d.Indication_Main_Establishment__c = false;
        d.Name = 't1';

        Business_Dossier__c d1 = new Business_Dossier__c();
        d1.Dossier_Number__c = '11';
        d1.Establishment_Number__c = '12';
        d1.Name = 't11';

        Account a1 = new Account();
        a1.Name = 'aa';
        Account a2 = new Account();
        a2.Name = 'aa2';

        insert a1;
        insert a2;
        insert c;
        d.Account__c = a1.Id;
        d1.Account__c = a2.Id;
        insert d;
        insert d1;
    }


    @IsTest
    static void testBatch() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness mockWS = (IWsDutchBusiness)mocks.mock(IWsDutchBusiness.class);
        Integer pageNR = 1;

        mocks.startStubbing();

        DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult output = new DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult();
        output.paging = new DutchBusinessWsdl.ResultInfo();
        output.paging.numpages = 1;
        output.results = new DutchBusinessWsdl.DutchBusinessUpdateReferenceArray();
        output.results.item = new List<DutchBusinessWsdl.DutchBusinessUpdateReference>();
        DutchBusinessWsdl.DutchBusinessUpdateReference a1 =  new DutchBusinessWsdl.DutchBusinessUpdateReference();
        a1.dossier_number = '1';
        a1.establishment_number = '2';
        a1.update_types = stringArray(new List<String>{'ChamberNo', 'Legalform', 'Name', 'EstablishmentAddress', 'CorrespondenceAddress'});
        output.results.item.add(a1);

        DutchBusinessWsdl.DutchBusinessUpdateReference a2 =  new DutchBusinessWsdl.DutchBusinessUpdateReference();
        a2.dossier_number = '11';
        a2.establishment_number = '12';
        a2.update_types = stringArray(new List<String>{'Removed'});
        output.results.item.add(a2);
        Credentials__c c = Credentials__c.getOrgDefaults();

        DutchBusinessWsdl.DutchBusinessDossierV3 output1 = new DutchBusinessWsdl.DutchBusinessDossierV3();

        mocks.when(mockWS.dutchBusinessUpdateGetChangedDossiers(fflib_Match.anyDate(), (DutchBusinessWsdl.stringArray) fflib_Match.anyObject(), fflib_Match.anyInteger())).thenReturn(output);
        mocks.when(mockWS.dutchBusinessGetDossierV3(a1.dossier_number, a1.establishment_number)).thenReturn(output1);

        mocks.stopStubbing();
        Application.Service.setMock(IWsDutchBusiness.class, mockWS);

        test.startTest();
        UpdateDossiersBatch o = new UpdateDossiersBatch();
        Database.executeBatch(o);
        test.stopTest();

        List<Business_Dossier__c> bd = [SELECT Id, Is_Removed__c, Dossier_Number__c FROM Business_Dossier__c WHERE Dossier_Number__c = '11' LIMIT 1];
        System.assertEquals(bd[0].Is_Removed__c, true);
        Credentials__c cs = Credentials__c.getOrgDefaults();
        Date d = cs.Last_Executed_Batch__c.Date();
        System.assertEquals(d, Datetime.now().Date());
    }

    @IsTest
    static void testBatchWithMorePages() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness mockWS = (IWsDutchBusiness)mocks.mock(IWsDutchBusiness.class);
        Integer pageNR = 1;

        mocks.startStubbing();

        DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult output = new DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult();
        output.paging = new DutchBusinessWsdl.ResultInfo();
        output.paging.numpages = 5;
        output.results = new DutchBusinessWsdl.DutchBusinessUpdateReferenceArray();
        output.results.item = new List<DutchBusinessWsdl.DutchBusinessUpdateReference>();
        DutchBusinessWsdl.DutchBusinessUpdateReference a1 =  new DutchBusinessWsdl.DutchBusinessUpdateReference();
        a1.dossier_number = '1';
        a1.establishment_number = '2';
        a1.update_types = stringArray(new List<String>{'ChamberNo', 'Legalform', 'Name', 'EstablishmentAddress', 'CorrespondenceAddress'});
        output.results.item.add(a1);

        DutchBusinessWsdl.DutchBusinessUpdateReference a2 =  new DutchBusinessWsdl.DutchBusinessUpdateReference();
        a2.dossier_number = '11';
        a2.establishment_number = '12';
        a2.update_types = stringArray(new List<String>{'Removed'});
        output.results.item.add(a2);
        Credentials__c c = Credentials__c.getOrgDefaults();

        DutchBusinessWsdl.DutchBusinessDossierV3 output1 = new DutchBusinessWsdl.DutchBusinessDossierV3();

        mocks.when(mockWS.dutchBusinessUpdateGetChangedDossiers(fflib_Match.anyDate(), (DutchBusinessWsdl.stringArray) fflib_Match.anyObject(), fflib_Match.anyInteger())).thenReturn(output);
        mocks.when(mockWS.dutchBusinessGetDossierV3(a1.dossier_number, a1.establishment_number)).thenReturn(output1);

        mocks.stopStubbing();
        Application.Service.setMock(IWsDutchBusiness.class, mockWS);

        test.startTest();
        UpdateDossiersBatch o = new UpdateDossiersBatch();
        Database.executeBatch(o);
        test.stopTest();

        List<Business_Dossier__c> bd = [SELECT Id, Is_Removed__c, Dossier_Number__c FROM Business_Dossier__c WHERE Dossier_Number__c = '11' LIMIT 1];
        System.assertEquals(bd[0].Is_Removed__c, true);
    }

    @IsTest
    static void testBatchWithNoUpdates() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness mockWS = (IWsDutchBusiness)mocks.mock(IWsDutchBusiness.class);
        Integer pageNR = 1;

        mocks.startStubbing();

        DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult output = new DutchBusinessWsdl.DutchBusinessUpdateReferencePagedResult();
        output.paging = new DutchBusinessWsdl.ResultInfo();
        output.paging.numpages = 1;
        output.results = new DutchBusinessWsdl.DutchBusinessUpdateReferenceArray();
        output.results.item = new List<DutchBusinessWsdl.DutchBusinessUpdateReference>();

        Credentials__c c = Credentials__c.getOrgDefaults();

        DutchBusinessWsdl.DutchBusinessDossierV3 output1 = new DutchBusinessWsdl.DutchBusinessDossierV3();

        mocks.when(mockWS.dutchBusinessUpdateGetChangedDossiers(fflib_Match.anyDate(), (DutchBusinessWsdl.stringArray) fflib_Match.anyObject(), fflib_Match.anyInteger())).thenReturn(output);
        mocks.when(mockWS.dutchBusinessGetDossierV3('', '')).thenReturn(output1);

        mocks.stopStubbing();
        Application.Service.setMock(IWsDutchBusiness.class, mockWS);

        test.startTest();
        UpdateDossiersBatch o = new UpdateDossiersBatch();
        Database.executeBatch(o);
        test.stopTest();

        List<Business_Dossier__c> bd = [SELECT Id, Is_Removed__c, Dossier_Number__c FROM Business_Dossier__c WHERE Dossier_Number__c = '11' LIMIT 1];
        System.assertEquals(bd[0].Is_Removed__c, false);
        Credentials__c cs = Credentials__c.getOrgDefaults();
        Date d = cs.Last_Executed_Batch__c.Date();
        System.assertEquals(d, Datetime.now().Date());
    }

    public static DutchBusinessWsdl.stringArray stringArray (List<String> types) {
        DutchBusinessWsdl.stringArray updateTypesArrayResponse = new DutchBusinessWsdl.stringArray();
        updateTypesArrayResponse.item = new List<String>();
        for (String s : types) {
            updateTypesArrayResponse.item.add(s);
        }

        return updateTypesArrayResponse;
    }
}