force-app/main/default/objects/Account/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business data fetched from Company.info</description>
    <inlineHelpText>The business data fetched from Company.info</inlineHelpText>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/Business_Data_SBI__c.object-meta.xml
<CustomObject>
    <description>A DutchBusiness Company SBI Collection.</description>
    <label>SBI Code</label>
    <nameField>
        <displayFormat>SBI-{000000}</displayFormat>
        <label>SBI Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SBI Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <label>Business Dossier</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipName>SBIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Data_SBI__c/fields/SBI_Code__c.field-meta.xml
<CustomField>
    <fullName>SBI_Code__c</fullName>
    <description>A SBI(‘Standaard Bedrijfs Indeling’) code, a number up to six characters in length.</description>
    <label>SBI Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/SBI_Description__c.field-meta.xml
<CustomField>
    <fullName>SBI_Description__c</fullName>
    <description>Description of the SBI code.</description>
    <label>SBI Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/SBI_Type__c.field-meta.xml
<CustomField>
    <fullName>SBI_Type__c</fullName>
    <description>SBI collection type</description>
    <label>SBI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>original</fullName>
            </value>
            <value>
                <fullName>company_info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Dossiers</relationshipLabel>
    <relationshipName>Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/selectors/main/classes/SbiCodeSelectorTest.cls
/**
 * Created by jaapbranderhorst on 2019-06-22.
 */

@IsTest
private class SbiCodeSelectorTest {

    @TestSetup
    static void setup() {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < 10; i++) {
            accounts.add(new Account(Name = '' + i));
        }
        insert accounts;
        List<Business_Dossier__c> dossiers = new List<Business_Dossier__c>();
        for (Integer i = 0; i < 10; i++) {
            dossiers.add(new Business_Dossier__c(Account__c = accounts.get(i).Id));
        }
        insert dossiers;
        List<Business_Data_SBI__c> sbiCodes = new List<Business_Data_SBI__c>();
        for (Business_Dossier__c businessDossier : dossiers) {
            for (Integer i = 0; i < 5; i++) {
                sbiCodes.add(new Business_Data_SBI__c(
                        Business_Dossier__c = businessDossier.Id,
                        SBI_Code__c = '' + i,
                        SBI_Description__c = '' + i,
                        SBI_Type__c = 'original')
                );
            }
        }
        insert sbiCodes;
    }

    @IsTest
    static void testSelectByDossierId() {
        Map<Id, Business_Dossier__c> dossiersByIds = new Map<Id, Business_Dossier__c>([SELECT Id FROM Business_Dossier__c]);
        Test.startTest();
        List<Business_Data_SBI__c> selectedDataSBIS = SbiCodeSelector.newInstance().selectByDossierId(dossiersByIds.keySet());
        System.assert(selectedDataSBIS.size() == 50);
        for (Business_Data_SBI__c businessDataSBI : selectedDataSBIS) {
            System.assert(!String.isEmpty(businessDataSBI.SBI_Code__c));
            System.assert(!String.isEmpty(businessDataSBI.SBI_Description__c));
            System.assert(!String.isEmpty(businessDataSBI.SBI_Type__c));
        }
    }
}