force-app/main/default/objects/Account/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business data fetched from Company.info</description>
    <inlineHelpText>The business data fetched from Company.info</inlineHelpText>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Dutch Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/services/impl/classes/BusinessDuplicateServiceImpl.cls
/**
 * Created by jaapbranderhorst on 2019-06-19.
 */

public without sharing class BusinessDuplicateServiceImpl implements IBusinessDuplicateService {

    public List<CheckDuplicateDossierResponse> checkForDuplicateDossiers(List<CheckDuplicateDossierRequest> requests) {
        try {
            // prep the query
            Set<DossierQueryDTO> queryDTOS = new Set<DossierQueryDTO>();
            for (CheckDuplicateDossierRequest checkDuplicateDossierRequest : requests) {
                queryDTOS.add(new DossierQueryDTO(checkDuplicateDossierRequest.dossierNumber, checkDuplicateDossierRequest.establishmentNumber));
            }
            // execute the query
            List<Business_Dossier__c> dossiers = BusinessDossierSelector.newInstance().selectByDossierNumbers(queryDTOS, false);

            // map the found dossiers on the request params
            Map<String, Business_Dossier__c> dossiersByDossierAndEstablishmentNumber = new Map<String, Business_Dossier__c>();
            for (Business_Dossier__c businessDossier : dossiers) {
                dossiersByDossierAndEstablishmentNumber.put(businessDossier.Dossier_Number__c + businessDossier.Establishment_Number__c, businessDossier);
            }
            List<CheckDuplicateDossierResponse> result = new List<CheckDuplicateDossierResponse>();
            for (CheckDuplicateDossierRequest checkDuplicateDossierRequest : requests) {
                String key = checkDuplicateDossierRequest.dossierNumber + checkDuplicateDossierRequest.establishmentNumber;
                result.add(new CheckDuplicateDossierResponse(
                        checkDuplicateDossierRequest.dossierNumber,
                        checkDuplicateDossierRequest.establishmentNumber,
                        dossiersByDossierAndEstablishmentNumber.get(key))
                );
            }
            return result;
        } catch (Exception ex) {
            ErrorLogUtil.logException(ex); // logging whenever we catch any exception other than CCException type
            throw new CCException(System.Label.DBSCall_Unknown_Exception, ex);
        }
    }

    /**
     * checks if there is a vat number related to dossiers with the given dossiernumber in the database. A dossier number
     *
     * @param dossierNumber
     *
     * @return a vat number if one is found, otherwise an empty string
     */
    public String checkForExistingVatNumberInDB(String dossierNumber) {
        // get the dossiers
        List<Business_Dossier__c> dossiersWithSameDossierNumber = ((IBusinessDossierSelector)Application.Selector.newInstance(Business_Dossier__c.SObjectType)).selectByDossierNumber(new Set<String>{dossierNumber}, false);
        // loop through the dossiers
        String vatNumber = '';
        for (Business_Dossier__c businessDossier : dossiersWithSameDossierNumber) {
            if (!String.isEmpty(businessDossier.VAT_Number__c)) {
                vatNumber = businessDossier.VAT_Number__c;
                break;
            }
        }
        return vatNumber;
    }

    /**
     * checks for account duplicates. Return a List of IDs if duplicates for the given account exist.
     *
     * @param acc
     *
     * @return
     */
    public List<Account> checkForAccountDuplicates(Account acc){
        List<Account> result = new List<Account>();
        try{
            Datacloud.FindDuplicatesResult[] results = Datacloud.FindDuplicates.findDuplicates(new List<Account>{acc});
            for (Datacloud.FindDuplicatesResult dupeResult : results) {
                for (Datacloud.DuplicateResult dupeRes : dupeResult.getDuplicateResults()) {
                    for (Datacloud.MatchResult matchRes : dupeRes.getMatchResults()) {
                        for (Datacloud.MatchRecord matchRec : matchRes.getMatchRecords()) {
                            result.add((Account)matchRec.getRecord());
                        }
                    }
                }
            }
        }catch(System.HandledException e){ // thrown if no duplicate rules are active. Let it fail silently to cover for orgs without duplicate management
            System.debug(LoggingLevel.INFO, 'No duplicate management for accounts in this org');
        }
        return result;
    }

}