force-app/main/default/objects/Account/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business data fetched from Company.info</description>
    <inlineHelpText>The business data fetched from Company.info</inlineHelpText>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Dossiers</relationshipLabel>
    <relationshipName>Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PostInstallScriptTest.cls
/**
 * Created by jaapbranderhorst on 2019-07-17.
 */

@IsTest
private class PostInstallScriptTest {
    
    @TestSetup
    static void testSetup() {
        Integer nrOfAccountsWithoutRecordTypeId = 20;
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < nrOfAccountsWithoutRecordTypeId; i++) {
            accounts.add(new Account(Name = '' + i));
        }
        insert accounts;

    }
    
    @IsTest
    static void testV20Upgrade() {
        List<Account> accounts = [SELECT Id, Name FROM Account];
        List<Business_Dossier__c> dossiers = new List<Business_Dossier__c>();
        for (Account account : accounts) {
            dossiers.add(new Business_Dossier__c(Name = account.Name, Account__c = account.Id));
        }
        insert dossiers;
        // Test.testInstall(new PostInstallScript(), new Version(1,0)); // simulate an installed version since this is an upgrade test.
        Test.startTest();
        {
            Test.testInstall(new PostInstallScript(), new Version(2, 0));
        }
        Test.stopTest();
        dossiers = [SELECT Id FROM Business_Dossier__c WHERE RecordTypeId = :Schema.SObjectType.Business_Dossier__c.getRecordTypeInfosByName().get('Dutch Business').getRecordTypeId()];
        System.assert(dossiers.size() == 20);
    }

    @IsTest
    static void testInstall() {
        Test.startTest();
        {
            try {
                Test.testInstall(new PostInstallScript(), null);
            } catch (Exception ex) {
                System.assert(false);
            }
            System.assert(true);
        }
        Test.stopTest();
    }
}