force-app/main/default/objects/Account/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Dutch Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dutch_Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dutch_Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dutch Business Dossier</label>
    <referenceTo>Dutch_Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/Dutch_Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Dutch Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dutch Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dutch Business Dossiers</relationshipLabel>
    <relationshipName>Dutch_Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/services/impl/classes/DutchBusinessServiceImplTest.cls
@isTest
public with sharing class DutchBusinessServiceImplTest {
    
@isTest
public static void testGetDossierAccount(){
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    //fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    //IWebServicesNLSOAPDutchBusiness mockWS = (IWebServicesNLSOAPDutchBusiness)mocks.mock(IWebServicesNLSOAPDutchBusiness.class);
    IDutchBusinessDossierSelector selectorMockDossier = (IDutchBusinessDossierSelector)mocks.mock(IDutchBusinessDossierSelector.class);// new Mocks.DutchBusinessDossierSelector(mocks);
    IAccountSelector selectorMockAccount = (IAccountSelector)mocks.mock(IAccountSelector.class); //new Mocks.DutchBusinessDossierSelector(mocks);
// Given
    mocks.startStubbing();
    Integer dossierNumber = 40000000;
    Account acc = new Account(
            Name = 'Test',
            Id = fflib_IDGenerator.generate(Account.SObjectType)
        );
        List<Dutch_Business_Dossier__c> dossierList = new List<Dutch_Business_Dossier__c> {
            new Dutch_Business_Dossier__c(
                Id = fflib_IDGenerator.generate(Dutch_Business_Dossier__c.SObjectType),
                Name = 'Test',
                Dossier_Number__c = dossierNumber,
                Account__c = acc.Id
            )
        };
        mocks.when(selectorMockDossier.sObjectType()).thenReturn(Dutch_Business_Dossier__c.SObjectType);
        mocks.when(selectorMockDossier.selectByDossierNumber(new set<Integer>{dossierNumber})).thenReturn(dossierList);
        mocks.when(selectorMockAccount.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorMockAccount.selectById(new set<Id>{acc.Id})).thenReturn(new list<Account>{acc});
        mocks.stopStubbing();
        //Application.UnitOfWork.setMock(uowMock);
        Application.Selector.setMock(selectorMockAccount);
        Application.Selector.setMock(selectorMockDossier);
        //Application.service.setMock(IWebServicesNLSOAPDutchBusiness.class, mockWS);
        test.startTest();
        //IDutchBusinessService service = DutchBusinessService.newInstance();
        Account result = DutchBusinessService.getDossierAccount(String.valueOf(dossierNumber));
        system.assertEquals(acc.Id, result.Id);
}


}