force-app/main/default/objects/Account/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Dutch Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dutch_Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dutch_Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dutch Business Dossier</label>
    <referenceTo>Dutch_Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/Dutch_Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Dutch Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dutch Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dutch Business Dossiers</relationshipLabel>
    <relationshipName>Dutch_Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/selectors/main/classes/DutchBusinessDossierSelectorTest.cls
/****************************************************************************************
Author          : ValerijsProkudins
******************************************************************************************/
@isTest
public with sharing class DutchBusinessDossierSelectorTest {

    
    @isTest
    static void testGetInstance() {
        Object o = DutchBusinessDossierSelector.newInstance();
        System.assert(o instanceof DutchBusinessDossierSelector);
    }
    @isTest
    static void testGetSObjectFields() {
        DutchBusinessDossierSelector selector = (DutchBusinessDossierSelector) DutchBusinessDossierSelector.newInstance();
        Test.startTest();
        System.runAs(TestUtils.getBDSUser()) { //didnt work. need to check with jaap how testutils work
            List<Schema.SObjectField> fields = selector.getSObjectFieldList();
            Set<Schema.SObjectField> fieldsAsSet = new Set<Schema.SObjectField>(fields);
            System.assert(fieldsAsSet.containsAll(new List<Schema.SObjectField>{
                Dutch_Business_Dossier__c.Id,
                Dutch_Business_Dossier__c.Name,
                Dutch_Business_Dossier__c.Account__c,
                Dutch_Business_Dossier__c.Account__r.Id,
                Dutch_Business_Dossier__c.Account__r.name
            }));
        }
        Test.stopTest();
        

    }

    @isTest
    static void testGetSObjectType() {
        DutchBusinessDossierSelector selector = (DutchBusinessDossierSelector) DutchBusinessDossierSelector.newInstance();
        Test.startTest();
        System.runAs(TestUtils.getBDSUser()) {//didnt work. need to check with jaap how testutils work
            Schema.SObjectType tpe = selector.getSObjectType();
            System.assertEquals(Dutch_Business_Dossier__c.sObjectType, tpe);
        }
        Test.stopTest();

    }
   

    @isTest
    static void testSelectByDossierNumber() {
        List<Account> accounts = new List<Account>();
        for (Integer i2 = 0; i2 < 10 ; i2++) {
            accounts.add(new Account(Name = 'test'+i2));
        }
        insert accounts;
        List<Dutch_Business_Dossier__c> dossiers = new List<Dutch_Business_Dossier__c>();
        Set<String> dossierNumSet = new set<String>();
        for (Integer i2 = 0; i2 < 10 ; i2++) {
            dossiers.add(new Dutch_Business_Dossier__c(Account__c = accounts[0].Id, Name = 'test'+i2, Dossier_Number__c=string.valueOf(i2)));
            dossierNumSet.add(string.valueOf(i2));
        }
        insert dossiers;
        

        

        Test.startTest();
        System.runAs(TestUtils.getBDSUser()) {//didnt work. need to check with jaap how testutils work
            IDutchBusinessDossierSelector selector = DutchBusinessDossierSelector.newInstance();
            List<Dutch_Business_Dossier__c> dossiersReturned = selector.selectByDossierNumber(dossierNumSet);
            System.assertEquals(10, dossiersReturned.size());
        }
        Test.stopTest();


    }






}