force-app/main/default/objects/Account/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Dutch Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dutch_Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dutch_Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dutch Business Dossier</label>
    <referenceTo>Dutch_Business_Dossier__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/Dutch_Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Dutch Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dutch Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dutch Business Dossiers</relationshipLabel>
    <relationshipName>Dutch_Business_Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Authorized_Share_Capital_Currency__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Share_Capital_Currency__c</fullName>
    <label>Currency For Authorized Share Capital</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Chamber_Number__c.field-meta.xml
<CustomField>
    <fullName>Chamber_Number__c</fullName>
    <description>The chamber number is the number of the Chamber of Commerce office which manages this dossier.


01	Noord Nederland
08	Oost Nederland
09	Centraal Gelderland
14	Limburg
17	Brabant
20	Zuid West Nederland
24	Rotterdam
27	Den Haag
30	Midden Nederland
32	Gooi-, Eem- en Flevoland
34	Amsterdam
37	Noordwest-Holland</description>
    <label>Chamber Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01	Noord Nederland</fullName>
            </value>
            <value>
                <fullName>08	Oost Nederland</fullName>
            </value>
            <value>
                <fullName>09	Centraal Gelderland</fullName>
            </value>
            <value>
                <fullName>14	Limburg</fullName>
            </value>
            <value>
                <fullName>17	Brabant</fullName>
            </value>
            <value>
                <fullName>20	Zuid West Nederland</fullName>
            </value>
            <value>
                <fullName>24	Rotterdam</fullName>
            </value>
            <value>
                <fullName>27	Den Haag</fullName>
            </value>
            <value>
                <fullName>30	Midden Nederland</fullName>
            </value>
            <value>
                <fullName>32	Gooi-, Eem- en Flevoland</fullName>
            </value>
            <value>
                <fullName>34	Amsterdam</fullName>
            </value>
            <value>
                <fullName>37	Noordwest-Holland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Class_Personnel__c.field-meta.xml
<CustomField>
    <fullName>Class_Personnel__c</fullName>
    <description>A classification of the total number of employees (full-time and part-time).  Possible values:
1	no employees
2	1 employee
3	2 to 4 employees
4	5 to 9 employees
5	10 to 19 employees
6	20 to 49 employees
7	50 to 99 employees
8	100 to 199 employees
9	199 to 499 employees
10	500 to 749 employees
11	750 to 999 employees
12	1000 or more employees</description>
    <label>Class Personnel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class_Personnel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Class_Personnel_Fulltime__c.field-meta.xml
<CustomField>
    <fullName>Class_Personnel_Fulltime__c</fullName>
    <label>Class Personnel Fulltime</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class_Personnel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Continuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Continuation_Date__c</fullName>
    <description>The continuation date of the company, if applicable. This is usually the date that the company changed legal form.</description>
    <label>Continuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Discontinuation_Date__c.field-meta.xml
<CustomField>
    <fullName>Discontinuation_Date__c</fullName>
    <description>The date when the business was discontinued (Dutch: datum wanneer de activiteiten gestaakt zijn)</description>
    <label>Discontinuation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Dossier Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Indication_Main_Establishment__c.field-meta.xml
<CustomField>
    <fullName>Indication_Main_Establishment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if this is the main establishment of the business.</description>
    <label>Indication Main Establishment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Indication_Organisation_Code__c.field-meta.xml
<CustomField>
    <fullName>Indication_Organisation_Code__c</fullName>
    <description>Possible values:
O	Business (Dutch: ‘Onderneming)
V	Association (Dutch: ‘Vereniging’)
S	Non-profit organisation (Dutch: ‘Stichting’)
K	Church community (Dutch: ‘Kerkgenootschap’)
&lt;empty&gt;	Unknown</description>
    <label>Indication Organisation Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Association</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Non-profit organisation</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Church community</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Issued_Share_Capital_Currency__c.field-meta.xml
<CustomField>
    <fullName>Issued_Share_Capital_Currency__c</fullName>
    <label>Issued Share Capital Currency</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Legal_Form_Text__c.field-meta.xml
<CustomField>
    <fullName>Legal_Form_Text__c</fullName>
    <description>Description of the legal form (in Dutch).</description>
    <label>Legal Form Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Main_Establishment_Number__c.field-meta.xml
<CustomField>
    <fullName>Main_Establishment_Number__c</fullName>
    <description>The establishment number for the main establishment of the business.  Optional.</description>
    <label>Main Establishment Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Paid_Up_Share_Capital_Currency__c.field-meta.xml
<CustomField>
    <fullName>Paid_Up_Share_Capital_Currency__c</fullName>
    <label>Currency For Paid Up Share Capital</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Personnel__c.field-meta.xml
<CustomField>
    <fullName>Personnel__c</fullName>
    <label>Personnel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Personnel_Fulltime__c.field-meta.xml
<CustomField>
    <fullName>Personnel_Fulltime__c</fullName>
    <label>Personnel Fulltime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Personnel_Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Personnel_Reference_Date__c</fullName>
    <description>The reference date (peildatum) of the number of employees.</description>
    <label>Personnel Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Rsin_Number__c.field-meta.xml
<CustomField>
    <fullName>Rsin_Number__c</fullName>
    <description>The 9 number RSIN (`Rechtspersonen Samenwerkingsverbanden Informatie Nummer`) identifying the business’ legal entity.  Optional, businesses with a sole proprietor (`eenmanszaken`) do not have an rsin_number.</description>
    <label>Rsin Number</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Secondary_Sbi_Code_1__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Sbi_Code_1__c</fullName>
    <label>Secondary SBI Code 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Secondary_Sbi_Code_2__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Sbi_Code_2__c</fullName>
    <label>Secondary SBI Code 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dutch_Business_Dossier__c/fields/Trade_Name_45__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_45__c</fullName>
    <description>Primary name under which the business engages in commercial activity.  Shortened to a maximum of 45 characters.</description>
    <label>Trade Name 45</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/dutchBusiness/globalValueSets/Class_Personnel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>unknown</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>no employees</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>1 employee</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>2 to 4 employees</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>5 to 9 employees</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>10 to 19 employees</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>20 to 49 employees</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>50 to 99 employees</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>100 to 199 employees</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>199 to 499 employees</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>500 to 749 employees</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>750 to 999 employees</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>1000 or more employees</label>
    </customValue>
    <masterLabel>Class Personnel</masterLabel>
</GlobalValueSet>

force-app/main/services/DutchBusinessService.cls
/****************************************************************************************
Author          : ValerijsProkudins
Description     : Service layer for DutchBusiness webservice calls and data processing
******************************************************************************************/
public with sharing class DutchBusinessService {
    
   private static WebServicesNLSOAPDutchBusinessImplTypes.DutchBusinessReferenceV2PagedResult returnedResults;
   private static list<WebServicesNLSOAPDutchBusinessImplTypes.DutchBusinessReferenceV2> searchResults; 
    
   public static WebServicesNLSOAPDutchBusinessImplTypes.DutchBusinessReferenceV2[] searchForDossiers(CompanySearchDto searchParams){
        // Handle valid postcodes that the web service does not like
        if (searchParams.postcode != null)
            searchParams.postcode = searchParams.postcode.replaceAll('(\\s+)', '').toUpperCase();

        IWebServicesNLSOAPDutchBusiness service = WebServicesNLSOAPDutchBusiness.newInstance();
        try{
            returnedResults = service.dutchBusinessSearchParametersV2(searchParams.name,searchParams.city,searchParams.street,searchParams.postcode,null,null,searchParams.phone,searchParams.domain,Constants.Strict_Search,Constants.paramInt).DutchBusinessReferenceV2PagedResult;
            if(returnedResults != null && returnedResults.results != null && returnedResults.results.item != null && returnedResults.results.item.size()>0){
                searchResults=returnedResults.results.item;
            }
            else{
                System.debug('no items');
                // searchResults=returnedResults;
            }
            //return parsed result
            return searchResults;
        }catch(System.CalloutException ex){
            throw new CustomException('The call to the service was unsuccessfull'+ex.getMessage());
        }
    }
    
    public static DutchBusinessDto getInfo(String dossierNumber) {
        if (dossierNumber == null) return null;
         IWebServicesNLSOAPDutchBusiness service = WebServicesNLSOAPDutchBusiness.newInstance();
        try{
            return service.dutchBusinessGetDossierV3(dossierNumber, null);//.dutchBusinessGetDossierV3Response;
        }catch(System.CalloutException ex){
            throw new CustomException('The call to the service was unsuccessfull'+ex.getMessage());
        }


    }
    public static void updateAccountDossier(Id accountId, Id dossierId) {
        List<Account> accts = [SELECT Id, Dutch_Business_Dossier__c FROM Account WHERE Id = :accountId];
        if (accts.size() == 1 && dossierId != NULL) {
            accts[0].Dutch_Business_Dossier__c = dossierId;
            update accts;
        }
    }
    
    
    private static Boolean checkAccess() {
         List<String> fields = new List<String>{'Name','Establishment_Number__c','Main_Establishment_Number__c',
        'Indication_Main_Establishment__c','Rsin_Number__c','Chamber_Number__c','Legal_Form_Code__c','Legal_Form_Text__c','Indication_Organisation_Code__c',
        'Trade_Name_45__c','Trade_Name_Full__c','Trade_Names__c','Telephone_Number__c','Mobile_Number__c','Domain_Name__c','Authorized_Share_Capital__c',
        'Authorized_Share_Capital_Currency__c','Class_Personnel__c','Class_Personnel_Fulltime__c','Continuation_Date__c','Discontinuation_Date__c','Establishment_Date__c',
        'Founding_Date__c','Issued_Share_Capital__c','Issued_Share_Capital_Currency__c','Paid_Up_Share_Capital__c','Paid_Up_Share_Capital_Currency__c',
        'Personnel__c','Personnel_Fulltime__c','Personnel_Reference_Date__c','Primary_Sbi_Code__c','Primary_Sbi_Code_Text__c','Secondary_Sbi_Code_1__c',
        'Secondary_Sbi_Code_1_Text__c','Secondary_Sbi_Code_2__c','Secondary_Sbi_Code_2_Text__c','Status__c'};

        Schema.sObjectType.Dutch_Business_Dossier__c.fields.getMap();

        Schema.DescribeSObjectResult a_desc = Dutch_Business_Dossier__c.sObjectType.getDescribe(); 
        //for the Account object, you can replace that with any object you have, standard or custom
        Map<String, Schema.SObjectField> a_fields = a_desc.fields.getMap();

        for(Schema.sObjectField fld: a_fields.values()){ 
            if (fld.getDescribe().isUpdateable() == false && fields.contains(fld.getDescribe().getName())) {
                return false;
            }
        }


        return true;
    }

    public static Id saveDutchBusinessDossier(WebServicesNLSOAPDutchBusinessImplTypes.DutchBusinessDossierV3 dossier, Id accountId) {
        if (Schema.sObjectType.Dutch_Business_Dossier__c.fields.Id.isAccessible() == false ||
            Schema.sObjectType.Dutch_Business_Dossier__c.fields.Account__c.isAccessible() == false ||
            checkAccess() == false) throw new NoAccessException();

        List<Dutch_Business_Dossier__c> dbds = [SELECT Id, Account__c FROM Dutch_Business_Dossier__c WHERE Dossier_Number__c = :Integer.valueOf(dossier.dossier_number)];
        Dutch_Business_Dossier__c d;

        String trade_names = '';
        if (dossier.trade_names != null && dossier.trade_names.item != null && dossier.trade_names.item.size() > 0) {
            // Condense all trade names into single field, seperated by new lines.
            for (Integer i = 0; i < dossier.trade_names.item.size(); i++) {
                trade_names += dossier.trade_names.item[i] + '/n';
            }
        }

        if (dbds.size() < 1) {
            d = new Dutch_Business_Dossier__c();
            d.Account__c = accountId;
        }
        else {
            d = dbds[0];
            if (d.Account__c !=  accountId) {
                throw new AuraHandledException('Dossier is already allocated to another Account');
            }
        }

        // @todo add addresses and contact.
        system.debug('VPROK tests dosier = '+ dossier);
        d.Name = dossier.legal_name;
        d.Dossier_Number__c = Integer.valueOf(dossier.dossier_number);
        d.Establishment_Number__c = Integer.valueOf(dossier.establishment_number);
        d.Main_Establishment_Number__c = Integer.valueOf(dossier.main_establishment_number);
        d.Indication_Main_Establishment__c = Boolean.valueOf(dossier.indication_main_establishment);
        if(dossier.rsin_number != null){d.Rsin_Number__c = Integer.valueOf(dossier.rsin_number);}
        if(dossier.chamber_number != null){d.Chamber_Number__c = Integer.valueOf(dossier.chamber_number);}
        if(dossier.legal_form_code != null){d.Legal_Form_Code__c = Integer.valueOf(dossier.legal_form_code);}
        if(dossier.legal_form_text != null){d.Legal_Form_Text__c = String.valueOf(dossier.legal_form_text);}
        if(dossier.indication_organisation_code != null){d.Indication_Organisation_Code__c = String.valueOf(dossier.indication_organisation_code);}
        d.Trade_Name_45__c = dossier.trade_name_45;
        d.Trade_Name_Full__c = dossier.trade_name_full;
        d.Trade_Names__c = trade_names;
        d.Telephone_Number__c = dossier.telephone_number;
        d.Mobile_Number__c = dossier.mobile_number;
        d.Domain_Name__c = dossier.domain_name;

        d.Authorized_Share_Capital__c = dossier.authorized_share_capital;
        d.Authorized_Share_Capital_Currency__c = dossier.authorized_share_capital_currency;
        if(dossier.class_personnel != null){d.Class_Personnel__c = String.valueOf(dossier.class_personnel);}
        if(dossier.class_personnel_fulltime != null){d.Class_Personnel_Fulltime__c = String.valueOf(dossier.class_personnel_fulltime);}
        if(dossier.continuation_date != null){d.Continuation_Date__c = convertDate(dossier.continuation_date);}
        if(dossier.discontinuation_date != null){d.Discontinuation_Date__c = convertDate(dossier.discontinuation_date);}
        if(dossier.establishment_date != null){d.Establishment_Date__c = convertDate(dossier.establishment_date);}
        if(dossier.founding_date != null){d.Founding_Date__c = convertDate(dossier.founding_date);}
        if(dossier.issued_share_capital != null){d.Issued_Share_Capital__c = Integer.valueOf(dossier.issued_share_capital);}
        d.Issued_Share_Capital_Currency__c = dossier.issued_share_capital_currency;
        if(dossier.paid_up_share_capital != null){d.Paid_Up_Share_Capital__c = Integer.valueOf(dossier.paid_up_share_capital);}
        d.Paid_Up_Share_Capital_Currency__c = dossier.paid_up_share_capital_currency;
        d.Personnel__c = dossier.personnel;
        d.Personnel_Fulltime__c = dossier.personnel_fulltime;
        if(dossier.personnel_reference_date != null){d.Personnel_Reference_Date__c = convertDate(dossier.personnel_reference_date);}
        d.Primary_Sbi_Code__c = dossier.primary_sbi_code;
        d.Primary_Sbi_Code_Text__c = dossier.primary_sbi_code_text;
        d.Secondary_Sbi_Code_1__c = dossier.secondary_sbi_code1;
        d.Secondary_Sbi_Code_1_Text__c = dossier.secondary_sbi_code1_text;
        d.Secondary_Sbi_Code_2__c = dossier.secondary_sbi_code2;
        d.Secondary_Sbi_Code_2_Text__c = dossier.secondary_sbi_code2_text;
        d.Status__c = determineStatus(dossier);

        upsert d;
        return d.Id;
    }
    private static String determineStatus(WebServicesNLSOAPDutchBusinessImplTypes.DutchBusinessDossierV3 dossier) {
        List<String> status = new List<String>();
        if (dossier.indication_import != null && Boolean.valueOf(dossier.indication_import) == true) status.add('Import');
        if (dossier.indication_export != null && Boolean.valueOf(dossier.indication_export) == true) status.add('Export');
        if (dossier.indication_economically_active != null && Boolean.valueOf(dossier.indication_economically_active) == true) status.add('Economically Active');
        if (dossier.indication_non_mailing != null && Boolean.valueOf(dossier.indication_non_mailing) == true) status.add('Non Mailing');
        if (dossier.indication_bankruptcy != null && Boolean.valueOf(dossier.indication_bankruptcy) == true) status.add('Bankruptcy');
        if (dossier.indication_dip != null && Boolean.valueOf(dossier.indication_dip) == true) status.add('DIP');
        return String.join(status, ';');
    }

    private static Date convertDate(WebServicesNLSOAPDutchBusinessImplTypes.DutchBusinessDateV3 d) {
        if (d != null) return Date.newInstance(d.year, d.month, d.day);
        return null;
    }

    




    public class CompanySearchDto {
        public string name;
        public string domain;
        public string phone;
        public string street;
        public string city;
        public string postcode;
        public string province;
        public string country;
    }

}