force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/fields/Business_Positions_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Positions_Updated_Date__c</fullName>
    <description>The date that the business positions were updated in Salesforce.</description>
    <label>Business Positions Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/services/DuplicateManagement/FindDuplicateDossiersInvocableTest.cls
/**
 * Created by hugovankrimpen on 08/07/2020.
 */

@IsTest
public with sharing class FindDuplicateDossiersInvocableTest {
    @TestSetup
    static void setup() {
        System.runAs(CompanyInfoTestUserFactory.getDutchBusinessUser()) {
            Datetime updatedTime = Datetime.now();
            Business_Dossier__c businessDossier = new Business_Dossier__c();
            businessDossier.Dossier_Number__c = '123';
            businessDossier.Establishment_Number__c = '456';
            businessDossier.Business_Positions_Updated_Date__c = updatedTime;
            insert businessDossier;
        }

    }

    @IsTest
    static void findDuplicatesHappyFlowTest() {
        System.runAs(CompanyInfoTestUserFactory.getDutchBusinessUser()) {
            Business_Dossier__c businessDossier = new Business_Dossier__c();
            businessDossier.Dossier_Number__c = '123';
            businessDossier.Establishment_Number__c = '456';

            FindDuplicateDossiersInvocable.FindDuplicateDossiersArgument argument = new FindDuplicateDossiersInvocable.FindDuplicateDossiersArgument();
            argument.dossier = businessDossier;
            Test.startTest();
            List<List<Business_Dossier__c>> duplicateDossiers =
                    FindDuplicateDossiersInvocable.findDuplicates(new List<FindDuplicateDossiersInvocable.FindDuplicateDossiersArgument>{
                            argument
                    });
            Test.stopTest();

            System.assertNotEquals(duplicateDossiers, null);
            System.assertEquals(1, duplicateDossiers.size());
            System.assertEquals(1, duplicateDossiers[0].size());

            //Check if the fields come over correctly.
            Business_Dossier__c businessDossier2 = duplicateDossiers[0][0];
            System.assertNotEquals(null, businessDossier2.Business_Positions_Updated_Date__c);
        }

    }
    @IsTest
    static void findDuplicatesNoInputTest() {
        System.runAs(CompanyInfoTestUserFactory.getDutchBusinessUser()) {
            Test.startTest();
            List<List<Business_Dossier__c>> duplicateDossiers = FindDuplicateDossiersInvocable.findDuplicates(new List<FindDuplicateDossiersInvocable.FindDuplicateDossiersArgument>{});
            Test.stopTest();
            System.assertNotEquals(null, duplicateDossiers);
            System.assertEquals(1, duplicateDossiers.size());
            System.assertEquals(0, duplicateDossiers[0].size());
        }
    }
}