force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/services/DuplicateManagement/FindDuplicateDossiersInvocable.cls
/**
 * Created by hugovankrimpen on 08/07/2020.
 */

global inherited sharing class FindDuplicateDossiersInvocable {
    global inherited sharing class FindDuplicateDossiersArgument {
        @InvocableVariable(label='Dossier' description='The sobject value' required=true)
        global SObject dossier;

        @TestVisible
        private FindDuplicateDossiersArgument(String dossierNumber, String establishmentNumber) {
            //this.dossierNumber = dossierNumber;
            //this.establishmentNumber = establishmentNumber;
        }

        global FindDuplicateDossiersArgument() {

        }
    }


    @InvocableMethod(
            label='Find Duplicate Dossiers'
            description='Find Duplicate Dossiers in Salesforce, based on the Dossier number and Establishment number.'
            category='Company.info')
    global static List<List<SObject>> findDuplicates(List<FindDuplicateDossiersArgument> findDuplicatesArguments) {
        try {
            List<List<Business_Dossier__c>> response = new List<List<Business_Dossier__c>>();
            List<String> dossierNumbers = new List<String>();
            List<String> establishmentNumbers = new List<String>();
            for(FindDuplicateDossiersArgument argument : findDuplicatesArguments){
                if(argument.dossier instanceof Business_Dossier__c) {
                    Business_Dossier__c businessDossier = (Business_Dossier__c)argument.dossier;
                    dossierNumbers.add(businessDossier.Dossier_Number__c);
                    establishmentNumbers.add(businessDossier.Establishment_Number__c);
                }
            }
            List<Business_Dossier__c> duplicateBusinessDossiers = BusinessService.findDuplicateDossiersByDossierAndEstablishmentNumber(dossierNumbers, establishmentNumbers);
            response.add(duplicateBusinessDossiers);

            return response;


        }catch (Exception ex) {
            ErrorLogUtil.logException(ex, true);
            throw ex;
        }
    }
}