force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/modules/Lead/classes/CreateBusinessDossierInvocable.cls
/**
 * Created by vishalshete on 14/08/2020.
 */

global with sharing class CreateBusinessDossierInvocable {
    global inherited sharing class CreateBusinessDossierArgument {
        @InvocableVariable(
                label='Dossier'
                description='The Dutch dossier to be inserted. This will be inserted.'
                required=true)
        global List<SObject> businessDossiers;

        global CreateBusinessDossierArgument() {
        }
    }
    @InvocableMethod(
            label='Create Business Dossiers'
            description='Create Business Dossiers'
            category='Company.info')
    global static List<Business_Dossier__c> createBusinessDossier(List<CreateBusinessDossierArgument> arguments) {
        try {
            List<Business_Dossier__c> businessDossiersToUpsert = new List<Business_Dossier__c>();
            List<Business_Dossier__c> businessDossiers= new List<Business_Dossier__c>();
            for (CreateBusinessDossierArgument argument : arguments) {
                //This invocable can only be called with both arguments filled of type business dossier.
                if (argument.businessDossiers == null) {
                    throw new AuraHandledException(Label.Error_Input_Incorrect);
                } else{
                    businessDossiers = argument.businessDossiers;
                }
            }
            businessDossiersToUpsert = checkDuplicate(businessDossiers);
            List<Business_Dossier__c> insertedBusinessDossiers = BusinessService.createDossiers(businessDossiersToUpsert, true);
                return insertedBusinessDossiers;
        }
        catch (Exception ex) {
            ErrorLogUtil.logException(ex, true);
            throw ex;
        }
    }

    public static List<Business_Dossier__c> checkDuplicate(List<Business_Dossier__c> dossiers){
        List<String> dossierNumbers = new List<String>();
        List<String> establishmentNumbers = new List<String>();
        for(Business_Dossier__c businessDossier : dossiers){
                dossierNumbers.add(businessDossier.Dossier_Number__c);
                establishmentNumbers.add(businessDossier.Establishment_Number__c);
        }
        List<Business_Dossier__c> duplicateBusinessDossiers = BusinessService.findDuplicateDossiersByDossierAndEstablishmentNumber(dossierNumbers, establishmentNumbers);

        Map<String,Business_Dossier__c> duplicateDossierMap = new Map<String, Business_Dossier__c>();
        for(Business_Dossier__c businessDossier : duplicateBusinessDossiers){
            duplicateDossierMap.put(businessDossier.Dossier_Number__c+businessDossier.Establishment_Number__c,businessDossier);
        }
        List<Business_Dossier__c> businessDossiersToReturn = new List<Business_Dossier__c>();
        for(Business_Dossier__c dossier : dossiers){
            if(!duplicateDossierMap.containsKey(dossier.Dossier_Number__c+dossier.Establishment_Number__c)){
                businessDossiersToReturn.add(dossier);
            }
        }
        return businessDossiersToReturn;
    }
}