force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Creditsafe_Company_Report_Full__c.field-meta.xml
<CustomField>
    <fullName>Creditsafe_Company_Report_Full__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report Full</label>
    <referenceTo>Creditsafe_Company_Report_Full__c</referenceTo>
    <relationshipLabel>Other Addresses</relationshipLabel>
    <relationshipName>Other_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/recordTypes/Creditsafe.recordType-meta.xml
<RecordType>
    <fullName>Creditsafe</fullName>
    <active>true</active>
    <description>Record type for dossiers coming from CreditSafe itself.</description>
    <label>Creditsafe</label>
</RecordType>

force-app/main/modules/creditSafe/objects/Creditsafe_Company_Report_Full__c/Creditsafe_Company_Report_Full__c.object-meta.xml
<CustomObject>
    <description>A detailed report about a company.</description>
    <label>Creditsafe Company Report</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Creditsafe Company Report Full Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Creditsafe Company Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/modules/creditSafe/objects/Creditsafe_Company_Report_Full__c/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[DEPRECATED] Use the lookup from Business Dossier to Creditsafe Company Report instead.</description>
    <label>Business Dossier</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Creditsafe Company Reports</relationshipLabel>
    <relationshipName>Creditsafe_Company_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/services/definition/classes/ICreditSafeService.cls
/**
 * Created by jaapbranderhorst on 2019-07-03.
 */

public interface ICreditSafeService {

    List<Business_Dossier__c> searchForCreditSafeDossiers(List<CreditSafe.Country> countries, String id, String status, String registration_number, String registration_type, String vat_number, String province, String city, String street, String postal_code, String name);
    Creditsafe_Company_Report_Full__c getCreditsafeReportFullV2(String company_id, String language, String reason);

}