force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <description>Creditsafe company identifier used to retrieve a report.</description>
    <label>Company Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/services/invocable/classes/GetCompanyIdInvocable.cls
/**
 * Created by tejaswinidandi on 09/03/2020.
 */

global with sharing class GetCompanyIdInvocable {

    @InvocableMethod(label='Search for Company ID' description='Searches for company Id based on the given arguments.' category='Company.info for Sales')
    global static List<String> searchForCompanyId(List<SearchForCreditSafeDossiersInvocable.SearchForCreditSafeDossiersArgument> arguments) {
        List<List<Business_Dossier__c>> dossierLists = SearchForCreditSafeDossiersInvocable.searchForCreditSafeDossier(arguments);
        System.debug(dossierLists);
        String companyId = dossierLists.size() > 0 && dossierLists[0].size() > 0 ? dossierLists[0][0].Company_Id__c : null;
        return new List<String>{companyId};
    }
}