force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/services/invocable/classes/CreateDutchDossierInvocableTest.cls
/**
 * Created by jaapbranderhorst on 23/02/2020.
 */

@IsTest
private class CreateDutchDossierInvocableTest {
    @IsTest
    static void testCreateDutchDossierInvocableHappyFlow() {
        // given
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IDutchBusinessService dutchBusinessServiceMock = (IDutchBusinessService)mocks.mock(IDutchBusinessService.class);

        mocks.startStubbing();
        String dossierNumber1 = '1234';
        String establishmentNUmber2 = '3234';
        String dossierNumber2 = null;
        String establishmentNUmber1 = '1234';
        Business_Dossier__c dossier1 = new Business_Dossier__c(Name = 'test1', Dossier_Number__c = dossierNumber1, Establishment_Number__c = establishmentNUmber1, Id = fflib_IDGenerator.generate(Business_Dossier__c.SObjectType));
        Business_Dossier__c dossier2 = new Business_Dossier__c(Name = 'test2', Dossier_Number__c = dossierNumber2, Establishment_Number__c = establishmentNUmber2, Id = fflib_IDGenerator.generate(Business_Dossier__c.SObjectType));
        mocks.when(dutchBusinessServiceMock.createDutchDossier(dossierNumber1, establishmentNUmber1)).thenReturn(dossier1);
        mocks.when(dutchBusinessServiceMock.createDutchDossier(dossierNumber2, establishmentNUmber2)).thenReturn(dossier2);
        mocks.stopStubbing();

        Application.Service.setMock(IDutchBusinessService.class, dutchBusinessServiceMock);

        // when
        List<CreateDutchDossierInvocable.CreateDutchDossierArgument> arguments = new List<CreateDutchDossierInvocable.CreateDutchDossierArgument>();
        arguments.add(new CreateDutchDossierInvocable.CreateDutchDossierArgument(dossierNumber1, establishmentNUmber1));
        arguments.add(new CreateDutchDossierInvocable.CreateDutchDossierArgument(dossierNumber2, establishmentNUmber2));
        Test.startTest();
        List<Business_Dossier__c> dossiers = CreateDutchDossierInvocable.createDutchDossier(arguments);
        Test.stopTest();

        // then
        System.assert(dossiers.size() == 2);
    }
}