force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Correspondence_City__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_City__c</fullName>
    <label>Correspondence City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Correspondence_Street__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Street__c</fullName>
    <label>Correspondence Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/fields/Establishment_City__c.field-meta.xml
<CustomField>
    <fullName>Establishment_City__c</fullName>
    <label>Establishment City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_street__c.field-meta.xml
<CustomField>
    <fullName>Establishment_street__c</fullName>
    <label>Establishment street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/fields/Indication_Main_Establishment__c.field-meta.xml
<CustomField>
    <fullName>Indication_Main_Establishment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating if this is the main establishment of the business.</description>
    <label>Main Establishment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Trade_Name_Full__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name_Full__c</fullName>
    <description>Primary name under which the business engages in commercial activity.  This is the full name, up to 132 characters long.</description>
    <label>Trade Name Full</label>
    <length>132</length>
    <type>Text</type>
</CustomField>

force-app/main/services/invocable/classes/SearchForDutchDossiersInvocableTest.cls
/**
 * Created by tejaswinidandi on 19/03/2020.
 */

@IsTest
private class SearchForDutchDossiersInvocableTest {
    @IsTest
    static void testSearchForDutchDossiers() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness mockWS = (IWsDutchBusiness)mocks.mock(IWsDutchBusiness.class);

        mocks.startStubbing();
        DutchBusinessWsdl.DutchBusinessEstablishmentReferencePagedResult resultPage1 = new DutchBusinessWsdl.DutchBusinessEstablishmentReferencePagedResult();
        resultPage1.paging = new DutchBusinessWsdl.ResultInfo();
        resultPage1.paging.curpage = 1;
        resultPage1.paging.numpages = 1;
        resultPage1.paging.perpage = 20;
        resultPage1.paging.numresults = 30;
        resultPage1.paging.maxresults = 500;
        resultPage1.results = new DutchBusinessWsdl.DutchBusinessEstablishmentReferenceArray();

        List<DutchBusinessWsdl.DutchBusinessEstablishmentReference> establishmentReferences= new List<DutchBusinessWsdl.DutchBusinessEstablishmentReference>();
        for (Integer i = 0; i < resultPage1.paging.numresults; i++) {
            DutchBusinessWsdl.DutchBusinessEstablishmentReference establishmentReference = new DutchBusinessWsdl.DutchBusinessEstablishmentReference();
            establishmentReference.dossier_number = 'dossier_number' + i;
            establishmentReference.indication_main_establishment = true;
            establishmentReference.trade_name = 'trade_name' + i;
            establishmentReference.legal_name = 'legal_name' + i;
            establishmentReference.correspondence_street = 'correspondence_street' + i;
            establishmentReference.correspondence_city = 'correspondence_city' + i;
            establishmentReference.establishment_street = 'establishment_street' + i;
            establishmentReference.establishment_city = 'establishment_city' + i;
            establishmentReference.match_type = 'match_type' + i;
            establishmentReference.establishment_number = 'establishment_number' + i;
            establishmentReferences.add(establishmentReference);
        }
        resultPage1.results.item = new List<DutchBusinessWsdl.DutchBusinessEstablishmentReference>();
        for (Integer i = 0; i < 20; i++) {
            resultPage1.results.item.add(establishmentReferences[i]);
        }
        mocks.when(mockWS.dutchBusinessSearch('1', 'trade_name', 'city', 'street', '1231', 1, 'a', '123123123', 'domain', true, 1)).thenReturn(resultPage1);

        mocks.stopStubbing();

        Application.Service.setMock(IWsDutchBusiness.class, mockWS);

        Test.startTest();
        List<SearchForDutchDossiersInvocable.SearchForDutchDossiersArgument> arguments = new List<SearchForDutchDossiersInvocable.SearchForDutchDossiersArgument>();
        SearchForDutchDossiersInvocable.SearchForDutchDossiersArgument argument = new SearchForDutchDossiersInvocable.SearchForDutchDossiersArgument();
        argument.street = 'street';
        argument.city = 'city';
        argument.house_number = 1;
        argument.telephone_number = '123123123';
        argument.domain_name = 'domain';
        argument.dossier_number = '1';
        argument.house_number_addition = 'a';
        argument.postcode = '1231';
        argument.strictSearch = true;
        argument.trade_name = 'trade_name';
        arguments.add(argument);
        List<List<Business_Dossier__c>> dossiers = SearchForDutchDossiersInvocable.searchForDutchDossiers(arguments);
        Test.stopTest();

        System.assert(dossiers.size() == 1);
        System.debug(dossiers[0].size());
        System.assert(dossiers[0].size() == 20);
        for (Business_Dossier__c businessDossier : dossiers[0]) {
            System.assert(businessDossier.Dossier_Number__c.startsWith('dossier_number'));
            System.assert(businessDossier.Indication_Main_Establishment__c = true);
            System.assert(businessDossier.Correspondence_Street__c.startsWith('correspondence_street'));
            System.assert(businessDossier.Correspondence_City__c.startsWith('correspondence_city'));
            System.assert(businessDossier.Establishment_Street__c.startsWith('establishment_street'));
            System.assert(businessDossier.Establishment_City__c.startsWith('establishment_city'));
            System.assert(businessDossier.Name.startsWith('legal_name'));
            System.assert(businessDossier.Trade_Name_Full__c.startsWith('trade_name'));
            System.assert(businessDossier.Establishment_Number__c.startsWith('establishment_number'));
        }
    }
}