force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dossier_Address__c/Dossier_Address__c.object-meta.xml
<CustomObject>
    <description>Establishment or Correspondence address of the Dossier</description>
    <label>Business Address</label>
    <nameField>
        <label>Business Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier_Address__c/fields/Business_Data__c.field-meta.xml
<CustomField>
    <fullName>Business_Data__c</fullName>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Business Addresses</relationshipLabel>
    <relationshipName>Business_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/selectors/main/classes/DossierAddressSelector.cls
/****************************************************************************************
Author          : DanNicholson
******************************************************************************************/
public with sharing class DossierAddressSelector extends fflib_SObjectSelector implements IDossierAddressSelector  {

    public DossierAddressSelector() {
        super(false, // Do not include FieldSet fields
                true,  // enforce Object level security
                true); // enforce Field level security
    }

    public static IDossierAddressSelector newInstance() {
        return (IDossierAddressSelector) Application.Selector.newInstance(Dossier_Address__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Dossier_Address__c.Id,
                Dossier_Address__c.Name,
                Dossier_Address__c.Business_Data__c,
                Dossier_Address__c.Business_Data__r.Id,
                Dossier_Address__c.Business_Data__r.name
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Dossier_Address__c.sObjectType;
    }


    public List<Dossier_Address__c> selectByDossierNumber(set<String> dossierNumSet){//, String sortedBy, String sortedDirection) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        List<Dossier_Address__c> result = new list<Dossier_Address__c>();
        queryFactory.setEnforceFLS(true);
        queryFactory.setCondition('Business_Data__r.Dossier_Number__c IN :dossierNumSet');
        queryFactory.setLimit(20);
        result = Database.query(queryFactory.toSOQL());
        return result;
    }

    public List<Dossier_Address__c> selectById(set<Id> addressIdSet){//, String sortedBy, String sortedDirection) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        List<Dossier_Address__c> result = new list<Dossier_Address__c>();
        queryFactory.setEnforceFLS(true);
        queryFactory.setCondition('Id IN :dosserIdSet');
        queryFactory.setLimit(20);
        result = Database.query(queryFactory.toSOQL());
        return result;
    }

}