force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/services/DutchBusiness/UpdateDutchDossierWithVATInvocableTest.cls
/**
 * Created by jaapbranderhorst on 03/03/2020.
 */

@IsTest
private class UpdateDutchDossierWithVATInvocableTest {
    @IsTest
    static void testHappyFlow() {
        // given
        // a dossier with a CoC number that returns a VAT number
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IDutchBusinessService dutchBusinessServiceMock = (IDutchBusinessService)mocks.mock(IDutchBusinessService.class);

        mocks.startStubbing();
        String dossierNumber = '1234';
        String VATNumber = '456';
        Business_Dossier__c dossier1 = new Business_Dossier__c(Name = 'test1', Dossier_Number__c = dossierNumber, Id = fflib_IDGenerator.generate(Business_Dossier__c.SObjectType));
        Business_Dossier__c dossier2 = dossier1.clone();
        dossier2.VAT_Number__c = VATNumber;
        mocks.when(dutchBusinessServiceMock.updateBusinessDossierWithVATNumber(dossier1)).thenReturn(dossier2);
        mocks.stopStubbing();

        Application.Service.setMock(IDutchBusinessService.class, dutchBusinessServiceMock);

        // when
        // the imvocable UpdateDossierWithVATInvocable is called
        Test.startTest();
        List<Business_Dossier__c> dossiersToAssert = UpdateDutchDossierWithVATInvocable.updateDutchDossiersWithVAT(new List<Business_Dossier__c>{dossier1});
        Test.stopTest();

        //then
        System.assert(dossiersToAssert.size() == 1);
        System.assert(dossiersToAssert[0].VAT_Number__c == VATNumber);
    }

    @IsTest
    static void testNoVATNumber() {
        // given
        // a dossier with a CoC number that returns a VAT number
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IDutchBusinessService dutchBusinessServiceMock = (IDutchBusinessService)mocks.mock(IDutchBusinessService.class);

        mocks.startStubbing();
        String dossierNumber = '1234';
        String VATNumber = '456';
        Business_Dossier__c dossier1 = new Business_Dossier__c(Name = 'test1', Dossier_Number__c = dossierNumber, Id = fflib_IDGenerator.generate(Business_Dossier__c.SObjectType));
        Business_Dossier__c dossier2 = dossier1.clone();
        mocks.when(dutchBusinessServiceMock.updateBusinessDossierWithVATNumber(dossier1)).thenReturn(dossier2);
        mocks.stopStubbing();

        Application.Service.setMock(IDutchBusinessService.class, dutchBusinessServiceMock);

        // when
        // the imvocable UpdateDossierWithVATInvocable is called
        Test.startTest();
        List<Business_Dossier__c> dossiersToAssert = UpdateDutchDossierWithVATInvocable.updateDutchDossiersWithVAT(new List<Business_Dossier__c>{dossier1});
        Test.stopTest();

        //then
        System.assert(dossiersToAssert.size() == 1);
        System.assert(dossiersToAssert[0].VAT_Number__c == null);
    }
}