force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city the organisation resides in according to CreditSafe</description>
    <inlineHelpText>The city the organisation resides in according to CreditSafe</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country this company is situated in according to CreditSafe</description>
    <inlineHelpText>The country this company is situated in according to CreditSafe</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <description>The house number of the address the organisation resides according to CreditSafe</description>
    <inlineHelpText>The house number of the address the organisation resides according to CreditSafe</inlineHelpText>
    <label>House Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>The street this organisation resides in according to CreditSafe</description>
    <inlineHelpText>The street this organisation resides in according to CreditSafe</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>The type of the organisation (Ltd, NonLtd etc.)</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dossier_Address__c/Dossier_Address__c.object-meta.xml
<CustomObject>
    <description>Establishment or Correspondence address of the Dossier</description>
    <label>Business Address</label>
    <nameField>
        <label>Business Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier_Address__c/fields/Business_Data__c.field-meta.xml
<CustomField>
    <fullName>Business_Data__c</fullName>
    <label>Business Data</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipLabel>Business Addresses</relationshipLabel>
    <relationshipName>Business_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dossier_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Correspondence</fullName>
                <default>true</default>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Establishment</fullName>
            </value>
            <value>
                <fullName>Creditsafe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/selectors/main/classes/DossierAddressSelectorTest.cls
/**
 * Created by jaapbranderhorst on 2019-06-22.
 */

@IsTest
private class DossierAddressSelectorTest {
    @TestSetup
    static void setup() {
        List<Business_Dossier__c> dossiers = new List<Business_Dossier__c>();
        for (Integer i = 0; i < 10; i++) {
            dossiers.add(new Business_Dossier__c(Name = '' + i));

        }
        insert dossiers;
        List<Dossier_Address__c> addresses = new List<Dossier_Address__c>();
        for (Business_Dossier__c businessDossier : dossiers) {
            addresses.add(addressCreator('Establishment', businessDossier.Id));
            addresses.add(addressCreator('Correspondence', businessDossier.Id));
        }
        insert addresses;
    }

    static Dossier_Address__c addressCreator(String type, Id dossierId) {
        Dossier_Address__c addressDB = new Dossier_Address__c();
        addressDB.Business_Data__c = dossierId;
        addressDB.Name = 'Name'; //dataVendorDossiercorrespondence_address_original_address;
        addressDB.Postcode__c = 'Postcode';
        addressDB.Street__c = 'Street';
        addressDB.City__c = 'City';
        addressDB.House_Number__c = '79';
        addressDB.House_Number_Addition__c = 'a';
        addressDB.Country__c = 'nl';
        addressDB.Type__c = type;
        return addressDB;
    }

    @IsTest
    static void testSelectByDossierId() {
        Map<Id, Business_Dossier__c> dossiersByIds = new Map<Id, Business_Dossier__c>([SELECT Id FROM Business_Dossier__c]);
        Test.startTest();
        List<Dossier_Address__c> selectedAddresses = DossierAddressSelector.newInstance().selectByDossierId(dossiersByIds.keySet());
        System.assert(selectedAddresses.size() == 20);
        for (Dossier_Address__c dossierAddress : selectedAddresses) {
            System.assert(!String.isEmpty(dossierAddress.Postcode__c));
            System.assert(!String.isEmpty(dossierAddress.Street__c));
            System.assert(!String.isEmpty(dossierAddress.City__c));
            System.assert(!String.isEmpty(dossierAddress.House_Number__c));
            System.assert(!String.isEmpty(dossierAddress.House_Number_Addition__c));
            System.assert(!String.isEmpty(dossierAddress.Country__c));
            System.assert(!String.isEmpty(dossierAddress.Type__c));
        }
    }
}