force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Dossier__c/fields/Dossier_Number__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Number__c</fullName>
    <description>The Chamber of Commerce number, consisting of 8 numbers (e.g., 00123456).  This number is unique and will not change as long as the organisation exists.  Subsidiaries (‘Nevenvestigingen’) of the organisation are registered using the same dossier number.</description>
    <externalId>true</externalId>
    <label>Chamber of Commerce Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Dossier__c/fields/Establishment_Number__c.field-meta.xml
<CustomField>
<fullName>Establishment_Number__c</fullName>
<description>The unique identifier for this business establishment, consisting of 12 numbers (e.g.  012345678912).  Optional.  Some businesses, mainly foundations (`Stichting`), do not have establishments.  In these instances the establishment_number is not returned.</description>
<label>Establishment Number</label>
<length>255</length>
<type>Text</type>
</CustomField>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/Datasource_Per_Country__mdt.object-meta.xml
<CustomObject>
    <description>Join object to join the data source CMDT with the ISO 3166 CMDT. Used to select the data source for a country for organisation searches</description>
    <label>Data source Per Country</label>
    <pluralLabel>Data source Per Countries</pluralLabel>
</CustomObject>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/Data_Source_Select_Record__c.field-meta.xml
<CustomField>
    <fullName>Data_Source_Select_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is the record that determines the selected data source for the country. There should only be one record per country with value true.</description>
    <inlineHelpText>True if this is the record that determines the selected data source for the country. There should only be one record per country with value true.</inlineHelpText>
    <label>Data source Select Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/ISO_3166_Entry__c.field-meta.xml
<CustomField>
    <fullName>ISO_3166_Entry__c</fullName>
    <description>The country (as ISO3166 code) for which the given data source can be selected</description>
    <inlineHelpText>The country (as ISO3166 code) for which the given data source can be selected</inlineHelpText>
    <label>ISO 3166 Entry</label>
    <referenceTo>ISO_3166_Entry__mdt</referenceTo>
    <relationshipLabel>Data source Per Countries</relationshipLabel>
    <relationshipName>Data_source_Per_Countries</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/ISO_3166_Entry__mdt.object-meta.xml
<CustomObject>
    <description>3 letter and 3 digit country codes according to ISO 3166</description>
    <label>ISO 3166 Entry</label>
    <pluralLabel>ISO 3166 Entries</pluralLabel>
</CustomObject>

force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <description>The 2 letter country code according to ISO 3166</description>
    <inlineHelpText>The 2 letter country code according to ISO 3166</inlineHelpText>
    <label>Alpha 2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The Country name according to ISO 3166</description>
    <label>Country Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/services/Business/BusinessServiceImpl.cls
/****************************************************************************************
Author          : Jaap Branderhorst
Description     : Service layer for Business dossier related functionality
******************************************************************************************/

public inherited sharing class BusinessServiceImpl implements IBusinessService {

    public static final Integer MAX_SEARCH_RESULTS = 1000;

    /**
     * Deletes the dossier with the given id with all related objects
     *
     * @param dossierId
     *
     */
    public void deleteDossier(Id dossierId, Boolean checkPermissions) {
        if (String.isNotEmpty(dossierId)) {
            List<Business_Dossier__c> dossierList = BusinessDossierSelector.newInstance().selectById(new Set<Id>{
                    dossierId
            });

            if (dossierList.size() == 1) {
                fflib_ISObjectUnitOfWork unitOfWork = null;
                if (checkPermissions) {
                    unitOfWork = Application.UnitOfWork.newInstance(new DMLWithCRUD());
                } else {
                    unitOfWork = Application.UnitOfWork.newInstance();
                }
                unitOfWork.registerDeleted(dossierList[0]);
                unitOfWork.commitWork();

                // TODO: commented for now. Must be added back when we move to update lists
                //if dossier is deleted, then remove it from the update list of dossiers on the company.info server
                //WsDutchBusiness.dutchBusinessUpdateRemoveDossier(dossierList[0].Dossier_Number__c, dossierList[0].Establishment_Number__c);
            }
        }
        else {
            throw new CCInputException(Label.Error_Input_Incorrect);
        }
    }

    public Map<String, String> getCountryOptionsForBusinessSearch() {
        // first get the appropriated datasourcePerCountries

        Set<Datasource_Per_Country__mdt> datasourcePerCountries = new Set<Datasource_Per_Country__mdt>();
        if (LicenseManagementService.userHasAccess(Feature.DUTCH_BUSINESS_GET_DOSSIER))
            datasourcePerCountries.addAll([
                    SELECT
                            ISO_3166_Entry__r.Country_Name__c,
                            ISO_3166_Entry__r.Alpha_2_Code__c,
                            ISO_3166_Entry__r.Label,
                            ISO_3166_Entry__c
                    FROM Datasource_Per_Country__mdt WHERE Data_Source_Select_Record__c = TRUE AND ISO_3166_Entry__r.Alpha_2_Code__c = 'NL']); // doesn't matter what the data source selected is, user has access
        if (LicenseManagementService.userHasAccess(Feature.INTERNATIONAL_BUSINESS_SEARCH)) {
            datasourcePerCountries.addAll([
                    SELECT
                            ISO_3166_Entry__r.Country_Name__c,
                            ISO_3166_Entry__r.Alpha_2_Code__c,
                            ISO_3166_Entry__r.Label,
                            ISO_3166_Entry__c
                    FROM Datasource_Per_Country__mdt
                    WHERE Data_Source_Select_Record__c = TRUE]); // user can search in all countries so we need to return all values
        }

        // next get the  map
        Map<String, String> countryCodesByTranslatedCountryNames = new Map<String, String>();
        for (Datasource_Per_Country__mdt datasourcePerCountry : datasourcePerCountries) {
            String translatedCountry = translatedCountryByAlpha3Code.get(datasourcePerCountry.ISO_3166_Entry__r.Label);
            if (translatedCountry != null)
                countryCodesByTranslatedCountryNames.put(translatedCountry, datasourcePerCountry.ISO_3166_Entry__r.Alpha_2_Code__c);
        }
        return countryCodesByTranslatedCountryNames;
    }

    // TODO: move this to a constant util class in the ISO 3166 dir?
    private final static Map<String, String> translatedCountryByAlpha3Code = new Map<String, String> {
            'BEL' => Label.Country_Belgium,
            'NLD' => Label.Country_Netherlands,
            'GBR' => Label.Country_United_Kingdom,
            'IRE' => Label.Country_Ireland,
            'ITA' => Label.Country_Italy,
            'NOR' => Label.Country_Norway,
            'SWE' => Label.Country_Sweden,
            'ESP' => Label.Country_Spain,
            'DEU' => Label.Country_Germany,
            'FRA' => Label.Country_France,
            'DNK' => Label.Country_Denmark
    };
}