force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/Business_Data_SBI__c.object-meta.xml
<CustomObject>
    <description>A DutchBusiness Company SBI Collection.</description>
    <label>SBI Code</label>
    <nameField>
        <displayFormat>SBI-{000000}</displayFormat>
        <label>SBI Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SBI Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <label>Business Dossier</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipName>SBIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/services/DutchBusiness/InstantiateBusinessDossierInvocableTest.cls
/**
 * Created by hugovankrimpen on 08/07/2020.
 */

@IsTest
public class InstantiateBusinessDossierInvocableTest {


    @IsTest
    public static void instantiateBusinessDossierHappyFlow(){
        string dossierNumber = '1234';
        string establishmentNumber = '5678';
        initiateMockResponse(dossierNumber, establishmentNumber);

        InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument argument = new InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument();
        argument.dossierNumber = dossierNumber;
        argument.establishmentNumber = establishmentNumber;

        Test.startTest();
        List<Business_Dossier__c> businessDossiers =
                InstantiateBusinessDossierInvocable.instantiateBusinessDossier(
                        new List<InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument>{argument}
                );
        Test.stopTest();
        System.assertNotEquals(null,businessDossiers);
        System.assertEquals(1,businessDossiers.size());
        System.assertNotEquals(null,businessDossiers[0].SBIs__r);
        System.assertEquals(10,businessDossiers[0].SBIs__r.size());
    }
    @IsTest
    public static void instantiateBusinessDossierErrorFlow(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness webserviceMock = (IWsDutchBusiness)mocks.mock(IWsDutchBusiness.class);

        string dossierNumber = '1234';
        string establishmentNumber = '5678';

        mocks.startStubbing();
        mocks.when(webserviceMock.dutchBusinessGetDossierV3(dossierNumber, establishmentNumber)).thenReturn(null);
        mocks.stopStubbing();

        Application.Service.setMock(IWsDutchBusiness.class, webserviceMock);

        InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument argument = new InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument();
        argument.dossierNumber = dossierNumber;
        argument.establishmentNumber = establishmentNumber;

        Test.startTest();
        try {
            List<Business_Dossier__c> businessDossiers =
                    InstantiateBusinessDossierInvocable.instantiateBusinessDossier(
                            new List<InstantiateBusinessDossierInvocable.InstantiateBusinessDossierArgument>{argument}
                    );
            System.assert(false);
        }catch (Exception e){
            System.assert(true);
        }
    }

    @TestVisible
    private static void initiateMockResponse(String dossierNumber, String establishmentNumber){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWsDutchBusiness webserviceMock = (IWsDutchBusiness)mocks.mock(IWsDutchBusiness.class);



        mocks.startStubbing();
        DutchBusinessWsdl.DutchBusinessDossierV3 dossierWSDL = DutchBusinessServiceImplTest.getDataVendorMockDossier();

        mocks.when(webserviceMock.dutchBusinessGetDossierV3(dossierNumber, establishmentNumber)).thenReturn(dossierWSDL);
        mocks.stopStubbing();

        Application.Service.setMock(IWsDutchBusiness.class, webserviceMock);
    }

}