force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/Business_Data_SBI__c.object-meta.xml
<CustomObject>
    <description>A DutchBusiness Company SBI Collection.</description>
    <label>SBI Code</label>
    <nameField>
        <displayFormat>SBI-{000000}</displayFormat>
        <label>SBI Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SBI Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <label>Business Dossier</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipName>SBIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/services/Business/BusinessServiceImplTest.cls
@isTest
public with sharing class BusinessServiceImplTest {

    @IsTest
    public static void testDeleteDossierHappyFlow() {
        // given
        // a business dossier, a SBI code and an address in the DB
        Business_Dossier__c dossier = new Business_Dossier__c(Name = 'test');
        insert dossier;
        Business_Data_SBI__c sb = new Business_Data_SBI__c(Business_Dossier__c = dossier.Id);
        insert sb;

        // when
        Test.startTest();
        BusinessService.deleteDossier(dossier.Id, false);
        Test.stopTest();

        // then
        // no objects any more
        System.assert([SELECT Id FROM Business_Dossier__c].size() == 0);
        System.assert([SELECT Id FROM Business_Data_SBI__c].size() == 0);
    }

    @IsTest
    public static void testGetCountryOptionsForBusinessSearchDutchBusiness() {
        Test.startTest();
        Map<String, String> countryOptions = null;
        System.runAs(TestUtils.getDutchBusinessUser()) {
            countryOptions = BusinessService.getCountryOptionsForBusinessSearch();
        }
        Test.stopTest();
        System.assertEquals(1, countryOptions.size());
        System.assertEquals('NL', countryOptions.values().get(0));
        System.assertEquals(true, countryOptions.containsKey(Label.Country_Netherlands));
    }

}