force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/Business_Data_SBI__c.object-meta.xml
<CustomObject>
    <description>A DutchBusiness Company SBI Collection.</description>
    <label>SBI Code</label>
    <nameField>
        <displayFormat>SBI-{000000}</displayFormat>
        <label>SBI Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SBI Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/Business_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Business_Dossier__c</fullName>
    <label>Business Dossier</label>
    <referenceTo>Business_Dossier__c</referenceTo>
    <relationshipName>SBIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Data_SBI__c/fields/SBI_Code__c.field-meta.xml
<CustomField>
    <fullName>SBI_Code__c</fullName>
    <description>A SBI(‘Standaard Bedrijfs Indeling’) code, a number up to six characters in length.</description>
    <label>SBI Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/SBI_Description__c.field-meta.xml
<CustomField>
    <fullName>SBI_Description__c</fullName>
    <description>Description of the SBI code.</description>
    <label>SBI Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Data_SBI__c/fields/SBI_Type__c.field-meta.xml
<CustomField>
    <fullName>SBI_Type__c</fullName>
    <description>SBI collection type</description>
    <label>SBI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>original</fullName>
            </value>
            <value>
                <fullName>company_info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/modules/businessDossier/objects/Business_Dossier__c/Business_Dossier__c.object-meta.xml
<CustomObject>
    <description>Information on a business establishment including information related to finance and structure.</description>
    <label>Business Dossier</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/selectors/main/classes/SbiCodeSelector.cls
/**
 * Created by jaapbranderhorst on 2019-06-18.
 */

public with sharing class SbiCodeSelector extends fflib_SObjectSelector implements ISbiCodeSelector {


    public SbiCodeSelector() {
//        super(false,
//                true,
//                true);
    }

    public static ISbiCodeSelector newInstance() {
        return (ISbiCodeSelector) Application.Selector.newInstance(Business_Data_SBI__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Business_Data_SBI__c.Id,
                Business_Data_SBI__c.Name,
                Business_Data_SBI__c.Business_Dossier__c,
                Business_Data_SBI__c.SBI_Code__c,
                Business_Data_SBI__c.SBI_Description__c,
                Business_Data_SBI__c.SBI_Type__c

        };
    }

    public Schema.SObjectType getSObjectType() {
        return Business_Data_SBI__c.sObjectType;
    }

    public List<Business_Data_SBI__c> selectByDossierId(set<Id> dossierIdSet){//, String sortedBy, String sortedDirection) {
        fflib_QueryFactory queryFactory = newQueryFactory();
        List<Business_Data_SBI__c> result = new List<Business_Data_SBI__c>();
        queryFactory.setCondition('Business_Dossier__c IN :dossierIdSet');
        System.debug('SOQL selectByDossierid: ' + queryFactory.toSOQL());
        result = Database.query(queryFactory.toSOQL());
        System.debug('found records: ' + result);
        return result;
    }

}