force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/Datasource_Per_Country__mdt.object-meta.xml
<CustomObject>
    <description>Join object to join the data source CMDT with the ISO 3166 CMDT. Used to select the data source for a country for organisation searches</description>
    <label>Data source Per Country</label>
    <pluralLabel>Data source Per Countries</pluralLabel>
</CustomObject>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/Data_source__c.field-meta.xml
<CustomField>
    <fullName>Data_source__c</fullName>
    <description>The data source that can be used to search for organisations for this country</description>
    <inlineHelpText>The data source that can be used to search for organisations for this country</inlineHelpText>
    <label>Data source</label>
    <referenceTo>Data_source__mdt</referenceTo>
    <relationshipLabel>Data source Per Countries</relationshipLabel>
    <relationshipName>Data_source_Per_Countries</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/ISO_3166_Entry__c.field-meta.xml
<CustomField>
    <fullName>ISO_3166_Entry__c</fullName>
    <description>The country (as ISO3166 code) for which the given data source can be selected</description>
    <inlineHelpText>The country (as ISO3166 code) for which the given data source can be selected</inlineHelpText>
    <label>ISO 3166 Entry</label>
    <referenceTo>ISO_3166_Entry__mdt</referenceTo>
    <relationshipLabel>Data source Per Countries</relationshipLabel>
    <relationshipName>Data_source_Per_Countries</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/ISO_3166_Entry__mdt.object-meta.xml
<CustomObject>
    <description>3 letter and 3 digit country codes according to ISO 3166</description>
    <label>ISO 3166 Entry</label>
    <pluralLabel>ISO 3166 Entries</pluralLabel>
</CustomObject>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The 3 digit country code according to ISO 3166</description>
    <inlineHelpText>The 3 digit country code according to ISO 3166</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The Country name according to ISO 3166</description>
    <label>Country Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/modules/setup/ConfigOrgPerCountryDataSourceController.cls
/**
 * Created by jaapbranderhorst on 26/06/2020.
 */

public with sharing class ConfigOrgPerCountryDataSourceController {

    public class DataSourceOption {

        @AuraEnabled
        public String label { get; set; }

        @AuraEnabled
        public String value { get; set; }

        public DataSourceOption(Datasource_Per_Country__mdt datasourcePerCountry) {
            this.label = datasourcePerCountry.Data_source__r.Label;
            this.value = datasourcePerCountry.Data_source__r.DeveloperName;
        }
    }

    public class DataSourcesPerCountry {
        @AuraEnabled
        public String country { get; set; }

        @AuraEnabled
        public String countryCode {get; set;}

        @AuraEnabled
        public String selectedDataSource {get; set;}

        @AuraEnabled
        public List<DataSourceOption> dataSourceOptions { get; set; }

        public DataSourcesPerCountry(String countryCode, List<Datasource_Per_Country__mdt> datasourcePerCountriesOptions) {
            Datasource_Per_Country__mdt datasourcePerCountry = datasourcePerCountriesOptions.get(0);
            this.country = datasourcePerCountry.ISO_3166_Entry__r.Country_Name__c;
            this.countryCode = datasourcePerCountry.ISO_3166_Entry__r.Country_Code__c;
            this.selectedDataSource = SetupService.getSelectedDataSource(this.countryCode).DeveloperName;
            List<DataSourceOption> dataSourceOptions = new List<DataSourceOption>();
            for (Datasource_Per_Country__mdt datasourcePerCountry2 : datasourcePerCountriesOptions) {
                dataSourceOptions.add(new DataSourceOption(datasourcePerCountry2));
            }
            this.dataSourceOptions = dataSourceOptions;
        }

        public DataSourcesPerCountry() {}
    }

    @AuraEnabled(Cacheable=true)
    public static List<DataSourcesPerCountry> getDataSourcesPerCountry() {
        try {
            List<Datasource_Per_Country__mdt> datasourcePerCountries = SetupService.getDataSourcesPerCountry();
            List<DataSourcesPerCountry> returnValue = new List<DataSourcesPerCountry>();
            Map<String, List<Datasource_Per_Country__mdt>> datasourcePerCountriesByCountryCode = new Map<String, List<Datasource_Per_Country__mdt>>();
            for (Datasource_Per_Country__mdt datasourcePerCountry : datasourcePerCountries) {
                String countryCode = datasourcePerCountry.ISO_3166_Entry__r.Country_Code__c;
                List<Datasource_Per_Country__mdt> datasourcePerCountries2 = datasourcePerCountriesByCountryCode.get(countryCode);
                if (datasourcePerCountries2 == null) {
                    datasourcePerCountries2 = new List<Datasource_Per_Country__mdt>();
                    datasourcePerCountriesByCountryCode.put(countryCode, datasourcePerCountries2);
                }
                datasourcePerCountries2.add(datasourcePerCountry);
            }
            for (String countryCode : datasourcePerCountriesByCountryCode.keySet()) {
                returnValue.add(new DataSourcesPerCountry(countryCode, datasourcePerCountriesByCountryCode.get(countryCode)));
            }
            return returnValue;
        }catch (Exception e){
            ErrorLogUtil.logException(e,true);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void setDataSourcePerCountry(List<DataSourcesPerCountry> dataSourcesPerCountries) {
        try {
            System.debug('dataSourcesPerCountries: ' + JSON.serializePretty(dataSourcesPerCountries));
            Map<String, String> selectedDataSourceByCountryId = new Map<String, String>();
            for (DataSourcesPerCountry dataSourcesPerCountry : dataSourcesPerCountries) {
                selectedDataSourceByCountryId.put(dataSourcesPerCountry.countryCode, dataSourcesPerCountry.selectedDataSource);
            }
            System.debug('selectedDataSourceByCountryId:  ' + JSON.serializePretty(selectedDataSourceByCountryId));
            SetupService.setDataSourcePerCountry(selectedDataSourceByCountryId);
        } catch(Exception e) {
            ErrorLogUtil.logException(e,true);
            throw new AuraHandledException(e.getMessage());
        }
    }

}