force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/Datasource_Per_Country__mdt.object-meta.xml
<CustomObject>
    <description>Join object to join the data source CMDT with the ISO 3166 CMDT. Used to select the data source for a country for organisation searches</description>
    <label>Data source Per Country</label>
    <pluralLabel>Data source Per Countries</pluralLabel>
</CustomObject>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/Data_source__c.field-meta.xml
<CustomField>
    <fullName>Data_source__c</fullName>
    <description>The data source that can be used to search for organisations for this country</description>
    <inlineHelpText>The data source that can be used to search for organisations for this country</inlineHelpText>
    <label>Data source</label>
    <referenceTo>Data_source__mdt</referenceTo>
    <relationshipLabel>Data source Per Countries</relationshipLabel>
    <relationshipName>Data_source_Per_Countries</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/Data_Source_Select_Record__c.field-meta.xml
<CustomField>
    <fullName>Data_Source_Select_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is the record that determines the selected data source for the country. There should only be one record per country with value true.</description>
    <inlineHelpText>True if this is the record that determines the selected data source for the country. There should only be one record per country with value true.</inlineHelpText>
    <label>Data source Select Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/modules/setup/objects/Datasource_Per_Country__mdt/fields/ISO_3166_Entry__c.field-meta.xml
<CustomField>
    <fullName>ISO_3166_Entry__c</fullName>
    <description>The country (as ISO3166 code) for which the given data source can be selected</description>
    <inlineHelpText>The country (as ISO3166 code) for which the given data source can be selected</inlineHelpText>
    <label>ISO 3166 Entry</label>
    <referenceTo>ISO_3166_Entry__mdt</referenceTo>
    <relationshipLabel>Data source Per Countries</relationshipLabel>
    <relationshipName>Data_source_Per_Countries</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/ISO_3166_Entry__mdt.object-meta.xml
<CustomObject>
    <description>3 letter and 3 digit country codes according to ISO 3166</description>
    <label>ISO 3166 Entry</label>
    <pluralLabel>ISO 3166 Entries</pluralLabel>
</CustomObject>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The 3 digit country code according to ISO 3166</description>
    <inlineHelpText>The 3 digit country code according to ISO 3166</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The Country name according to ISO 3166</description>
    <label>Country Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/modules/objects/Protected_Subscriber_Setting__mdt/Protected_Subscriber_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Contains Subscriber settings which 
-Should not be overwritten when a new package version is installed
-Should not be changed through the custom metadata types interface</description>
    <label>Protected Subscriber Setting</label>
    <pluralLabel>Protected Subscriber Settings</pluralLabel>
</CustomObject>

force-app/main/modules/setup/objects/Protected_Subscriber_Setting__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A field to store a description of this setting.</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/modules/setup/objects/Protected_Subscriber_Setting__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <description>A field to store a true or false value for this setting.</description>
    <defaultValue>false</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/modules/setup/objects/Protected_Subscriber_Setting__mdt/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>This field stores an identifier value of another system.</description>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/services/Setup/SetupServiceImpl.cls
/**
 * Created by Hugo on 04/06/2020.
 */

public with sharing class SetupServiceImpl implements ISetupService {

    public inherited sharing class CustomMetadataCallback implements Metadata.DeployCallback {
        public void handleResult(Metadata.DeployResult result, Metadata.DeployCallbackContext context) {
            if (result.status == Metadata.DeployStatus.Succeeded) {
            } else {

            }
        }
    }

    public List<Protected_Subscriber_Setting__mdt> getUpdateTypes(){
        List<Protected_Subscriber_Setting__mdt> updateTypes = [
                SELECT id, DeveloperName, MasterLabel, Label, External_Id__c, Enabled__c, Description__c
                FROM Protected_Subscriber_Setting__mdt
                WHERE DeveloperName LIKE '%Update_Type_%'
                WITH SECURITY_ENFORCED
                ORDER BY MasterLabel
        ];
        return updateTypes;
    }

    public Data_source__mdt getSelectedDataSource(String countryCode) {
        List<Datasource_Per_Country__mdt> datasourcePerCountries = [
                SELECT Data_source__c
                FROM Datasource_Per_Country__mdt
                WHERE Data_Source_Select_Record__c = TRUE AND ISO_3166_Entry__r.Country_Code__c = :countryCode WITH SECURITY_ENFORCED];
        if (datasourcePerCountries != null && datasourcePerCountries.size() == 1) {
            Data_source__mdt dataSource = [
                    SELECT
                            DeveloperName,
                            Id,
                            Label,
                            Language,
                            MasterLabel,
                            NamespacePrefix,
                            QualifiedApiName
                    FROM Data_source__mdt WHERE Id = :datasourcePerCountries.get(0).Data_source__c WITH SECURITY_ENFORCED];
            return dataSource;
        } else {
            throw new InputException('Found no or too many data sources selected for country code ' + countryCode);
        }
    }

    public List<Datasource_Per_Country__mdt> getDataSourcesPerCountry() {
        List<Datasource_Per_Country__mdt> datasourcePerCountries = [
                SELECT
                        Data_source__r.Label,
                        Data_source__r.DeveloperName,
                        Data_source__c,
                        Data_Source_Select_Record__c,
                        ISO_3166_Entry__c,
                        ISO_3166_Entry__r.Country_Code__c,
                        ISO_3166_Entry__r.Label,
                        ISO_3166_Entry__r.Country_Name__c,
                        DeveloperName,
                        Id,
                        Label,
                        Language,
                        MasterLabel,
                        NamespacePrefix,
                        QualifiedApiName
                FROM Datasource_Per_Country__mdt WHERE Data_Source_Select_Record__c = FALSE WITH SECURITY_ENFORCED];
        return datasourcePerCountries;
    }

    public Id setUpdateTypes(List<Map<string, object>> payload) {
        string updateTypeAPIName = String.valueOf(appsolutely__Protected_Subscriber_Setting__mdt.getSObjectType());
        List<Protected_Subscriber_Setting__mdt> updateTypes = SetupService.getUpdateTypes();
        CustomMetadataCallback callback = new CustomMetadataCallback();

        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
        for(Map<string, object> mdRecord : payload ){

            boolean checked = Boolean.valueOf(mdRecord.get('checked'));
            string developerName = String.valueOf(mdRecord.get('developerName')); //RecordName = DeveloperName
            string masterLabel = String.valueOf(mdRecord.get('label'));

            if(checked == null || developerName == null || masterLabel == null){
                throw new InputException(Label.Error_Input_Incorrect);
            }
            Metadata.CustomMetadata customMetadata = new Metadata.CustomMetadata();
            customMetadata.fullName = updateTypeAPIName + '.' + developerName; //RecordName = DeveloperName
            customMetadata.label = masterLabel;

            Metadata.CustomMetadataValue customField = new Metadata.CustomMetadataValue();
            customField.field = String.valueOf(Protected_Subscriber_Setting__mdt.Enabled__c);
            customField.value = checked;
            customMetadata.values.add(customField);

            mdContainer.addMetadata(customMetadata);
        }
        //Cannot update an empty container.
        if(mdContainer.getMetadata().size() == 0){
            return null;
        }

        Id jobId;
        try{
            jobId = Metadata.Operations.enqueueDeployment(mdContainer, callback);
        }catch (Exception e){
            MetadataOperationException metadataOperationException = new MetadataOperationException(Label.Error_updating_update_type_settings);
            metadataOperationException.setMessage(Label.Error_updating_update_type_settings); //Explicitly set the message so it can be read in apex as well.
            throw metadataOperationException;
        }
        return jobId;

    }


}