force-app/main/appsolutelyBaseComponents/iso3166/objects/ISO_3166_Entry__mdt/ISO_3166_Entry__mdt.object-meta.xml
<CustomObject>
    <description>3 letter and 3 digit country codes according to ISO 3166</description>
    <label>ISO 3166 Entry</label>
    <pluralLabel>ISO 3166 Entries</pluralLabel>
</CustomObject>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The 3 digit country code according to ISO 3166</description>
    <inlineHelpText>The 3 digit country code according to ISO 3166</inlineHelpText>
    <label>Country Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ISO_3166_Entry__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>The Country name according to ISO 3166</description>
    <label>Country Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Iso3166CountryPickListController.cls
/**
 * Created by jaapbranderhorst on 12/03/2020.
 */

public inherited sharing class Iso3166CountryPickListController {

    public class Iso3166Option {

        @AuraEnabled
        public String country { get; set; }

        @AuraEnabled
        public String alpha3Code {get; set; }

        @AuraEnabled
        public String countryCode { get; set; }

        public Iso3166Option(String country, String alpha3Code, String countryCode) {
            this.country = country;
            this.alpha3Code = alpha3Code;
            this.countryCode = countryCode;
        }
    }

    /**
     * loads all ISO3166 metadata fields and returns them as options for a picklist
     *
     * @return
     */
    @AuraEnabled(cacheable=true)
    public static List<Iso3166Option> getIso3166Options() {
        List<ISO_3166_Entry__mdt> iso3166Entries = [SELECT Country_Code__c, Country_Name__c, Label FROM ISO_3166_Entry__mdt ORDER BY Country_Name__c];
        List<Iso3166Option> options = new List<Iso3166CountryPickListController.Iso3166Option>();
        for (ISO_3166_Entry__mdt o3166Entry : iso3166Entries) {
            options.add(new Iso3166Option(o3166Entry.Country_Name__c, o3166Entry.Label, o3166Entry.Country_Code__c));
        }
        return options;
    }

}