force-app/main/default/objects/SEPA_Bank_Account__c/SEPA_Bank_Account__c.object-meta.xml
<CustomObject>
    <description>Stores information about a SEPA Bank Account. The name of the bank account is equal to the IBAN number.</description>
    <label>SEPA Bank Account</label>
    <nameField>
        <label>SEPA Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEPA Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEPA_Bank_Account__c/fields/Account_Holder_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Type__c</fullName>
    <description>The type of the account holder
NP = Natural Person
ORG = Organization</description>
    <label>Account Holder Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>ORG</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEPA_Bank_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the account is active or not.</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SEPA_Bank_Account__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country code of where the account is registered.</description>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEPA_Bank_Account__c/fields/Foreign__c.field-meta.xml
<CustomField>
    <fullName>Foreign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the bank account is foreign or not.</description>
    <label>Foreign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/services/Sepa/SepaServiceImpl.cls
/**
 * Created by hugovankrimpen on 01/07/2020.
 */

public with sharing class SepaServiceImpl implements ISepaService{


    public static SEPA_Bank_Account__c getSepaMatchAccountHolder(String IBAN,String accountHolderName){
        //do something
        SepaWsdl.SepaMatchAccountHolderResult sepaMatchAccountHolderResult;
        try {
            sepaMatchAccountHolderResult = WsSepa.sepaMatchAccountHolder(IBAN, accountHolderName);
        }
        catch (CalloutException calloutException){
            //This exception is thrown when the IBAN or AccountHolderName are incorrect.
            throw calloutException;
        }
        catch (Exception e){
            //This should hopefully never happen.
            throw e;
        }

        if(sepaMatchAccountHolderResult != null){
            //If its a match, create it! -OR-
            //If its mistype, create it only if its an ORGANIZATION
            if(sepaMatchAccountHolderResult.name_matching_result.type_x == 'MATCHING' ||
                    (   sepaMatchAccountHolderResult.name_matching_result != null &&
                            sepaMatchAccountHolderResult.name_matching_result.type_x == 'MISTYPE' &&
                            sepaMatchAccountHolderResult.bank_account_holder != null &&
                            sepaMatchAccountHolderResult.bank_account_holder.type_x == 'ORG')){
                return createSEPABankAccount(sepaMatchAccountHolderResult);
            }
        }
        return null;
    }
    public void saveSEPABankAccounts(List<SEPA_Bank_Account__c> sepaBankAccounts){
        //Insert Existing SEPA Bank Account Ids
        insertExistingSEPABankAccountsIds(sepaBankAccounts);
        fflib_ISObjectUnitOfWork unitOfWork = Application.UnitOfWork.newInstance();
        unitOfWork.registerUpsert(sepaBankAccounts);
        unitOfWork.commitWork();
    }


    /****************************/
    /** IMPLEMENTATION METHODS **/
    /****************************/

    private static SEPA_Bank_Account__c createSEPABankAccount(SepaWsdl.SepaMatchAccountHolderResult sepaMatchAccountHolderResults){
        SEPA_Bank_Account__c sepaBankAccount = new SEPA_Bank_Account__c();
        sepaBankAccount.Name = sepaMatchAccountHolderResults.iban;
        sepaBankAccount.Active__c = (sepaMatchAccountHolderResults.bank_account_details.status == 'ACTIVE');
        sepaBankAccount.Country_Code__c = sepaMatchAccountHolderResults.bank_account_details.country_code;
        sepaBankAccount.Foreign__c = sepaMatchAccountHolderResults.bank_account_details.foreign;
        sepaBankAccount.Account_Holder_Type__c = sepaMatchAccountHolderResults.bank_account_holder.type_x;
        return sepaBankAccount;
    }

    private static void insertExistingSEPABankAccountsIds(List<SEPA_Bank_Account__c> sepaBankAccounts){
        System.debug(sepaBankAccounts);
        Set<String> IBANs = new Set<String>();
        for(SEPA_Bank_Account__c sepaBankAccount : sepaBankAccounts){
            IBANs.add(sepaBankAccount.Name);
        }
        List<SEPA_Bank_Account__c> existingSEPABankAccounts = [SELECT Id, Name FROM SEPA_Bank_Account__c WHERE Name IN :IBANs];
        Map<String, SEPA_Bank_Account__c> existingSEPABankAccountsMap = new Map<String, SEPA_Bank_Account__c>();
        for(SEPA_Bank_Account__c existingSEPABankAccount : existingSEPABankAccounts){
            existingSEPABankAccountsMap.put(existingSEPABankAccount.Name, existingSEPABankAccount);
        }
        for(SEPA_Bank_Account__c sepaBankAccount : sepaBankAccounts){
            if(existingSEPABankAccountsMap.containsKey(sepaBankAccount.Name)){
                sepaBankAccount.Id = existingSEPABankAccountsMap.get(sepaBankAccount.Name).Id;
            }
        }
    }

}