force-app/main/standard/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Logs errors fired throughout the application. Purely to ease the maintenance. No access needed for users of the app or admins.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <description>The cause of the error</description>
    <inlineHelpText>The cause of the error</inlineHelpText>
    <label>Cause</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Error_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Address__c</fullName>
    <defaultValue>$CustomMetadata.Setting__mdt.Error_Email_Address.Value__c</defaultValue>
    <label>Error Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/standard/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number the error occurred on.</description>
    <inlineHelpText>The line number the error occurred on.</inlineHelpText>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/standard/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The message logged. Message of the exception if an exception has been logged.</description>
    <inlineHelpText>The message logged</inlineHelpText>
    <label>Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set in the handleAfterEventInsert method to true if an email needs to be send to the support email address configured in the Setting error email. If checked the after insert trigger on Error Log itself will send an email to the support email address. See https://salesforce.stackexchange.com/questions/221708/does-messaging-sendemail-not-work-in-a-platform-event-trigger-context</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>The stacktrace&#39; exception to log</description>
    <inlineHelpText>The stacktrace&#39; exception to log</inlineHelpText>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/appsolutelyBaseComponents/errorLogUtil/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The exception type</description>
    <inlineHelpText>The exception type</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogUtilAccessTest.cls
/**
 * Created by jaapbranderhorst on 02/07/2020.
 */

@IsTest
private class ErrorLogUtilAccessTest {
    @IsTest
    static void testBehavior() {
        Test.startTest();
        {
            System.runAs(CompanyInfoTestUserFactory.getDutchBusinessUser()) {
                ErrorLogUtil.logException(new CustomException('test'));
            }
        }
        Test.stopTest();
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();
        errorLogs = [
                SELECT
                        Cause__c,
                        Error_Email_Address__c,
                        Line_Number__c,
                        Message__c,
                        Send_Email__c,
                        Stacktrace__c,
                        Type__c,
                        CreatedById,
                        CreatedDate,
                        Id,
                        IsDeleted,
                        LastModifiedById,
                        LastModifiedDate,
                        LastReferencedDate,
                        LastViewedDate,
                        Name,
                        OwnerId,
                        SystemModstamp
                FROM Error_Log__c];
        System.assertEquals(1, errorLogs.size());
        System.assertEquals('test', errorLogs.get(0).Message__c);
    }
}